### ISSUE TITLE
Problem with page ui-components/typesoftoolbarbuttons.md

### ISSUE THREAD

**Issue by awan2008** [tinymce/tinymce-docs#1000]
In tinyMCE 4, I can do something like this:
keywordMenu['onclick'] = function (props) {
                                            ed.insertContent(props.toElement.textContent)

However, in tinyMCE 5, I found that onclick is replaced by onAction, but onAction API does not have anything I could pass in to the content.

> *affected page: https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/*

**Comment by tylerkelly13** [comment]
@awan2008, looks like the `insertContent` is still valid, See the example shown at: https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#menubuttonexampleandexplanation
API docs entry: https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#insertcontent

Please reopen or create a new issue if this issue should not have been closed.
