### ISSUE TITLE
TinyMCE v4 Checkbox doc url is broken

### ISSUE THREAD

**Issue by DamChtlv** [tinymce/tinymce-docs#1004]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- Doc url is broken [Checkbox v4 docs](http://archive.tinymce.com/wiki.php/api4:class.tinymce.ui.Checkbox)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
- Urls from the archive doesn't work anymore, there is no redirection : [Checkbox v4](http://archive.tinymce.com/wiki.php/api4:class.tinymce.ui.Checkbox).

**What is the expected behavior?**
- Redirection to the docs.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- Any browser, TinyMCE v4

**Comment by tylerkelly13** [comment]
Sorry for the slow response. 
http://archive.tinymce.com has been depreciated and now redirects to the TinyMCE 5 docs. 
For the TinyMCE 4 Docs site, visit: https://www.tiny.cloud/docs-4x/
