### ISSUE TITLE
Problem with page /docs/demo/format-custom.md

### ISSUE THREAD

**Issue by al1357** [tinymce/tinymce-docs#1006]
Code sample does not load. Error in console: 

"SyntaxError: expected expression, got end of script"

> *affected page: https://www.tiny.cloud/docs/demo/format-custom/*

**Comment by Afraithe** [comment]
Seems to load for me?

**Comment by alecpl** [comment]
@Afraithe, there are about four tickets about this issue here. I think all of them are about v4 and the expectation to see the custom format in UI.

**Comment by tylerkelly13** [comment]
I've been unsuccessful in reproducing this issue in Chrome and Firefox.
This issue appears to be resolved.
Please reopen or create a new issue if this issue should not have been closed.
