### ISSUE TITLE
Problem with page plugins/imagetools.md

### ISSUE THREAD

**Issue by Exonfang** [tinymce/tinymce-docs#1010]
There is no documentation on how to add your own custom buttons to the imagetools_toolbar... It's been such a struggle trying to find where the code snippets outlined in the documentation go as there is often no context given other than the specific snippets...

> *affected page: https://www.tiny.cloud/docs-4x/plugins/imagetools/*

**Comment by tylerkelly13** [comment]
@Exonfang, the page: https://www.tiny.cloud/docs-4x/advanced/creating-a-custom-button/#basicbutton does provide a simple example which can be used to create a custom button on the imagetools_toolbar.
For example:
```
tinymce.init({
    selector: "textarea",
    plugins: [
        "image imagetools"
    ],
	toolbar: "image mybutton",
    imagetools_toolbar: "rotateleft rotateright | flipv fliph | editimage imageoptions mybutton",
    setup: function(editor) {
    editor.addButton('mybutton', {
       text: "My Button",
       onclick: function () {
           alert("My Button clicked!");
      }
    });
  }
});
```

**Comment by tylerkelly13** [comment]
This issue appears to have been resolved.
Please reopen or create a new issue if this issue should not have been closed.
