### ISSUE TITLE
Problem with page demo/format-custom.md

### ISSUE THREAD

**Issue by richardwo** [tinymce/tinymce-docs#1026]
The example doesn't work.

> *affected page: https://www.tiny.cloud/docs/demo/format-custom/*

**Comment by Afraithe** [comment]
Demo seems to work fine? What is missing?

**Comment by tylerkelly13** [comment]
I've been unsuccessful in reproducing this issue in Chrome and Firefox.
The example Custom Formats can be found at: **Format** > **Formats** and appear to work correctly on the `tiny.cloud/docs` site and on the codepen page.
Please reopen or create a new issue if this issue should not have been closed and provide more details.
