### ISSUE TITLE
Reference webpack's inline syntax for loaders

### ISSUE THREAD

**Issue by EverybodyKurts** [tinymce/tinymce-docs#1055]
When viewing instructions on how to include tinymce via webpack, https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#webpackfile-loader, it gives an example of how to use inline syntax with the `require.context` function.

However, before I knew the term 'inline syntax', it was  difficult discovering what this concept was, how it was used, or how to configure it. A simple link to webpack's documentation, just like what tinymce's documentation does for `file-loader` and `require.context` does, would have been very helpful: 
https://webpack.js.org/concepts/loaders/#inline

**Comment by tylerkelly13** [comment]
Hi @EverybodyKurts,

We've just released a full re-write of this content and removed inline loaders. The new content shows example webpack configurations instead of inlining all the content into one file.

Tyler
