### ISSUE TITLE
URL Dialog "Button Types" incorrectly lists "close"

### ISSUE THREAD

**Issue by martyf** [tinymce/tinymce-docs#1057]
The [documentation](https://www.tiny.cloud/docs/ui-components/urldialog/#buttontypes) states that "close" is a valid button type.

However this results in an error, and the error says to use either "cancel" or "custom".

Changing to "cancel" works as I would expect "close" to work - the documentation doesn't really specify when or why you would want or need to use "cancel" vs "close"

**Comment by blackcathikari** [comment]
Thanks for this Marty! Since I'm currently updating the dialog docs, I'll add this to my PR
