### ISSUE TITLE
Problem with page quick-start.md

### ISSUE THREAD

**Issue by the-wazz** [tinymce/tinymce-docs#1085]
there is only one thing users really need to know and it's not addressed: is the formatting saved? please address this in all docs. as it is, it appears that formatting is not saved. if it isn't, users only need to save the contents of a label or div or any other html element.

> *affected page: https://www.tiny.cloud/docs/quick-start/*

**Comment by tylerkelly13** [comment]
The TinyMCE 5.1 documentation has been released, along with an updated quick start guide.
The addition requested by this issue can be found here: https://www.tiny.cloud/docs/quick-start/#step4savethecontentwithaformpost
