### ISSUE TITLE
Top Toolbar for Documentation Section of the Site Includes a Link to Forums

### ISSUE THREAD

**Issue by damienfitz** [tinymce/tinymce-docs#111]
The toolbar for the documentation section of the TinyMCE site includes a link to "Forums".  Not only does this link not appear on the main site, but the Forums implementation appears to have broken styling.

I suspect this link needs to be removed.

**Comment by kilianc** [comment]
@damienfitz I literally fixed this 10m ago, now the docs pulls the menu and the footer from the main website so they are always in sync, I will wait for deploy and then let you know for a double check!

Thanks for reporting :beers:

**Comment by kilianc** [comment]
@damienfitz it's live now
