### ISSUE TITLE
why are you referencing window variable on an Angular article?

### ISSUE THREAD

**Issue by marcohern** [tinymce/tinymce-docs#1122]
Your documentation on how to install tinymce on angular is frustratingly incomplete and misleading.  what do you mean window.tinyMCE??? that does not work in angular! why is the part on importing the tinymce variable not in this article? why would you make us use window variable when it clearly does not work? why can't you just put the damn code as an example?!?! it's almost as if you are trolling us devs, making  us feel like idiots, or just want to frustrate us so we can give you our money!

> *affected page: https://www.tiny.cloud/docs/integrations/angular2/*

**Comment by tylerkelly13** [comment]
Hi @marcohern.
The Angular 4+ integration for TinyMCE has recently been updated and should have resolved your issue. 
Please reopen or create a new issue if this issue should not have been closed.
