### ISSUE TITLE
HTML error on documentation

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce-docs#1130]
See https://www.tiny.cloud/docs/configure/content-formatting/#style_formats

every example have html addtribute `id="example"`.
So its impossible to link to a specific example. Attribute "id" must be unique in html source.

**Comment by tylerkelly13** [comment]
This issue will be resolved when the docs are updated for TinyMCE 5.1.

**Comment by tylerkelly13** [comment]
The TinyMCE 5.1 documentation has just been released and this issue has been resolved. Thanks!
