### ISSUE TITLE
Problem with page mobile.md

### ISSUE THREAD

**Issue by huashaoZhao** [tinymce/tinymce-docs#1134]
> *affected page: https://www.tiny.cloud/docs/mobile/*

How to disable TinyMCE mobile detection？

**Comment by tylerkelly13** [comment]
Hi @huashaoZhao,
In the current release of TinyMCE (5.0.12), this option is unavailable.
The option will be added in the TinyMCE 5.0.13 release and is currently present on the nightly build of TinyMCE for **testing purposes** and may be subject to change in future releases.

__This setting should be considered as a Technical Preview at this time.__

To use the standard editor in Mobile view, change the mobile theme to `'silver'`.
For example:
```
tinymce.init({
  selector: 'textarea',
  mobile: {
    theme: 'silver',
  }
});
```
