### ISSUE TITLE
Misleading documentation in Quickstart

### ISSUE THREAD

**Issue by JordanFarrow** [tinymce/tinymce-docs#1135]
```
<h1>TinyMCE Quick Start Guide</h1>
  <form method="post">
    <textarea id="mytextarea" **name="mytextarea"**>Hello, World!</textarea>
  </form>
```
without a name attribute, when the form is submitted, this value will be omitted

**Comment by tylerkelly13** [comment]
Fix has been applied and is now live on the TinyMCE Documentation site.
The updated content can be viewed here: https://www.tiny.cloud/docs/quick-start/#step2initializetinymceaspartofawebform
@JordanFarrow Thanks for letting us know about the issue.
