### ISSUE TITLE
Add documentation to reduce the size of toolbar icons.

### ISSUE THREAD

**Issue by saigoutham7** [tinymce/tinymce-docs#1193]
Hi,
IThe default size of the tinyMCE 5 toolbar icons is 20px, which looks pretty large for my use case in my application. Can you add documentation on how to reduce the size of toolbar please? 

Thanks,
Sai

**Comment by tylerkelly13** [comment]
Hi @saigoutham7
You'll need to create a skin to reduce the size of toolbar icons. Here is our page on creating skins: https://www.tiny.cloud/docs/advanced/creating-a-skin/.
Additional information related to resizing icons can be found here: https://github.com/tinymce/tinymce/issues/4777
Hope this helps.

**Comment by saigoutham7** [comment]
Thanks for your comment @tylerkelly13 !
