### ISSUE TITLE
Problem with page advanced/creating-a-skin.md

### ISSUE THREAD

**Issue by mehronkugler** [tinymce/tinymce-docs#1194]
If I use the "skin" option on init, where does TinyMCE look? In a subfolder named `skins/<my skin name>/`? What file is expected to be in that folder? content.css, skin.css, or ui.css? Or is the folder structure going to have more depth?

I am preprocessing LESS files on my own, not using `yarn oxide-start`

> *affected page: https://www.tiny.cloud/docs/advanced/creating-a-skin/*

**Comment by tylerkelly13** [comment]
Hi @mehronkugler,

TinyMCE skins have the structure:
```
skins/
  content/
    <name>/
     content.min.css
     content.inline.min.css
     ...
  ui/
    <name>/
       content.min.css
       content.inline.min.css
       skin.min.css
       ...
```
where `<name>` is the name of the skin.
Alternatively, you can host the skin files elsewhere and load them in the editor using the [`skin_url`](https://www.tiny.cloud/docs/configure/editor-appearance/#skin_url) property.
The `skin/ui/<name>` directory should contain 3 css files `content.min.css`, `content.inline.min.css`, and `skin.min.css`.

**Comment by mehronkugler** [comment]
Thank you very much! I did some testing and I'm able to load the files as expected.

**Comment by tylerkelly13** [comment]
> Thank you very much! I did some testing and I'm able to load the files as expected.

Awesome! No problem.
