### ISSUE TITLE
Add codepens to examples section

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#120]
Need to migrate content across.

There is a tinymce user setup on Codepen now. Ping me if you need access.

We might want @lucaorio to think about the content that we have inside the editor instances.

**Comment by kilianc** [comment]
Will do later on before EOD

**Comment by androb** [comment]
Awesome :beers: !

**Comment by r12s** [comment]
@lucaorio if you cool do the codepen side i'll do the github/docs side
