### ISSUE TITLE
Problem with page plugins/emoticons.md

### ISSUE THREAD

**Issue by dongwuqiang** [tinymce/tinymce-docs#1213]
> *affected page: https://www.tiny.cloud/docs/plugins/emoticons/* 
what the char field  type of emoticons Obj

**Comment by dongwuqiang** [comment]
can I  put in  a http url

**Comment by tylerkelly13** [comment]
A Single Unicode character is the only valid input for `char:`.
For example: You could copy and paste emoticons from the _Char_ column on this page.

**Comment by dongwuqiang** [comment]
> A Single Unicode character is the only valid input for `char:`.
> For example: You could copy and paste emoticons from the _Char_ column on this page https://www.w3schools.com/charsets/ref_emoji.asp.

ok, thank U, but what i should to do if i want to loading emoticons a list form internet

**Comment by dongwuqiang** [comment]
> A Single Unicode character is the only valid input for `char:`.
> For example: You could copy and paste emoticons from the _Char_ column on this page https://www.w3schools.com/charsets/ref_emoji.asp.

ok, thank U, but what i should to do if i want to loading a list of emoticons form internet

**Comment by dongwuqiang** [comment]
ok, thank U, but what i should to do if i want to loading a list of emoticons form internet

> A Single Unicode character is the only valid input for `char:`.
> For example: You could copy and paste emoticons from the _Char_ column on this page https://www.w3schools.com/charsets/ref_emoji.asp.

ok, thank U, but what i should to do if i want to loading a list of emoticons from internet

**Comment by EkimChau** [comment]
Hi,

We don't have a supported way to use url emoticons at the moment.

May i ask if your users are having problems seeing [][] square characters when using the unicode characters?  If so we are planning to provide a work around for older OS which do not have modern unicode support.

Ekim

**Comment by tylerkelly13** [comment]
This issue appears to be resolved.
Please reopen or create a new issue if this issue should not have been closed.
