### ISSUE TITLE
Add description and keywords to meta tags in head

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#122]
I am guessing we can just pull these through from the article?

**Comment by androb** [comment]
@hassaab - do you have any views of what we should do here?

**Comment by kilianc** [comment]
I can take care of the tech, we already have `keywords` but we could have `meta_*` in the front matter of every page and meaningful default values where they are not defined.

Also meta og are important for facebook and co.

**Comment by hassaab** [comment]
Keywords - 
wysiwyg, html editor,wysiwyg html editor, html editor free, wysiwyg editor, html text editor, jquery editor, best wysiwyg html editor, visual html editor, jquery wysiwyg, html5 wysiwyg, easy html editor, jquery text editor, jquery rich text editor, drag and drop html editor, rich text editor html5, jquery html editor, best wysiwyg, text to html editor, best free wysiwyg html editor, html5 text editor, html5 wysiwyg editor, free html text editor, javascript wysiwyg editor, javascript html editor, simple wysiwyg html editor, wysiwyg text editor, html editor, tinymce enterprise, tinymce pricing, tinymce documentation, tinymce docs, advanced wysiwyg editor

Title -

The Most Advanced WYSIWYG Editor

**Comment by androb** [comment]
What is the value of this in each and every page? Should the keywords be more targeted to each page? The title surely should be specific to each page correct?

**Comment by hassaab** [comment]
No, my recommendation is to add these to our home page. Internal pages can have more specific keywords and I can start building a list of those.

**Comment by androb** [comment]
Okay, my bad. I should have been more precise in the issue description. This project is for "docs" related issues - website related issues should be raised in the website project.

**Comment by hassaab** [comment]
@kilianc During our stand-up today @androb  advised that we focus on capturing the description for each page and have it match the description on that page itself. (Example below)
![description_docs_example](https://cloud.githubusercontent.com/assets/13426010/11511033/8bfdb33c-981b-11e5-9503-69cca57f753a.png)

**Comment by kilianc** [comment]
got it, will be done today
