### ISSUE TITLE
@merwok We have just published a listing of all possible `icon` values:

### ISSUE THREAD

**Issue by Andy-QT** [tinymce/tinymce-docs#1281]
@merwok We have just published a listing of all possible `icon` values:
https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/
And added a page on adding custom icons:
https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/

_Originally posted by @tylerkelly13 in https://github.com/tinymce/tinymce-docs/issues/1019#issuecomment-541999219_

**Comment by Andy-QT** [comment]
The link to 'Creating an icon pack' is not correct on this site:
[https://www.tiny.cloud/docs/advanced/creating-a-skin/](https://www.tiny.cloud/docs/advanced/creating-a-skin/) 

![link](https://user-images.githubusercontent.com/2870154/68470441-5f557f80-021c-11ea-9cf1-08be2b22d605.jpg)

The current link is: https://www.tiny.cloud/docs/advanced/creating-an-icon-pack.md
Should be: https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/

**Comment by tylerkelly13** [comment]
Hi @Andy-QT,
Thanks for raising this issue.
I've fixed the link and the docs will be updated later today.
