### ISSUE TITLE
nav disappears abruptly into footer

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#131]
@kilianc (this is a priority 2 or 3).

When the nav list is long (e.g. the plugins pages) and when the end of a page is reached so that the footer shows, it looks like the footer is "eating" the nav.

To replicate this go to the link below, scroll the content so that the footer appears (and then scroll the page up and down to see an exaggerated example).

http://beta.tinymce.com/docs/plugins/compat3x/

One of our dev guys suggested, "applying some padding/margin at the bottom with a fade on the sidebar will make a nice difference". Several other peeps in this office have commented about this also. 

![tinymce_beta-nav_footer](https://cloud.githubusercontent.com/assets/2252896/11192770/c2af6d5a-8c57-11e5-9e34-f2687e6013aa.png)

**Comment by kilianc** [comment]
@r12s I can see from your screenshot that there is a scrollbar on the left nav that is ~halfway. Left nav and sidebar are disconnected and have separate scrolling.

**Comment by kilianc** [comment]
fixed!
