### ISSUE TITLE
Problem with page ui-components/contextform.md

### ISSUE THREAD

**Issue by Eddcapone** [tinymce/tinymce-docs#1317]
Please add screenshots so we can understand what the article is about.

> *affected page: https://www.tiny.cloud/docs/ui-components/contextform/*

**Comment by tylerkelly13** [comment]
Thanks @Eddcapone. 

In the meantime, have a look at the codepen at the bottom of the page. It may help clear things up.
![image](https://user-images.githubusercontent.com/14833627/70398544-53055200-1a68-11ea-8cf8-c046d6c12fc9.png)
Is there any part of the page that is particular hard to understand? More info will see the page fixed sooner.

**Comment by tylerkelly13** [comment]
Hi @Eddcapone, I'm closing this ticket due to a lack of information. Please reopen with more information.
