### ISSUE TITLE
Problem with page try-tinymce/basic-example.md

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#132]
### [Basic Example](try-tinymce/basic-example.md) issue:

@r12s - this page still needs some copy (vs. Lorem Ipsum).

**Comment by kilianc** [comment]
p.s. that page was a proposal for the example structure, if it's not possible ATM to write copy and keep all examples consistent we should just drop the copy in the page completely

**Comment by r12s** [comment]
@androb I have removed the lorem ipsum for now *but* will push new copy on all examples as @kilianc idea of providing line-level commentary will greatly improve this section. I am also updating content in Codepen.
