### ISSUE TITLE
Problem with page ui-components/customsidebar.md

### ISSUE THREAD

**Issue by Kristiyan96** [tinymce/tinymce-docs#1321]
I have to open the sidebar programmatically. Tried with `tinymce.activeEditor.execCommand('togglesidebar', false, 'sidebar_name');`
but this would only close the sidebar even though it is expected to toggle between open/close state. Any idea how to achieve this?

> *affected page: https://www.tiny.cloud/docs/ui-components/customsidebar/*

**Comment by tylerkelly13** [comment]
Hi @Kristiyan96,
Please check that you are passing the command the correct name. If the command doesn't receive a valid sidebar name it will just close the current sidebar.

**Comment by Kristiyan96** [comment]
@tylerkelly13 Thanks for the prompt help! I register the plugin as advised in the documentation:

tinymce.PluginManager.add('chemInfo', function (editor, url) {
  editor.ui.registry.addSidebar('chemInfo', {
    tooltip: 'My sidebar',
    icon: 'comment',
    onSetup: function(api) {    },
    onShow: function (api) {   },
    onHide: function (api) {    }
  });
});
Which displays the toggle button in the toolbar and it works fine. However, both
tinymce.activeEditor.execCommand('togglesidebar', false, 'chemInfo');
and
tinymce.activeEditor.execCommand('togglesidebar', true, 'chemInfo');

fails to open the sidebar. Any idea where I mess this up :? Thanks again!

**Comment by lnewson** [comment]
@Kristiyan96 it appears as though there's a bug in the toggle sidebar command, as it requires the sidebar name to be lowercase since that's how TinyMCE registers it internally. So if you change `chemInfo` to `cheminfo` then it'll work. Here's a fiddle to demo: http://fiddle.tinymce.com/yXgaab

**Comment by lnewson** [comment]
I'm going to close this question, since it was also asked in the tinymce repo and the question has been answered.
