### ISSUE TITLE
Let us know link does nothing

### ISSUE THREAD

**Issue by ahait** [tinymce/tinymce-docs#1335]
In the end of the page: https://www.tiny.cloud/docs/ui-components/dialogcomponents/
It says:
Can't find what you're looking for? Let us know.

Let us know is a link that does nothing else than just takes you to the top of the page ???

**Comment by tylerkelly13** [comment]
Hi @ahait, 
We are aware of this issue, I think the site designer intended for the link to focus on the documentation search. This may be fixed or removed early next year (depending on when the site is scheduled for a redesign).

**Comment by tylerkelly13** [comment]
Change of plan. I've created a PR to fix this issue.

**Comment by tylerkelly13** [comment]
Fix is now live. Thanks!
