### ISSUE TITLE
Change CDN URL

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#134]
We are going to update the examples to be:
//cloud.tinymce.com/4/tinymce.min.js

This does not work yet so this issue is blocked for now.

**Comment by r12s** [comment]
Ok. Will make a note to update all snippets that reference the CDN (mainly in the Get Started section).

**Comment by r12s** [comment]
this has been resolved. @kilian implemented a global cdnurl in config.yml to help simplify updates resutling from future changes to cdn versioning.
