### ISSUE TITLE
I can't find what I'm looking for: api/tinymce/tinymce.shortcuts.html

### ISSUE THREAD

**Issue by kofaysi** [tinymce/tinymce-docs#1340]
Dear devs,

The examples section of the https://www.tiny.cloud/docs/api/tinymce/tinymce.shortcuts/ article is useless: real world examples are missing. It would be much helpful, if the examples showed:
- entering an HTML code on the place of the cursor
- opening a selection window (pictures)
- formatting a pre-selected part of the text by a style name XY or adding a class to the selection.
- ...

I'm about to construct a keyboard shortcut for entering a non-breakable space. I came up with this:
`editor.shortcuts.add('shift+ctrl+space', "Enter non-breakable space", code('&nbsp;') {});`
but it does not do anything yet.

Thank you!

**Comment by kofaysi** [comment]
I searched the JCE plugin folder for examples and I found out that there is a nonbreakable plugin for entering a non-breakable space. Huray!
`ed.addShortcut("ctrl+shift+s","nonbreaking.desc","mceNonBreaking")`

Using the `Custom Configuration Variables` option in Global settings:
I have found out that the `space` key is probably not defined, when redefining the shortcut to
`ed.addShortcut("ctrl+shift+space","nonbreaking.desc","mceNonBreaking")` or
`ed.addShortcut("ctrl+shift+spacebar","nonbreaking.desc","mceNonBreaking")`
I would wish a list of characters (names), which can be used for allocating a shortcut, is in the help.

Then I have also found out that my construction is wrong fundamentally. The following is not allowing to enter a nbsp:
`ed.addShortcut("ctrl+shift+l","nonbreaking.desc","mceNonBreaking")`
`addShortcut("ctrl+shift+l","nonbreaking.desc","mceNonBreaking")`
I was awaiting that one of the commands will work and ctrl+shift+l inserts a nbsp into the text.

Other found examples executes commands, they do not enter code.

**Comment by kofaysi** [comment]
Well, I the above examples I was working with and outdated JCE version:
Joomla! 3.9.13
JCE 2.6.36

After updating the JCE to v2.8.1, the `Custom Configuration Variables` has a key-value structure and it does not allow to define `addShortcut()`. But the floating help box does not say anything new and redirects to the `addShortcut()` definition.

**Comment by tylerkelly13** [comment]
> The examples section of the https://www.tiny.cloud/docs/api/tinymce/tinymce.shortcuts/ article is useless: real world examples are missing. It would be much helpful, if the examples showed:
>     * entering an HTML code on the place of the cursor
>     * opening a selection window (pictures)
>     * formatting a pre-selected part of the text by a style name XY or adding a class to the selection.
>     * ...

I've created a ticket to get the Keyboard Shortcut docs fixed up. In the meantime, this blog post will help: https://www.tiny.cloud/blog/creating-keyboard-shortcuts-tinymce/

**Comment by tylerkelly13** [comment]
For issues related to JCE, please contact the the JCE developer at: https://github.com/widgetfactory/jce. We do not maintain JCE or the JCE docs.

**Comment by kofaysi** [comment]
I'm managing another site with

- Wordpress 5.3.1
- TinyMCE Advanced 5.3.0
- Advanced TinyMCE Configuration 1.5

and there is the same situation:

- I could not find a keyboard shortcut for entering a non-breakable space and I wish to create one
- I wish to create other keyboard shortcuts to enter text snippets
- The administrator can enter an option_name-value pair with the Advanced TinyMCE Configuration plugin

So, I'm still interested in a solution: **key-value pair defining a keyboard shortcut for TinyMCE**, please. Or how else could I define it for TinyMCE, please?

**Comment by lnewson** [comment]
@kofaysi all of those aren't maintained by us, so we are limited in what help we can provide. I'd suggest logging any issues, or questions against those plugins/products directly as they'll likely be to assist:
- TinyMCE Advanced: https://wordpress.org/support/plugin/tinymce-advanced/
- Advanced TinyMCE Configuration: https://wordpress.org/support/plugin/advanced-tinymce-configuration/

As for TinyMCE itself, as per the docs and blog @tylerkelly13 linked above, the `addShortcut` API requires a function that will handle what to do when the shortcut key combination has been pressed or the name of a [command](https://www.tiny.cloud/docs/advanced/editor-command-identifiers/) to execute.

Here's a basic example to show how to insert a non-breaking space:
```
editor.addShortcut('ctrl+shift+l', 'Inserts a nonbreaking space', 'mceNonBreaking');
```
and a corresponding fiddle to show it working: http://fiddle.tinymce.com/RXgaab

**Comment by kofaysi** [comment]
Thank you, dear @tylerkelly13 and @lnewson. I understand and will try to trigger a solution at the mentioned places. M

**Comment by tylerkelly13** [comment]
Not problem @kofaysi. Good luck!
