### ISSUE TITLE
Problem with page demo/basic-example.md

### ISSUE THREAD

**Issue by dongolojeno85** [tinymce/tinymce-docs#1341]
I just changed the color on the page and all for some of the text color but this was not reflected in HTML source code.

> *affected page: https://www.tiny.cloud/docs/demo/basic-example/*

![image](https://user-images.githubusercontent.com/54619520/71015351-1dadd380-20fc-11ea-8f99-81818bfba463.png)

This is the HTML code generated: (Missing the style with the color red.)
  <h2 style="text-align: center;">Welcome to the TinyMCE editor demo!</h2>

**Comment by tylerkelly13** [comment]
Hi @dongolojeno85,
The HTML tab of the codepens is static and shows the initial content, not the current content.
To view the current HTML content, you need to use the `code` plugin, which is not enabled for that demo.
If you visit the Full Featured demos, you can view the HTML source by:
- Selecting the *View* Menu,
- Selecting the *Source Code* Option.

The Full-featured demo can be found here: https://www.tiny.cloud/docs/demo/full-featured/
