### ISSUE TITLE
How to import all the plugins at one time in one single line when using with module loaders

### ISSUE THREAD

**Issue by vfi2018** [tinymce/tinymce-docs#1348]
**How to import all the plugins at one time in one single line when using with module loaders?
It's very untidy to import them one by one when I need to use many of the plugins as below:**
import 'tinymce/plugins/image'
import 'tinymce/plugins/media'
import 'tinymce/plugins/plugina'
import 'tinymce/plugins/pluginb'
import 'tinymce/plugins/pluginc'
import 'tinymce/plugins/plugind'
import 'tinymce/plugins/plugine'
...

**Comment by lnewson** [comment]
Unfortunately, it's limited to what the JavaScript spec and module loader implementations allow and currently there isn't support for wildcard imports for the paths, so yes you'll need to specify an import each plugin you want to use.

If you find it cleaner, you could create a separate file with all the required imports (eg `tinymce-imports.js`) and then just import that where you're using TinyMCE instead.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
