### ISSUE TITLE
I can't find what I'm looking for: quick-start.md

### ISSUE THREAD

**Issue by crankyozfranky** [tinymce/tinymce-docs#1350]
Hello. This is not an issue, but i was directed to this page from your doco site. I'm evaluating tinymce as a solution for client-side content creation and editing for HTML sites and STATIC sites created with Jekyll. It's easy to get started, but I can't find the information I need regarding user/client set up and how that and/or user roles work with the product. Can you please point me in the right direction? Thank you very much...Francis Ginter, Sydney Australia

**Comment by tylerkelly13** [comment]
Hi Francis.
TinyMCE does not have any concept of users. Handling users and authentication is something you'll need to handle server-side using PHP, Node.js or similar. It is difficult for us to document how to handle user as it will depend on your setup, not on TinyMCE.

**Comment by crankyozfranky** [comment]
Thank you. Understood.

**Comment by crankyozfranky** [comment]
Tyler where can I find the documentation for how to handle server-side or using PHP, to control user access, etc.?

 

Thanks.

 

Francis

**Comment by tylerkelly13** [comment]
Hi Francis
That depends on the authentication method(s) you intend on using. For example, if you are using LDAP, you would refer to this section of the php docs: https://www.php.net/manual/en/book.ldap.php
TinyMCE is a library, not a content management application. So authentication would be controlled by the system you integrate TinyMCE into, so we can't provide docs on how to do that, as it'll depend on what you integrate TinyMCE into.

**Comment by crankyozfranky** [comment]
I really appreciate your help, thank you.

 

The three forms I’m using include:

 

1.	HTML+CSS+JS
2.	Jekyll
3.	Kirby CMS

 

Of these #1 is the one I’m most interested in setting up with front-end user content editing.

 

Thanks.

 

Francis

**Comment by tylerkelly13** [comment]
Hi Francis
This question is not related to TinyMCE. For help setting up TinyMCE in KirbyCMS, try: https://forum.getkirby.com/.
Alternatively, try asking on: 
- https://stackoverflow.com/
- https://community.tiny.cloud/
