### ISSUE TITLE
I can't find what I'm looking for: integrations/react.md

### ISSUE THREAD

**Issue by Moshe10** [tinymce/tinymce-docs#1358]
hi, Is it possible to make the toolbar sticky in react-js ?

**Comment by tylerkelly13** [comment]
Hi @Moshe10,
If you add the [`toolbar_sticky`](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_sticky) setting to the [`init`](https://www.tiny.cloud/docs/integrations/react/#init) option for your react application it should make the toolbar sticky.

**Comment by tylerkelly13** [comment]
This issue appears to have been resolved. If this issue has not been resolved, reopen or create a new Issue.
