### ISSUE TITLE
I can't find what I'm looking for: wordcount plugin

### ISSUE THREAD

**Issue by zakircinjarevic** [tinymce/tinymce-docs#1359]
I cant seem to get wordcount.body , since wordcount has only getCount() which returns number of words, and body.getCharacterCount() is not defined.

**Comment by lnewson** [comment]
@zakircinjarevic which version of TinyMCE are you using? As the `getCharacterCount` API was only added in 5.0.6?

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
