### ISSUE TITLE
Problem with page enterprise/check-spelling/index.md

### ISSUE THREAD

**Issue by JackMasonEphox** [tinymce/tinymce-docs#136]
### [Check Spelling As-You-Type](enterprise/check-spelling/index.md) issue:

Link to TinyMCE Enterprise (i.e. http://www.tinymce.com/pricing/?_ga=1.63408170.440443705.1447811000) displays a message around "Could not find the specified document".

Perhaps the link should point to http://www.tinymce.com/enterprise/enterprise.php instead.

**Comment by kilianc** [comment]
Thanks for reporting @JackMasonEphox ! That page should link to `/pricing/` which is the correct URL.

Regarding the `_ga` noise that's known and we're on it!

**Comment by r12s** [comment]
tested this in chrome, firefox and safari (osx). this appears to have been fixed. closing issue.
