### ISSUE TITLE
Problem with page configure/integration-and-setup.md

### ISSUE THREAD

**Issue by faloupy** [tinymce/tinymce-docs#1360]
Under the heading

content_security_policy

the code reads

content_security_policy: 'default-src 'self''

but should be

content_security_policy: "default-src 'self'"

> *affected page: https://www.tiny.cloud/docs/configure/integration-and-setup/*

**Comment by tylerkelly13** [comment]
Thanks @faloupy, your suggested fix will be live a few minutes after PR #1361 is merged.

**Comment by tylerkelly13** [comment]
The fix is now live on the website: https://www.tiny.cloud/docs/configure/integration-and-setup/#content_security_policy
Thanks for pointing out this error @faloupy .
