### ISSUE TITLE
I can't find what I'm looking for: ui-components/dialogcomponents.md

### ISSUE THREAD

**Issue by adventmedia** [tinymce/tinymce-docs#1364]
specifically, the 'selectbox' widget - which builds an HTML select input - how do I set the default selected item in the list of items?
`{value: '4', text: 'Four', selected=true}` doesn't work

**Comment by lnewson** [comment]
@adventmedia you set the default value, by using the `initialData` property. It's used to set the initial value for all components in the dialog. https://www.tiny.cloud/docs/ui-components/dialog/#simpleinteractivedialog contains an example of how `initialData` is used to set the default value for the checkbox/input components.
