### ISSUE TITLE
I can't find what I'm looking for: configure/editor-appearance.md

### ISSUE THREAD

**Issue by n1ckster** [tinymce/tinymce-docs#1368]
Hi,

Does the editor allow text placeholders to be added? ie Text that appears in the editor window on load but when the user clicks into the editor window it disappears? I am currently using V 5.*

Thanks

Nick

**Comment by tylerkelly13** [comment]
Hi @n1ckster .
TinyMCE 5.1 does not have this feature, however a new placeholder setting will be added in an upcoming release.

**Comment by n1ckster** [comment]
Hi tylerkelly13 ,

Thanks for the speedy reply. Do you have a rough idea on the time scales for this feature release?

Thanks

Nick

**Comment by tylerkelly13** [comment]
We are currently targeting 5.2 for this feature, which _should_ be released in the next month or so (pending QA). For details on the new setting, see the following link:
https://github.com/tinymce/tinymce-docs/blob/feature/TinyMCE_5.2/_includes/configuration/placeholder.md

**Comment by tylerkelly13** [comment]
The `placeholder` setting has now been released with TinyMCE 5.2 It will released for enterprise and cloud users in the coming weeks.
