### ISSUE TITLE
Problem with page enterprise/check-spelling/troubleshoot.md

### ISSUE THREAD

**Issue by JackMasonEphox** [tinymce/tinymce-docs#137]
### [Troubleshoot](/tinymce/tinymce-docs/enterprise/check-spelling/troubleshoot.md) issue:

I figured you might like to know that the images on this page aren't rendering. I can replicate this on both Chrome latest and Firefox latest on OSX 10.9.5.

**Comment by kilianc** [comment]
all images need `{{ site.baseurl }}`

**Comment by r12s** [comment]
fixed in PR 187
