### ISSUE TITLE
Letter 'p' in bottom left corner

### ISSUE THREAD

**Issue by eugenevk** [tinymce/tinymce-docs#1373]
Have integrated TinyMCE in my AngularJS project. The editor shows a 'p' in the bottom left corner!? Clicking it selects the paragraph the cursor is at. How can I either change the 'p' into an icon, or remove it at all?
![TinyMCE - p in bottem left corner](https://user-images.githubusercontent.com/19785727/73162822-f0871480-40ee-11ea-948a-e7bcc3fcc26b.jpg)

**Comment by lnewson** [comment]
@eugenevk that's the element path feature in TinyMCE that shows the path to the current selection. So as an example, if you had some bold text in the editor then it'd show `P > STRONG`. You can disable it using the [`elementpath`](https://www.tiny.cloud/docs/configure/editor-appearance/#elementpath) init setting.

Here's an example for AngularJS, based on the example from the [integration docs](https://www.tiny.cloud/docs/integrations/angularjs/):
```
  $scope.tinymceOptions = {
    plugins: 'link image code',
    toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code',
    elementpath: false
  };
```

**Comment by eugenevk** [comment]
Solved. Thanks @lnewson
