### ISSUE TITLE
When I press enter empty <p> tags are created

### ISSUE THREAD

**Issue by Remy-Limelight** [tinymce/tinymce-docs#1377]
Everything worked fine for a while then i started getting this bug where when i press enter, then the editor creates `<p class="selected"><br data-mce-bogus="1"></p>`

But when i start typing the text still stays in the previous `<p>` tag

so it creates multiple "empty" `<p>` tags and i am stuck in the previous `<p>` tag

**Comment by tylerkelly13** [comment]
Please note that the issues section of the TinyMCE documentation repository is for reporting documentation issues.
If you have found a bug, please report it with steps to reproduce at the [TinyMCE GitHub Repository](https://github.com/tinymce/tinymce/issues).
