### ISSUE TITLE
Footer interferes with side bar

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#138]
* Shrink your browser vertically so it is slightly larger than the topics list.
* Open the Plugins section.
* Scroll to the bottom of the page.

Result: The footer section will cover the side bar, making it difficult to scroll to or click on another topic.

Expected: When the footer is scrolled into view, it should push both the content and topic views upwards to ensure that the user is still able to interact with items in them.

**Comment by kilianc** [comment]
@Ahtaps that would result in the user scrolling all the way to the top every time he wants to change page

**Comment by Ahtaps** [comment]
The problem is that the scrolling on the topic list is weird because of it.  It seems like it actually extends beyond the bottom of the page and to change to a topic that is covered by the footer you have to scroll up (To unhide the topics) before you can scroll down (If the topic is off screen) in  many cases.

**Comment by kilianc** [comment]
@Ahtaps I am not sure I follow, I will investigate more tomorrow. This behavior with docs is pretty common see https://docs.angularjs.org/api

**Comment by Ahtaps** [comment]
I think this is a combination of our footer being large and both Chrome and Firefox putting the bottom of the scrollable area below the bottom of the browser.
