### ISSUE TITLE
iPad - Footer does not extend the full width of the screen

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#139]
When viewing the documentation on an iPad, the footer panel will not extend to the full width of the page, creating a void in the bottom, right hand corner.

**Comment by kilianc** [comment]
@Ahtaps could you be so nice to attach a screenshot?

**Comment by kilianc** [comment]
Also be sure to have cache cleared, we did fix footer problems previously

**Comment by Ahtaps** [comment]
![ipaddocs](https://cloud.githubusercontent.com/assets/15883853/11232540/31e361aa-8e00-11e5-9b65-ef8b9ca0a2f4.png)
I don't think this is a caching issue as today was the first time the iPad accessed the site and it happened the first time.

**Comment by kilianc** [comment]
Oh Thanks for the screenshot. That's due to the fact that we didn't push the responsive version of the documentation just yet.

Thanks @Ahtaps !
