### ISSUE TITLE
I can't find what I'm looking for: api/tinymce.dom/tinymce.dom.controlselection.html

### ISSUE THREAD

**Issue by WarwickGoatee** [tinymce/tinymce-docs#1397]
This page appears to be blank at the moment...

**Comment by tylerkelly13** [comment]
Hi @WarwickGoatee 
The dom.ControlSelection APIs are intended for use by the editor, and this blank page will disappear at a later date. If you would like to see the APIs available for dom.ControlSelection, they can be viewed at https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts

**Comment by tylerkelly13** [comment]
Thanks for the bug report!
This page has been removed as intended with the release of TinyMCE 5.4.
Please reopen or create a new issue if this issue should not have been closed.
