### ISSUE TITLE
Problem with page enterprise/advcode.md

### ISSUE THREAD

**Issue by dlkulp** [tinymce/tinymce-docs#1405]
This doesn't do a good job differentiating the advanced and non-advanced versions.  Would be helpful to have a side-by-side comparison, possibly including images or embedded editors to make it clear what is actually gained by using the advanced code editor.

> *affected page: https://www.tiny.cloud/docs/enterprise/advcode/*

**Comment by tylerkelly13** [comment]
@dlkulp thanks for the suggestion! I'll let you know when we have fixed this up.

**Comment by tylerkelly13** [comment]
Thanks again for the suggestion.
The suggested content has been added and is now live on the documentation site: https://www.tiny.cloud/docs/enterprise/advcode/#thedifferencebetweenthecodeandadvancedcodeeditorplugins
Please reopen or create a new issue if this issue should not have been closed.
