### ISSUE TITLE
Search Results panel takes up the entire screen width.

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#141]
* Perform a search for a topic.

Result: The results panel will extend to the width of the screen.  At large browser widths, this tends to result in a large amount of empty space in the middle of the panel.  

Expected: Since only topic names are listed, I'd have expected the list to be more like a dropdown rather than a full width panel.

**Comment by kilianc** [comment]
This will be taken offline for further consideration cc @r12s
