### ISSUE TITLE
I can't find what I'm looking for: plugins/save.md

### ISSUE THREAD

**Issue by ducat595** [tinymce/tinymce-docs#1423]
Hi, I can't understand how to save the content with 'tinymce.activeEditor.execCommand('mceSave')'.
Please advice to me,when the command is executed, what happens and where it is saved .
Kind Regards

**Comment by tylerkelly13** [comment]
Hi @ducat595 ,
When the `mceSave` command is executed, either:he callback function defined for the [`save_onsavecallback` setting](https://www.tiny.cloud/docs/plugins/save/#save_onsavecallback) will be executed.
