### ISSUE TITLE
I can't find what I'm looking for: demo/classic.md

### ISSUE THREAD

**Issue by theranajayant** [tinymce/tinymce-docs#1424]
The JS section doesn't have same code. Looks like someone placed thatcode by mistake. 
URL: https://www.tiny.cloud/docs/demo/classic/

**Comment by tylerkelly13** [comment]
Thanks @theranajayant .
The first function in that codepen was incorrectly added, and will now be removed.
In case there was some confusion about the demo, the JS tab shows the JavaScript used to create the demo. In this codepen, the TinyMCE configuration is defined by the variable `demoBaseConfig` and the editor is initialized at the end of the JavaScript `tinymce.init(demoBaseConfig);`

**Comment by tylerkelly13** [comment]
Thanks again for reporting this bug. The fix will go live next time we push changes to the master branch.
