### ISSUE TITLE
I can't find what I'm looking for: plugins/nonbreaking.md

### ISSUE THREAD

**Issue by mandrael** [tinymce/tinymce-docs#1427]
no link to the plugin, so I can't use it, though nice documentation how it _could_ work...

**Comment by tylerkelly13** [comment]
@mandrael 
The plugin is bundled with TinyMCE. To include it in the editor, add `nonbreaking` to the plugins list, as shown in the [example](https://www.tiny.cloud/docs/plugins/nonbreaking/#example).

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
