### ISSUE TITLE
I can't find what I'm looking for: plugins/lists.md

### ISSUE THREAD

**Issue by daniel-weltz** [tinymce/tinymce-docs#1429]
Hello,

How can i customize bullet list in Tinymce ?
My customisation is to replace bullet style with my own.

Thanks for you help

**Comment by tylerkelly13** [comment]
Hi @daniel-weltz,
To change the bullet style, provide CSS for the change using the [`content_style`](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) or [`content_css`](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) options.
I've created a quick example using content_style here: http://fiddle.tinymce.com/ydhaab

**Comment by daniel-weltz** [comment]
Hi,
Thanks a lot for your quickly answer.
This will help me.
May I still bother you by asking you how to customize the first level <li> with my own symbol (like '>') ?

Best regard,


[logo BS-Team]<https://www.bs-team.ch/>
[picto linkedin]<https://www.linkedin.com/company/bs-team/>
Daniel WELTZ
Senior Business Consultant, Solutions Architect
m: +41 79 936 44 06<tel:0041763886714>
e: dweltz@bs-team.ch<mailto:dweltz@bs-team.ch>

BS-Team Sàrl
Route de Vaularbel 18 | 1468 Cheyres
Chemin de la Venoge 7 | 1025 St-Sulpice
Rue des Follaterres 27 | 1920 Martigny
t: +41 58 255 00 20<tel:0041582550020>
w: bs-team.ch<https://www.bs-team.ch/>


De : Tyler Kelly <notifications@github.com>
Envoyé : mercredi 11 mars 2020 00:37
À : tinymce/tinymce-docs <tinymce-docs@noreply.github.com>
Cc : Daniel Weltz - BS-Team <dweltz@bs-team.ch>; Mention <mention@noreply.github.com>
Objet : Re: [tinymce/tinymce-docs] I can't find what I'm looking for: plugins/lists.md (#1429)


Hi @daniel-weltz<https://github.com/daniel-weltz>,
To change the bullet style, provide CSS for the change using the content_style<https://www.tiny.cloud/docs/configure/content-appearance/#content_style> or content_css<https://www.tiny.cloud/docs/configure/content-appearance/#content_css> options.
I've created a quick example using content_style here: http://fiddle.tinymce.com/ydhaab

**Comment by tylerkelly13** [comment]
Generally, this page should help: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style
Specifically, this section: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style#Accessibility_concerns
Replace `\200B` with the desired character code.

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
