### ISSUE TITLE
I can't find what I'm looking for: integrations/wordpress.md

### ISSUE THREAD

**Issue by amitjagtap21** [tinymce/tinymce-docs#1438]
not able to find preview option in editor for wordpress

**Comment by tylerkelly13** [comment]
Hi @amitjagtap21 

The WordPress integration of TinyMCE is not maintained by the Tiny team. Please talk to the maintainer of the relevant WordPress plugin.
Classic editor plugin: https://en-au.wordpress.org/plugins/classic-editor/
TinyMCE Advanced plugin: https://en-au.wordpress.org/plugins/tinymce-advanced/
