### ISSUE TITLE
I can't find what I'm looking for: plugins/index.md

### ISSUE THREAD

**Issue by Cassirer** [tinymce/tinymce-docs#1440]
Dear all,
I'm looking for a plugin to change the quotes  in Jommla's 3.9.16 TinyMCE permanently to the german version of

&bdquo; _Text_ &ldquo;

Is there any possibility to stop doing it by copy and paste from another editor?

Thanks, best cassirer

**Comment by tylerkelly13** [comment]
Hi @Cassirer ,

Short answer - not in [TinyMCE 4](https://www.joomla.org/announcements/release-news/5751-joomla-3-9-1-release.html), unless there is a Joomla plugin that can help you.

Options that may be suitable in TinyMCE 5:
- override the input events and when someone presses a quote key,  have it insert the related german equivalent instead,
- use post processing on the content to convert all of them,
- create an autocompleter: https://www.tiny.cloud/docs/ui-components/autocompleter/

I'm going to close this issue; we don't maintain the Joomla integration and we don't support the version of TinyMCE that Joomla provides at this time. I recommend trying either:
- Joomla support: https://community.joomla.org/
- StackOverFlow using the `tinymce` and `joomla` tags: https://stackoverflow.com/questions/tagged/tinymce+joomla

**Comment by Cassirer** [comment]
thx a lot for your reply!
