### ISSUE TITLE
Version dropdown takes users to "Can't Edit" page link for v3

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#145]
* Select the TinyMCE v3 item in the version dropdown.

Result: The user will be taken to a page that has a message stating that they are unable to edit the page.

Expected: The user should be taken to the v3 documentation.

**Comment by r12s** [comment]
@Ahtaps cannot replicate. On various pages when selecting v3 from the dropdown I get redirected to http://archive.tinymce.com/wiki.php/TinyMCE3x:TinyMCE_3.x

Please provide url exhibiting the behavior.

**Comment by kilianc** [comment]
@r12s this is known bug due to `_ga` noise. see #136 and internal website issue
