### ISSUE TITLE
execCommand(command, ui, value, args) .....What are the args Settings?

### ISSUE THREAD

**Issue by MrLiufei** [tinymce/tinymce-docs#1458]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by tylerkelly13** [comment]
Hi everyone.
Thank you @MrLiufei for raising this ticket.

All of the `execCommand`s are now documented with examples: https://www.tiny.cloud/docs/advanced/editor-command-identifiers/ moving this ticket to closed.
