### ISSUE TITLE
Problem with page plugins/emoticons.md

### ISSUE THREAD

**Issue by kanadaj** [tinymce/tinymce-docs#1459]
Documentation outdated due to https://github.com/tinymce/tinymce/commit/d1ee80a2a702a4709f4533597dc8f114c1ab1ce3 and https://github.com/tinymce/tinymce/commit/bc09fd05b5efa8cd48992f11b695ce7f11c3cbdf but the change is not indicated in the docs nor in the changelog.

> *affected page: https://www.tiny.cloud/docs/plugins/emoticons/*

**Comment by tylerkelly13** [comment]
Thanks @kanadaj ,

The emoticons plugin documentation has been updated to reflect this change. Thanks for letting us know!

Updated content is now live here: https://www.tiny.cloud/docs/plugins/emoticons/#emoticons_database_url
