### ISSUE TITLE
Long breadcrumb trails go behind the Search text field.

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#146]
- Open the  Upgrade to Enterprise > Check Spelling As-You-Type > Install Spell Checker Pro Server page.

Result: The breadcrumb trail will go behind the Search text field.

Expected: The start of the trail should probably be either hidden behind an ellipsis, or a scrolling feature be made available for long trails.

**Comment by kilianc** [comment]
@androb is it acceptable to have a max characters for each part in the path ?

**Comment by r12s** [comment]
Issue resolved with update to search / implementation of Algolia `docsearch`.
