### ISSUE TITLE
Link to Menu.ContextMenuApi

### ISSUE THREAD

**Issue by tinydylan** [tinymce/tinymce-docs#1461]
I'm trying to register a custom context menu.

In https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addcontextmenu, there's a reference to "Menu.ContextMenuApi". It looks like it should be a link, but it isn't.

I can't find any details on "Menu.ContextMenuApi", so I'm finding it difficult to figure out how to use this.

**Comment by tylerkelly13** [comment]
Hi @tinydylan 
Unfortunately, the confusion has been caused by the choice of CSS on the page. I'll look into that this week.
For info on using "Menu.ContextMenuApi" see: https://www.tiny.cloud/docs/ui-components/contextmenu/#registeringcontextmenusections

**Comment by tylerkelly13** [comment]
Thanks for the bug report!
Most methods on the tinymce.editor.ui.Registry page now have links to the relevant documentation pages, except addIcon which will be updated for TinyMCE 5.5 (see https://github.com/tinymce/tinymce-docs/issues/1583).
Please reopen or create a new issue if this issue should not have been closed.
