### ISSUE TITLE
django integration

### ISSUE THREAD

**Issue by okongwu101** [tinymce/tinymce-docs#1464]
django integration is needed. Thank you.

**Comment by tylerkelly13** [comment]
Hi @okongwu101,

We don't currently maintain an integration for django.

There is a community maintained integration, which is documented here: https://django-tinymce.readthedocs.io/en/latest/

Thanks
Tyler

**Comment by tylerkelly13** [comment]
This question has been answered and there has been no response for more than 7 day, so I'm treating this issue as resolved.
Please reopen or create a new issue if this issue should not have been closed.
