### ISSUE TITLE
tinydrive is only for premium

### ISSUE THREAD

**Issue by LexRiver** [tinymce/tinymce-docs#1511]
**Documentation/Product Version**
_TinyMCE 5 Documentation_

**Links to Page(s) affected**
https://www.tiny.cloud/docs/plugins/drive/
https://www.tiny.cloud/pricing/

**Description of Issue**
On the page https://www.tiny.cloud/docs/plugins/drive/ we have
```Note: This plugin is only available for paid TinyMCE subscriptions.```
But on the page https://www.tiny.cloud/pricing/ we have Tiny Drive in community edition

**Suggested Fix**
remove 
```Note: This plugin is only available for paid TinyMCE subscriptions.```
from page https://www.tiny.cloud/docs/plugins/drive/

**Comment by tylerkelly13** [comment]
Thanks @LexRiver,

I've created a PR (#1512) to update this note. The fix should go out in the next 24hrs.

Cheers
Tyler

**Comment by tylerkelly13** [comment]
The updated note is now live on the documentation site: https://www.tiny.cloud/docs/plugins/drive/

Thanks for pointing out the issue
Tyler
