### ISSUE TITLE
I can't find what I'm looking for: enterprise/index.md I want tinymce to all my all domains without mentioning them in approved domains 

### ISSUE THREAD

**Issue by shubh151994** [tinymce/tinymce-docs#1515]

**Comment by tylerkelly13** [comment]
Hi @shubh151994 

Could you provide more information about what you are trying to do.

If you are an enterprise customer, please close this ticket and open a zendesk ticket here: https://support.tiny.cloud/

Thanks
Tyler

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
