### ISSUE TITLE
Problem with page general-configuration-guide/multiple-editors.md

### ISSUE THREAD

**Issue by nousename** [tinymce/tinymce-docs#1519]
Every tiny input is supposed to have it's own form element?
seems unlikely and unusable 

> *affected page: https://www.tiny.cloud/docs/general-configuration-guide/multiple-editors/*

**Comment by tylerkelly13** [comment]
Hi @nousename ,

Had a chat with the devs and this page needs fixing. You don't need a separate form for each editor.

Thanks
Tyler

**Comment by tylerkelly13** [comment]
Updated examples are now live.
https://www.tiny.cloud/docs/general-configuration-guide/multiple-editors/
Thank you for your feedback.
