### ISSUE TITLE
Mac keyboard-shortcuts are not written in typical Mac culture

### ISSUE THREAD

**Issue by brichwin** [tinymce/tinymce-docs#1539]
**Documentation/Product Version**
_TinyMCE 4 Documentation_ OR _TinyMCE 5 Documentation_

**Links to Page(s) affected**
https://www.tiny.cloud/docs/advanced/keyboard-shortcuts/

**Description of Issue**
Most Mac keyboards do not have a key label as "Alt", however many of the Mac keyboard-shortcuts refer to the "Alt" key.

**Suggested Fix**
Probably what is meant is the "Option" key. Consider replacing references to "Alt" with "Option".

**Comment by tylerkelly13** [comment]
Hi @brichwin ,

Thanks for pointing out this issue. The updated list of shortcuts is now live. We've also added a missing shortcut for the help dialog (from the `help` plugin) and fixed up the descriptions and shortcuts on the [Accessibility keyboard shortcuts table](https://www.tiny.cloud/docs/advanced/keyboard-shortcuts/#accessibilitykeyboardshortcuts).
