### ISSUE TITLE
Incorrect How to work with the editor instructions

### ISSUE THREAD

**Issue by brichwin** [tinymce/tinymce-docs#1540]
**Documentation/Product Version**
_TinyMCE 4 Documentation_ OR _TinyMCE 5 Documentation_

**Links to Page(s) affected**
https://www.tiny.cloud/docs/advanced/accessibility/

**Description of Issue**
The How to work with the editor instructions include this statement, "When you reach the end of one toolbar the Right Arrow and Left Arrow wrap to the next and previous toolbars respectively." However, when I use the Right Arrow or Left Arrow keys at the ends, they wrap around to items within the toolbar I'm in and do not move to the next or previous toolbar.

**Suggested Fix**

- If this behavior is specific to a particular version of TinyMCE, then the link provided in the keyboard-shortcuts modal should go to a version specific keyboard-shortcuts and accessibility page.
- Otherwise, consider rewording it as: "When you reach the end of one toolbar the Right Arrow and Left Arrow wrap around to items within that toolbar. Use tab and shift+tab to move to the next and previous toolbars respectively."

**Comment by tylerkelly13** [comment]
The keyboard navigation instructions have been rewritten to reflect the editor behavior and address this issue. The updated content can be found here: https://www.tiny.cloud/docs/advanced/accessibility/
