### ISSUE TITLE
Problem with page try-tinymce/image-tools.md

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#156]
### [Image Tools Example](try-tinymce/image-tools.md) issue:
There was no inline toolbar displayed when I clicked on the image.

**Comment by Afraithe** [comment]
This is probably due to where the image is loaded from, if its a remote domain, it will not be able to fiddle with the image. Solution is to load the image in tinymce locally.

**Comment by kilianc** [comment]
@Afraithe is this related to CORS headers not being set?

**Comment by r12s** [comment]
fixed missing config option to set cors. set on both tinymce.com and codepen.io so that inline toolbar appears in both fiddles.
