### ISSUE TITLE
I can't find what I'm looking for: quick-start.md

### ISSUE THREAD

**Issue by steviedeeee** [tinymce/tinymce-docs#1566]
Hello I would like to use TinyMCE as an alternative to Sitecake for my flat-file website, where I can install it on my server or link to Tiny Cloud, then be able to log in when I want to edit content on the page. I need this so that I can work with code editors who will only change text and not play with the form of the website. Can TinyMCE do this? I have searched through the documentation and it seems that the editor is only activated automatically once installed.

**Comment by tylerkelly13** [comment]
Hi Steve,

I'm not sure what the question is here. But, note that Sitecake is a Content Management System (CMS) that likely contains a WYSIWYG editor, whereas TinyMCE _is_ a WYSIWYG editor. Whether it affects the 'form' of the site depends on how it is integrated into your CMS or site.
The Inline editor 'mode' and Distraction-free 'mode' demos is good examples of isolating the editor to specific sections of content: https://www.tiny.cloud/docs/demo/inline/ and https://www.tiny.cloud/docs/demo/editor-dfree/.
Note that TinyMCE is for editing and creating content and is not page-builder.

Tyler

**Comment by steviedeeee** [comment]
Hi Tyler, thanks for your reply. I'm not looking for a CMS per se, I really just want to be able to edit the text content on a flat-file website using TinyMCE without all of the other features except for the ability to login to the site to do the editing and to choose which text areas are editable. I found one open source project that is working on this, JOCMS, but my question is, "does TinyMCE also have this functionality?"

**Comment by tylerkelly13** [comment]
TinyMCE is an embeddable rich text editor - think word's text editing capabilities but as something you embed in your own application. If you're designing a backend for a website and want something you can plug in that makes editing content easy, then TinyMCE is for you. If you're looking for anything else - e.g. something that handles logins or saving the content to a database - then you would need to build that yourself around TinyMCE.

**Comment by steviedeeee** [comment]
Okay, will do, thanks Tyler. JOCMS is built around TinyMCE.

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
