### ISSUE TITLE
Problem with page try-tinymce/url-conversion.md

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#157]
### [URL Conversion Example](try-tinymce/url-conversion.md) issue:

I wasn't able to work out what a lot of these examples were supposed to be doing as the initial content wasn't always descriptive enough to tell me what I should expect.

**Comment by r12s** [comment]
@Ahtaps agreed. @androb @Afraithe this is one for the product team. each example requires some descriptive text. if someone can ping me that i'll edit (as required) and update the page.

http://beta.tinymce.com/docs/try-tinymce/url-conversion/

**Comment by fyrkant** [comment]
Closing this as the links above are all dead so it's hard to know exactly what it is about. If this is something still relevant please leave a comment with some up to date information and I can open it up again.
