### ISSUE TITLE
Suppress table hover menu?

### ISSUE THREAD

**Issue by rogercoder** [tinymce/tinymce-docs#1578]
Is there a way to suppress the table hover menu that pops up when you're in the editor? Our users have been complaining that it "gets in the way".

**Comment by tylerkelly13** [comment]
Hi @rogercoder ,
To suppress the table toolbar, set the [`table_toolbar` option](https://www.tiny.cloud/docs/plugins/table/#table_toolbar) to an empty string, such as:
```
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "table",
  table_toolbar: ''
});
```

Let me know if this helps.
Tyler

**Comment by rogercoder** [comment]
That did it! Thanks so much!
