### ISSUE TITLE
I can't find what I'm looking for: general-configuration-guide/index.md

### ISSUE THREAD

**Issue by ziobit** [tinymce/tinymce-docs#1586]
How to DELETE AN ACCOUNT and REMOVE ALL THE DATA from the tiny.cloud website

**Comment by tylerkelly13** [comment]
Hi @ziobit ,


To delete your tiny.cloud account, please open a ZenDesk ticket with our support team.

https://www.tiny.cloud/docs/enterprise/support/

Tyler
