### ISSUE TITLE
Add integration of Python Django framework 

### ISSUE THREAD

**Issue by ketan1786** [tinymce/tinymce-docs#1588]
Please add Django framework application integration also.

**Comment by tylerkelly13** [comment]
Hi @ketan1786 .

Not sure what you are requesting. 
- If you are requesting that Tiny create and maintain an integration for django, please close this ticket and open a new ticket in the tinymce/tinymce repo.
- if you are looking for documentation on the third-party maintained django tinymce integration, visit: https://django-tinymce.readthedocs.io/en/latest/

Hope this helps.
Tyler

**Comment by tylerkelly13** [comment]
A new page has been added to the documentation regarding TinyMCE and Django at: https://www.tiny.cloud/docs/integrations/django/
This issue is resolved and will now be closed.
