### ISSUE TITLE
how resize video youtube on tinyMCE?

### ISSUE THREAD

**Issue by bank990999** [tinymce/tinymce-docs#1602]
when i add link youtube, video too big on tinyMCE. I want resize it, please help me, thanks.
> *affected page: https://www.tiny.cloud/docs/plugins/media/*

**Comment by tylerkelly13** [comment]
Hi @bank990999 ,

To resize the video:
- Click the video to select it (without playing it).
- On the menu bar, open *Insert* > *Media*.
- Change the height or width for the video.
- Click Save.

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
