### ISSUE TITLE
I can't find what I'm looking for: index.md

### ISSUE THREAD

**Issue by sirfragalot** [tinymce/tinymce-docs#1608]
I can only find licence information for v3. What about v5?

**Comment by tylerkelly13** [comment]
Hi @sirfragalot ,

The License for the TinyMCE editor and community plugins can be found here: https://github.com/tinymce/tinymce/blob/develop/LICENSE.TXT

Is this what you were looking for?
Tyler

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
