### ISSUE TITLE
I can't find what I'm looking for: integrations/wordpress.md

### ISSUE THREAD

**Issue by nzlgl** [tinymce/tinymce-docs#1623]
Hello, I have different plugins in my website and they are creating different forms (add event form, add product form, add blog post form, each comes from different plugin)Therefore, their rich text editors are different from each other. I want all those to be same. Do you support this?

**Comment by tylerkelly13** [comment]
Hi @nzlgl ,

We don't maintain the TinyMCE plugin for WordPress.
For questions regarding the Classic Editor plugin, see: https://wordpress.org/support/plugin/classic-editor/
For questions regarding the TinyMCE Advanced plugin, see: https://wordpress.org/support/plugin/tinymce-advanced/

If this question is not about the WordPress plugins, please re-open this ticket.

Tyler
