### ISSUE TITLE
I can't find what I'm looking for: advanced/usage-with-module-loaders.md

### ISSUE THREAD

**Issue by arsnyder16** [tinymce/tinymce-docs#1640]
Does webpacking tinymce violate the lgpl license for closed source use?

**Comment by tylerkelly13** [comment]
Tiny is unable to provide legal advice in relation to the use of the LGPL license. You should seek your own legal counsel on the application of LGPL. 

Tiny offers a commercial license that allows customers to avoid the strictures of open source. You should contact sales@tiny.cloud to discuss licensing options.

**Comment by arsnyder16** [comment]
@tylerkelly13 i am using the editor in inline mode, the only guidance I see for attribution is in the status bar, there is no status bar for the inline 

Is there any guidance for Inline mode?

**Comment by tylerkelly13** [comment]
Based on the requirements here: https://www.tiny.cloud/docs/general-configuration-guide/attribution-requirements/

> When including attribution, the following requirements must be met:
>* "**POWERED BY TINY**" to be stated or the [Tiny logo]({{site.url}}/guidelines/#logo) placed in a readily visible location whenever the editor is loaded.
>* The word "**Tiny**" or the Tiny logo should have a hyperlink to [https://www.tiny.cloud/](https://www.tiny.cloud/).
>* The location of the product attribution is to be:
> ....
>    * An alternate location adjacent to the TinyMCE editor that is no less prominent (than shown on the status bar).

So, placing the attribution below or beside the field would be best. Is it a single inline editor or several inline editors in a form?

**Comment by arsnyder16** [comment]
Thanks this is helpful. For my case it would be multiple inline editors within a single page

**Comment by tylerkelly13** [comment]
Ok, I'll raise this issue internally and get back to you with a response ASAP.

**Comment by tylerkelly13** [comment]
Hi @arsnyder16,

Sorry for the delay.
We are currently updating this page. When you have multiple editors on the same page, the attribution needs to clearly visible and you only need one attribution on the page where an editor appears. 

Thanks
Tyler

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
