### ISSUE TITLE
Problem with page advanced/migration-guide-from-3.x.md

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#165]
### [Migrate from 3.x](advanced/migration-guide-from-3.x.md) issue:
* The links to the removed plugins all lead to a page that displays a "You don't have permission to edit this page" message.
* The compat3x plugin link leads to the schema topic in the Content Filtering section.

**Comment by r12s** [comment]
* @hassaab re point one, the links are being broken by GA. if i cut/paste a link directly they resolve correctly.
* re compat3x this has been fixed.

**Comment by kilianc** [comment]
@r12s since compat3x has been fixed I am going to close this because is a duplicate
