### ISSUE TITLE
wrong example in docs for video_template_callback

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce-docs#1660]
https://www.tiny.cloud/docs/plugins/media/#video_template_callback
as 5.4.2 data.source1 is now data.source

P.S. please fix tinymce/tinymce#4112

**Comment by tylerkelly13** [comment]
Thanks @bes-internal ,
We've updated the following media callback examples to show the correct data sources:
- https://www.tiny.cloud/docs/plugins/media/#exampleusingaudio_template_callback
- https://www.tiny.cloud/docs/plugins/media/#exampleusingvideo_template_callback
Thanks again for the bug report
Tyler
