### ISSUE TITLE
Export to .doc or .docx

### ISSUE THREAD

**Issue by KevinBrother** [tinymce/tinymce-docs#1700]
I want to  save to .doc or .docx.

**Comment by tylerkelly13** [comment]
Hi @KevinBrother ,

TinyMCE currently does not have this functionality. Would you like me to move this issue to the product repository and mark it as a feature request for management team?

Tyler

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please reopen or create a new issue if this issue should not have been closed.
