### ISSUE TITLE
I can't find what I'm looking for: demo/custom-toolbar-button.md

### ISSUE THREAD

**Issue by rmacfadyen** [tinymce/tinymce-docs#1702]
Doesn't show/explain where the icon comes from or how I can specify my own icon.

**Comment by tylerkelly13** [comment]
Hi @rmacfadyen ,

You can find information on creating custom toolbar buttons here: https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/

This page also has links to information on adding icons.

Tyler

**Comment by tylerkelly13** [comment]
Side note: I plan on removing this demo page, along with some others. The demo is also on the toolbar button page I linked to.

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
