### ISSUE TITLE
tiny para Balde de Laravel

### ISSUE THREAD

**Issue by yassercf** [tinymce/tinymce-docs#1710]
Poseen alguna integracion de tiny para Laravel con Blade

**Comment by tylerkelly13** [comment]
Sorry, we can only accept issues in English. Please reopen or open a new issue if you can translate your issue/question into English.
Note: I see the word Laravel, so this may also be a duplicate of #1627

**Comment by yassercf** [comment]
You have some tiny integration for Laravel with Blade
