### ISSUE TITLE
You have some tiny integration for Laravel with Blade

### ISSUE THREAD

**Issue by yassercf** [tinymce/tinymce-docs#1711]
You have some tiny integration for Laravel with Blade

**Comment by tylerkelly13** [comment]
Hi @yassercf,

I'm not sure what you are asking or requesting. Could you provide more information?

Note: I know Laravel is sometimes installed using the Composer package manager, which we have some installation documentation for here: https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#composer

Tyler

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
