### ISSUE TITLE
Problem with page plugins/moxiemanager.md

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#172]
### [MoxieManager Plugin](plugins/moxiemanager.md) issue:
The Integrate with TinyMCE link leads to a page with the text "TinyMCE_Integration?_ga=1.264841353.742023185.1447737160".

**Comment by r12s** [comment]
unable to replicate this. @hassaab can you replicate? if not please close the issue. thanks.

**Comment by kilianc** [comment]
@r12s this is related to external links and `_ga`, it's known and we're trying to fix it. Closing since it's duplicate
