### ISSUE TITLE
Plugin pages have menu item and toolbar button items in header.

### ISSUE THREAD

**Issue by Ahtaps** [tinymce/tinymce-docs#175]
I thought due to the number that I'd log it as one issue.

Many of the Plugin pages in the documentation have a (+ menu item) and (+ toolbar button) element in their header.  Some of them only have one or the other, but a list of pages affected is as follows:
* Anchor
* Autosave
* Character Map
* Code
* Codesample
* Directionality
* Emoticons
* Full Page
* Full Screen
* Horizontal Rule
* Insert Date/Time
* Link
* Media
* Nonbreaking Space
* Page Break
* Preview
* Print
* Save
* Search and Replace
* Spellchecker
* Table
* Template
* Text Colour
* Visual Blocks
* Visual Characters

**Comment by r12s** [comment]
correct. please advise whether this is helpful, not helpful, et cetera.

**Comment by Ahtaps** [comment]
Now that I am looking at it again, I think I understand them as indicators of how they integrate into Tiny MCE?  My initial thought was that they were left over placeholder heading items from the document editing tool.  I think the visual representation is what threw me off.

**Comment by r12s** [comment]
thanks @Ahtaps you're correct. that the intent wasn't immediately clear isn't ideal. i'll close the issue and the team will continue discussing this offline. some user testing may be in order.
