### ISSUE TITLE
I can't find what I'm looking for: integrations/index.md

### ISSUE THREAD

**Issue by madhumitharaju** [tinymce/tinymce-docs#1762]
hi looking for integration with polymer .can u help us out?

**Comment by tylerkelly13** [comment]
Hi @madhumitharaju ,
Assuming you are referring to [Polymer Project](https://www.polymer-project.org/), we do produce a web component integration. For details, see: https://www.tiny.cloud/docs/integrations/webcomponent/

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please reopen or create a new issue if this issue should not have been closed.
