### ISSUE TITLE
Laravel support?

### ISSUE THREAD

**Issue by eduardonwa** [tinymce/tinymce-docs#1769]
Im just beginning working with Laravel, I know it has Vue integration, will it work anyway? Thanks, awesome tool.

**Comment by tylerkelly13** [comment]
Hi @eduardonwa 

I don't have any documentation for using TinyMCE with Laravel yet, however, we do provide a PHP package through PHP composer. You can find some information on using it here: https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#composer

Tyler

**Comment by eduardonwa** [comment]
Thanks, I managed to install it via LaravelMix. Cheers.
