### ISSUE TITLE
What is the substitute for the this.settings of onclick in the version 5 and above?

### ISSUE THREAD

**Issue by KrunalMeher** [tinymce/tinymce-docs#1772]
What is the substitute for the this.settings of onclick in the version 5 and above?

**Comment by tylerkelly13** [comment]
Hi @KrunalMeher ,

`onClick` has been replaced with `onAction`. Our migration guide should be able to help you further, for example here is the section on changes to the toolbar button APIs (including `onClick` to `onAction`): https://www.tiny.cloud/docs/migration-from-4x/#changedtoolbarapimethods

Tyler

**Comment by tylerkelly13** [comment]
This question appears to have been answered and will now be closed.
If this issue should not have been closed, please reopen with more information or create an issue.
