### ISSUE TITLE
bug : ui-components/urldialog.md

### ISSUE THREAD

**Issue by Zmira134** [tinymce/tinymce-docs#1785]
The interactive example at the page bottom is not working

**Comment by tylerkelly13** [comment]
Hi @Zmira134 ,

Could you please provide more information on the bug? The interactive example appears to work as expected.

Tyler

**Comment by Zmira134** [comment]
Hi Tyler Kelly,

When I press the {;} in the UrlDialog interactive example I get 404 error message from CodePen.

Thanks
Zmira


[cid:image003.jpg@01D6C95D.7385AC10]

**Comment by tylerkelly13** [comment]
Hi @Zmira134 ,

Had a look at the issue, although the interactive example works as expected on our site, it will not work on codepen due to:
- A relative link, rather than an absolute link.
- Browsers may now block the cross-domain traffic.
I'll remove the link to the codepen site.

Thanks 
Tyler

**Comment by tylerkelly13** [comment]
Hi @Zmira134,

We have updated the example to resolve the issue. The change is now live at: https://www.tiny.cloud/docs/ui-components/urldialog/#interactiveexample

Tyler

**Comment by Zmira134** [comment]
Hi Tyler Kelly,

Thanks for the effort.
The script in the external-page.html was what I was looking for.

I also came across another example that helped me with url dialog at : https://codesandbox.io/embed/tinymce-dialog-openurl-demo-fpfew.

Thanks again

Zmira
