### ISSUE TITLE
I can't find what I'm looking for: tinydrive/get-help.md

### ISSUE THREAD

**Issue by 6120ssu** [tinymce/tinymce-docs#1793]
Can tiny drive be used on my local server ?
How can I use a custom file browser for my local server (I have been using my own for years in 3.x and 4.x) ?

**Comment by lincolndennis** [comment]
Hello!

Tiny Drive is our Cloud Storage option, and is only available as part of our Cloud Platform. 

For more information about Tiny Drive, we recommend setting up a Tiny Cloud account. 

https://www.tiny.cloud/auth/signup/

Creating a new tiny.cloud account gives you 30 days access to our Support platform, where you can open up to two tickets. Our Support Engineers can work with you and coordinate with Engineering as needed to answer relevant technical questions regarding TinyMCE and Tiny Drive.
