### ISSUE TITLE
I can't find what I'm looking for: enterprise/tiny-comments.md

### ISSUE THREAD

**Issue by zzk-true** [tinymce/tinymce-docs#1795]
是否支持编辑内容留痕，或者内容修订标记
Whether to support the marking of editing content or content revision mark

**Comment by tylerkelly13** [comment]
Hi @zzk-true ,

Can you provide more information? Including the use-case?

Tyler

**Comment by zzk-true** [comment]
协同编辑时，下游用户可以看到上游用户对内容的修改位置，类似于office的审阅模式，但是不需要展示过于详细的信息，只需要展示一个简单标记以证明此处内容有过变动。
In collaborative editing, downstream users can see the modification position of upstream users, which is similar to the review mode of office. However, it does not need to display too detailed information, but only needs to display a simple mark to prove that the content has changed here.

**Comment by tylerkelly13** [comment]
Hi @zzk-true ,

This is not a feature we currently support. This feature is provided by one of our Technology Partners. See https://www.tiny.cloud/blog/simple-and-intuitive-track-changes-for-any-content-workflow/

Tyler

**Comment by zzk-true** [comment]
嗨@tylerkelly13  此功能可以嵌入到TinyMCE中吗
