### ISSUE TITLE
Both "Docs" and "Demo" are underlined when viewing this page

### ISSUE THREAD

**Issue by damienfitz** [tinymce/tinymce-docs#180]
### [Full Featured Example](try-tinymce/full-featured.md) issue:

There appears to be some subtle issues with the underlining of items in the main toolbar.

On this page both "Docs" and "Demo" are underlined.

However on the documentation home page (http://beta.tinymce.com/docs/) nothing is underlined in the toolbar.

Not sure if anyone other than me will notice.

**Comment by kilianc** [comment]
@damienfitz I noticed this too, since it's a 30s fix it's worth fixing it! Thanks for reporting.
