### ISSUE TITLE
Docs: ui-components/typesoftoolbarbuttons.md - swap sections

### ISSUE THREAD

**Issue by dakur** [tinymce/tinymce-docs#1802]
I suggest swapping of sections Split button and Menu button. That's because Split button refers to Menu button, but reader does not know about it yet as it is defined below.

> A split button contains a basic button and a menu button, wrapped up into one toolbar item.

**Comment by tylerkelly13** [comment]
@dakur Thanks for suggesting this.

The fix is live on the TinyMCE documentation site here: https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/
