### ISSUE TITLE
TinyMCE: Paste option doesn't work in Chrome and Firefox

### ISSUE THREAD

**Issue by arenduli** [tinymce/tinymce-docs#1808]
On Linux (Ubuntu) in TinyMCE editor
Paste option in Edit menu doesn't work, I got the message:
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead."
Does exist some solution how to solve it?

Thanks, in advance.

**Comment by tylerkelly13** [comment]
Hi @arenduli , 

Unfortunately no. As it states, browsers do not provide direct access to the device clipboard, which is an issue google docs users often also encounter: https://www.usatoday.com/story/tech/columnist/2014/04/13/copy-and-paste-in-google-docs/7568661/

Sorry we can't provide a better solution.

Tyler
