### ISSUE TITLE
I can't find what I'm looking for: index.md

### ISSUE THREAD

**Issue by ScottSEA** [tinymce/tinymce-docs#1809]
Can't find in the documentation what the upper limit is for an instance of the text editor.  What is the maximum number of characters one instance can handle at a time?

**Comment by tylerkelly13** [comment]
Hi @ScottSEA,

There is no defined limit in TinyMCE. The "limit" would depend on the resources (RAM and Architecture) available to the user's browser, and (possibly) the user's browser itself.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
