### ISSUE TITLE
Is an Api-key required for Self-hosting ?

### ISSUE THREAD

**Issue by joe-oli** [tinymce/tinymce-docs#1810]
**Documentation/Product Version**
Not sure Prod Version, whatever version below url's refer to.

**Related page URL (if applicable)**
https://www.tiny.cloud/docs/integrations/react/
https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/

**I would like to know...**
I have read step 6. on the first url.
It mentions for info on self-hosting, see https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/

After reading both links, it is still not clear if I need the API-KEY for SELF-HOSTING.

Can the answer be made explicit and clear in both documents above, whether an API-KEY is needed for self-hosting?

And when is an API-KEY required (if at all) for self-hosting, e.g. as we add more plugins, will it demand an api-key?

**Comment by tylerkelly13** [comment]
Hi @joe-oli,

No, an API-key is not needed for self-hosted deployments of TinyMCE. The links on that will be updated to point to:
- [Package Manager Install Options](https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#packagemanagerinstalloptions).
- [Self-Hosted Install](https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#self-hostedinstall).

Also, thank you for the feedback. All of these pages are marked for significant changes in the future and your feedback will help greatly.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.

**Comment by drahkrub** [comment]
self-hosted without API-key gives a "nice" popup: 
![image](https://github.com/tinymce/tinymce-docs/assets/1061679/1bd74529-b9c7-40e0-9651-6bda4c0d21d7)

self-hosted with a free Core plan API-key prevents the pop-up from appearing, but the editor contains an advertising icon in the bottom right-hand corner:
![image](https://github.com/tinymce/tinymce-docs/assets/1061679/c228df5b-5dea-43b2-a64a-fe617dcb8ef0)

https://www.tiny.cloud/pricing/ says YES to "White Label" starting with the Essential plan (but surprisingly NO to "Self-hosted Deployment").

Question: If self-hosted deployment is used with the Essential plan, does the advertising icon disappear?

**Comment by drahkrub** [comment]
ok, sorry, just found https://www.tiny.cloud/legal/attribution-requirements/

**Comment by valeryanka** [comment]
We created the [Invalid API key help post](https://www.tiny.cloud/docs/tinymce/6/invalid-api-key/ to provide more details.

**Comment by jowin202** [comment]
I am sorry, but the API key system sucks. 

Is there a full NPM package, which does not require this ..

**Comment by TheSpyder** [comment]
If you see a popup regarding API keys or tiny cloud then you are not using a self-hosted editor. Our NPM packages do not require an API key.

However many of our integrations load TinyMCE from our cloud for a faster out-of-the-box experience, and that will prompt for an API key. This is not a requirement, it is only the default. Each integration has a documented way to load the editor as self-hosted.
https://www.tiny.cloud/docs/tinymce/latest/installation/

**Comment by jowin202** [comment]
I used this tutorial for the tinymce: https://www.tiny.cloud/docs/tinymce/latest/angular-pm/
and I exactly got this
![image](https://github.com/user-attachments/assets/967c3f86-fe18-4b77-add0-dcc634d218b5)

I would like to use the editor on my local intranet, no connection to anywhere, just LAN inside my house. Is there an easy way to disable everything with APIs and Keys and pay-to-use and clouds? Just me, my webserver, and my browser. no requests anywhere else than 127.0.0.1?

Somehow it makes me sad that using an npm package prompts for some api keys per default. the default version should be the free version. it costs me hours to find a solution to disable the api key.

**Comment by kirkkoster** [comment]
did you ever figure this out?

**Comment by jowin202** [comment]
Switched to ngx-quill

**Comment by jowin202** [comment]
the problem is that the DRM api key stuff is written in a shitty way that it always shows the API key thing if it does not find the local js file. what you can do is to manually include <script src=".../tinymce.min.js"></script> (or whatever the name is) by hand in angular template file. make sure the path is available and does not respond with 404. also check out the web developer console if the script is requested. it worked for me once (with the help of chatgpt), but I'll try to put an example project online.

for the maintainers: please can you make it in a way that including into angular works out-of-the-box without checking paths and manually include anything? it would be really helpful
