### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/searchreplace.md

### ISSUE THREAD

**Issue by lucky-nmk** [tinymce/tinymce-docs#1811]
Hi, I want to disable the default Find and replace on ctrl + f and to replace with new find and replace which I developed. How can I do it. I am expecting when the user click ctrl + f the new find and replace should pop up. How can I achieve it on 4.7 version.

**Comment by tylerkelly13** [comment]
Hi @lucky-nmk, 

You'll need to remove `searchreplace` from the plugins list, and ensure your plugin uses a different name. For information on creating TinyMCE 4 plugins, see: https://www.tiny.cloud/docs-4x/advanced/creating-a-plugin/.

Note: TinyMCE 4 is no-longer supported and this issue will now be closed. Please consider migrating to TinyMCE 5.
For a list of supported versions, see: [Supported TinyMCE versions](https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedtinymceversions).
For information on migrating to TinyMCE 5, see: [Migrating from TinyMCE 4 to TinyMCE 5](https://www.tiny.cloud/docs/migration-from-4x/).

Tyler
