### ISSUE TITLE
How to dynamically add inline styles in html tags in tinymce 4 editor

### ISSUE THREAD

**Issue by nsuriya23** [tinymce/tinymce-docs#1812]
I am using tinymce 4.5.12 editor as email editor, how to dynamically add inline style to html elements on inserting the content in editor.

I have tried to add the paragraph with custom css, after the tinymce editor has been initiated, by using the below command to set editor default inline style for paragraph tag.

`tinymce.get('tinymce_editir_id').execCommand('mceInsertContent', false, '<p class="pmbot_p" style="margin: 0in; margin-bottom: .0001pt; font-size: 11.0pt; font-family: Calibri; color: #1F497D;"><br></p>');`

Whenever i hit enter the below paragraph added with style

`<p class="pmbot_p" style="margin: 0in; margin-bottom: .0001pt; font-size: 11.0pt; font-family: Calibri; color: #1F497D;"><br></p>`

But When i choose bullet or number list option, the paragraph style gets reset and there is no style in the tag.

`<p></p>`

Can you please suggest any solution for this?

Thanks in advance.

**Comment by tylerkelly13** [comment]
Hi @nsuriya23,

I was unable to reproduce this issue using https://fiddle.tiny.cloud/. Using the reproduction case given, the paragraph element is replaced by a unordered list element. The styles would be stripped by the editor's clean-up functionality. Consider this paragraph style as a format using the `format` option: https://www.tiny.cloud/docs-4x/configure/content-formatting/#formats this may solve the issue.

Note: TinyMCE 4 is no-longer supported and this issue will now be closed. Please consider migrating to TinyMCE 5.
For a list of supported versions, see: [Supported TinyMCE versions](https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/#supportedtinymceversions).
For information on migrating to TinyMCE 5, see: [Migrating from TinyMCE 4 to TinyMCE 5](https://www.tiny.cloud/docs/migration-from-4x/).

Tyler
