### ISSUE TITLE
How to set text indent from top and bottom edge in this editor?

### ISSUE THREAD

**Issue by Jaroslav298** [tinymce/tinymce-docs#1815]
> *affected page: https://www.tiny.cloud/docs/configure/content-formatting/*

**Comment by tylerkelly13** [comment]
Hi @Jaroslav298 

The padding/margins of the content in the editor can be defined using the `content_css` option. See: https://www.tiny.cloud/docs/configure/content-appearance/#content_css.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.

**Comment by Jaroslav298** [comment]
This problem is resolved.
Thank you.
Jaroslav298
