### ISSUE TITLE
ui-components/autocompleter.md const versus var

### ISSUE THREAD

**Issue by philiprbrenan** [tinymce/tinymce-docs#1839]
Surely it should be: 

const onAction

not

var onAction

?

**Comment by lnewson** [comment]
Hi @philiprbrenan,

As TinyMCE still supports IE 11, we're unable to use ES6 or above features in our documentation, as the examples we provide must be able to be run on our supported browsers. As such, using `var` is correct, though can safely be changed if you don't need to support IE 11 or have something to transpile it to ES5.

**Comment by philiprbrenan** [comment]
I see!  Thanks!
