### ISSUE TITLE
TinyMCE integration is missing in Django

### ISSUE THREAD

**Issue by mnkhtrbukhbold** [tinymce/tinymce-docs#1842]
Hi, I was interested in integrating your editor onto my website. I used Django as my framework for my web. Sadly, I didn't find the guide for TinyMCE integration for Django. Therefore I am writing this ticket to take a look at my request about documentation or guide to integrating TinyMCE for my Django web. I am pretty sure that there are a lot of people who want the same thing as I am :)

**Comment by lnewson** [comment]
Hi @mnkhtrbukhbold,

There is already a third-party integration for Django available and documentation available is available here: https://www.tiny.cloud/docs/integrations/django/. This only goes over the high-level integration details, but the full docs can be found published by the `django-tinymce` creators here: https://django-tinymce.readthedocs.io/en/latest/index.html
