### ISSUE TITLE
I can't find what I'm looking for: general-configuration-guide/use-tinymce-classic.md

### ISSUE THREAD

**Issue by ChristopherParke** [tinymce/tinymce-docs#1866]
Hi,

I'm trying to access the element containing the input data with JavaScript -- but it always returns "undefined".  I can see there is a DOM element with id "tinymce", and it has a p element in it -- but that always shows as null.  Why is that?

Ideally, I would still be able to target my textarea element by id and grab the value out of that.

Thanks.

**Comment by tylerkelly13** [comment]
Hi @ChristopherParke,

The best method for retrieving the editor content using Javascript is to use the `getContent` API. For information on this API, see: https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
