### ISSUE TITLE
Problem with page release-notes/release-notes5013.md

### ISSUE THREAD

**Issue by eduardonwa** [tinymce/tinymce-docs#1869]
Im trying to figure out how to change the background color of the editor to something like ```#1a202c```, thanks. Doesn't seem to be that obvious from the documentation since most topics only cover plugins, like the pen plug-in or the plug-in that lets you change the background color for a block inside the editor. 

> *affected page: https://www.tiny.cloud/docs/release-notes/release-notes5013/*

**Comment by tylerkelly13** [comment]
Hi @eduardonwa,

To change the background color, use the `content_CSS` option, described at: https://www.tiny.cloud/docs/configure/content-appearance/#content_css

For an example CSS file to provide this setting, including the classes we use, see https://github.com/tinymce/tinymce-dist/tree/master/skins/content . I recommend looking at the `dark` content CSS file (https://github.com/tinymce/tinymce-dist/blob/master/skins/content/dark/content.css) which changes the background to a darker color.

Tyler

**Comment by eduardonwa** [comment]
Thanks for the helpful links, one question remains: can I overwrite the classes using my own CSS file? Or does it need to have the same name from the folder structure, aka this file https://github.com/tinymce/tinymce-dist/blob/master/skins/content/dark/content.css thanks!
