### ISSUE TITLE
Problem with page demo/local-upload.md

### ISSUE THREAD

**Issue by douglerner** [tinymce/tinymce-docs#1873]
I can't seem to find a working example of image upload anywhere. Are there any? Thanks.

> *affected page: https://www.tiny.cloud/docs/demo/local-upload/*

**Comment by tylerkelly13** [comment]
Hi @douglerner ,

We don't have any working examples for the image upload functionality. The image upload functionality requires a back-end setup. I recommend looking at this page for a better example: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#imageuploadoptions
If you have a PHP-based back-end, we also have this example: https://www.tiny.cloud/docs/advanced/php-upload-handler/

If you need more information, let me know and I'll pass this issue to our developers.

Tyler

**Comment by douglerner** [comment]
Hi. I actually found an example of this UI here:
https://www.tiny.cloud/docs/demo/file-picker/

Thanks,

doug

**Comment by tylerkelly13** [comment]
Awesome! Glad you found a solution.
