### ISSUE TITLE
I can't find what I'm looking for: general-configuration-guide/localize-your-language.md

### ISSUE THREAD

**Issue by miryuk** [tinymce/tinymce-docs#1877]
Hello! Is it possible to localize a tooltip's value of a custom button to all languages?

**Comment by tylerkelly13** [comment]
Hi @miryuk,

If you only have one string to translate, this fiddle shows you how: https://fiddle.tiny.cloud/D5haab/5

If you have more than one tooltip to translate, we recommend creating a plugin for the button(s) and using these instructions: https://www.tiny.cloud/docs/advanced/creating-a-plugin/#languagelocalization

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
