### ISSUE TITLE
Problem with page integrations/bootstrap.md

### ISSUE THREAD

**Issue by musicman3** [tinymce/tinymce-docs#1878]
Hello. I am unable to integrate tiny with bootstrap 5 in a modal window. No focus on Link insertion, picture insertion, etc.

Here's an example: 
http://fiddle.tiny.cloud/gRgaab/187

> *affected page: https://www.tiny.cloud/docs/integrations/bootstrap/*

**Comment by lnewson** [comment]
I see you've logged this in the actual TinyMCE repo as well, so I'm going to close this.

**Comment by musicman3** [comment]
ok
