### ISSUE TITLE
"This domain is not registered with Tiny Cloud" on mobile app running on iOS

### ISSUE THREAD

**Issue by miralos** [tinymce/tinymce-docs#1886]
Dear,

I implemented Tiny Cloud in my mobile app. App is done with Ionic, angular, typescript. Everything works fine while in development mode using my browser Safari or the emulator; but when I compile the app for iOS and I deploy the app to TestFlight and download it to my iPhone device, whenever I show a textarea with TinyMCE there is a warning popping up that never disappears "This domain is not registered with Tiny Cloud. Please review your approved domains".
I can't manage to find which is the domain used by my app. I tried everything, domain of the web app, IP, id of the mobile app on App Store.
What should I use in approved domain to allow my TinyMCE without warning in my app?

Regards

**Comment by tylerkelly13** [comment]
Hi @miralos 

For support related to Tiny Cloud, please log ticket with our support team at https://support.tiny.cloud.

Tyler
