### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/index.md Math Plugin

### ISSUE THREAD

**Issue by bridgeyuwa** [tinymce/tinymce-docs#1892]
Please do you have a free Math plugin? one that can render mathjax, latex etc....

**Comment by tylerkelly13** [comment]
Hi @bridgeyuwa 

Unfortunately we do not have a free Math plugin. There is only a plugin provided by one of our partners: https://www.tiny.cloud/partners/

Tyler

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please create a new issue if this issue should not have been closed.
