### ISSUE TITLE
Problem with page plugins/premium/export.md

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#1893]
"licence" should be spelled "license"

> *affected page: https://www.tiny.cloud/docs/plugins/premium/export/*

**Comment by tylerkelly13** [comment]
Hi @androb,

This typo will be fixed up when we release TinyMCE 5.8.

Tyler

**Comment by tylerkelly13** [comment]
Hi @androb ,

The fix is now live on the TinyMCE documentation site.

Tyler
