### ISSUE TITLE
I can't find what I'm looking for: integrations/index.md

### ISSUE THREAD

**Issue by jamontes79** [tinymce/tinymce-docs#1895]
Hi,

It could be possible to add tinymce in a flutter web application?

Thanks in advance
Best regards

**Comment by EkimChau** [comment]
jamontes79, TinyMCE does not have an official integration for the Flutter framework.  We may consider future support should we get enough requests from developers using this framework.

It is possible to load TinyMCE into a webview and create bridging code between your application and the webview to communicate with TinyMCE's javascript apis.

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please create a new issue if this issue should not have been closed.
