### ISSUE TITLE
Backticked code in titles should be the same size as the title

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#19]
Text marked with backticks in titles currently defaults to the `<p>` style and size. It would ideally be similar in size and style as the element it is inline with, e.g `h3`.

http://localhost:4000/getting-started/first-steps/#stepsavingcontentwithaformpost

**Comment by r12s** [comment]
UPDATE: let's review whether having code formatting in titles is a good idea in the first place. This is inherited from the 4.2 docs. Note, including code formatting breaks titles so the options are to backtick code formatting or remove it completely (or fix the behavior with a script).

**Comment by kilianc** [comment]
done
