### ISSUE TITLE
Make multi type init keys consistent with toolbar

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#190]
Make multi type init keys consistent with `toolbar` option in Config /Editor Appearance section.

**Comment by r12s** [comment]
thanks @kilianc massive job. i'll need to create a style guide entry on this so that others can help. plus it will need to become the default state (so to speak) for all config and plugin entries.

**Comment by kilianc** [comment]
see the last commit on the branch https://github.com/tinymce/tinymce-docs/tree/consistent-structure

**Comment by r12s** [comment]
this is a work-in-progress.

**Comment by tylerkelly13** [comment]
This issue appears to have been resolved, and given the amount of time that has passed, this ticket will now be closed.
Please reopen or create a new issue with more information if this issue should not have been closed.
