### ISSUE TITLE
images_upload_handler is not triggered in Tinymce if the file extension is .tiff

### ISSUE THREAD

**Issue by za-webdev** [tinymce/tinymce-docs#1903]
**Product Version**
TinyMCE 5.7.0

**I would like to know...**

Is there a way to show error in Tinymce when the image file type is unsupported. When trying to upload or paste a .tiff file into the editor Tinymce just ignores the image and it doesn't even trigger the images_upload_handler that's why I cant do any validation inside the images_upload_handler. I have used block_unsupported_drop but this only shows errors when dropping the image not when uploading or pasting an image.

**Comment by tylerkelly13** [comment]
Hi @za-webdev 

The `images_file_types` option was added in TinyMCE 5.6, which allows you to configure which file types are unsupported. See: https://www.tiny.cloud/docs/plugins/opensource/image/#images_file_types.

I'll follow up with the developers about how to show the error.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
