### ISSUE TITLE
I can't find what I'm looking for: advanced/keyboard-shortcuts.md

### ISSUE THREAD

**Issue by Taumai** [tinymce/tinymce-docs#1904]
I cannot type Diacritical Marks on my keyboard. I need to use some Latin Marks (letters) using my keyboard. I have a PC. What do I have to do?

**Comment by tylerkelly13** [comment]
Hi @Taumai 

To insert characters that are not present on your keyboard, please use the Special Character menu option if it is available. If the Special Character option is not available, please talk to the webpage or application owner.

Information on the Special Character option (`charmap`) can be found here: https://www.tiny.cloud/docs/plugins/opensource/charmap/

Tyler

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please create a new issue if this issue should not have been closed.
