### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/visualblocks.md

### ISSUE THREAD

**Issue by davidhywel** [tinymce/tinymce-docs#1906]
I;m trying to give blocks - divs, paras etc -some background colour (as well as to thev text within it)

**Comment by tylerkelly13** [comment]
Hi @davidhywel,

The best way to achieve this is to use the `content_css` option. For details, see: https://www.tiny.cloud/docs/configure/content-appearance/#content_css

If you only need to define one or two styles, you can use the [`content_style` option](https://www.tiny.cloud/docs/configure/content-appearance/#content_style).

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.
