### ISSUE TITLE
Problem with page try-tinymce/full-featured.md

### ISSUE THREAD

**Issue by andreas271828** [tinymce/tinymce-docs#191]
### [Full Featured Example](try-tinymce/full-featured.md) issue:
![scrollbar](https://cloud.githubusercontent.com/assets/5901143/11255645/15c83b7e-8e93-11e5-921e-5be4e3074cf7.png)
The 'Results' view has a scrollbar in this example, but not in any of the other examples.
Linux Mint 17, Firefox, 27" screen, 2560x1440

**Comment by r12s** [comment]
@kilian i can replicate this via online browser testing services on IE11 (issue reported on firefox) and the issue relates to this example only. looks like codepen iframe isn't big enough for tinymce iframe. any thoughts on a fix?

(it's kind of like the Inception of iframes)

**Comment by kilianc** [comment]
@r12s you can pass height to the codepen include file

**Comment by r12s** [comment]
thanks @kilianc done and appears to have fixed the problem. tested using online browser tools. marking closed.
