### ISSUE TITLE
I can't find what I'm looking for: Math Formula Plug-ins

### ISSUE THREAD

**Issue by GregLee-Jeffco** [tinymce/tinymce-docs#1913]
I'm specifically looking for some kind of plug that will help teachers/educators write basic math formulas for their students to see  using Rich Text Editor (TinyMCE).  Anyone know of something available?

**Comment by tylerkelly13** [comment]
Hi @GregLee-Jeffco,

One of our Technology Partners, WIRIS, provides a math formula plugin: https://www.tiny.cloud/partners/

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.
