### ISSUE TITLE
I can't find what I'm looking for: index.md

### ISSUE THREAD

**Issue by ttttttssssss** [tinymce/tinymce-docs#1917]
How do I set the overall background color of the document？
> If you set a background color for each line of text they will not be continuous.
> I need to set a background color for the entire page
![image](https://user-images.githubusercontent.com/58020640/113109707-d425c100-9238-11eb-9fbc-ebdebb183dcf.png)

**Comment by tylerkelly13** [comment]
Hi @ttttttssssss,

The content CSS option will allow you to change the background color of the editor: https://www.tiny.cloud/docs/configure/content-appearance/#content_css

Tyler

**Comment by ttttttssssss** [comment]
Thank you for your answer
