### ISSUE TITLE
JavaScript error: Uncaught TypeError: Cannot read property 'addClass' of undefined when clicking on Editor Command Identifiers

### ISSUE THREAD

**Issue by ephox-mogran** [tinymce/tinymce-docs#194]
Steps to replicate:

1. Go to docs search
2. Type "Commands" into the search field
3. Click on "Editor Command Identifiers"

A JavaScript error is logged to console.

**Comment by r12s** [comment]
this is replicable from the same search query (i.e. "command") when clicking on the "Text Pattern Plugin" result. i have tried some additional searches and have not yet been able to replicate.

**Comment by kilianc** [comment]
JS is tracked on an internal repository and there is ticket for this already :beer:
