### ISSUE TITLE
Problem with page configure/editor-appearance.md

### ISSUE THREAD

**Issue by TheSpyder** [tinymce/tinymce-docs#197]
### [Editor Appearance](configure/editor-appearance.md) issue:

The `toolbar<n>` link in the sidebar doesn't work. It resolves to:

`/%20docs/%20configure/%20editor-appearance/#%20toolbar<%20n>`

I guess something about the link name is causing spaces to be added, if I use the DOM browser to manually remove them it works.

**Comment by r12s** [comment]
@kilianc this appears to be fixed. Marking closed.
