### ISSUE TITLE
Edit html-files locally on my laptop - possibly on localhost?

### ISSUE THREAD

**Issue by MartinInFrankfurtAM** [tinymce/tinymce-docs#1980]
For my internal reports analysing confidential data, I use R Markdown source files in the RStudio IDE to produce htmloutput.
The main advantage for me are interactive features and the absence of pagebreaks. 
No server involved.
Some IT-illiterate readers miss the possibility to write their own comments in my html-document, they do not care to use the Excelfiles that my R-Markdown script exports.
Could they do this if I provide the with tinymce on their Windows-PCs?

**Comment by tylerkelly13** [comment]
Hi @MartinInFrankfurtAM ,

It is possible, but there are better ways to solve your issue. Without a server it would be difficult. At present, we provide Microsoft Word-like "comments" in a premium plugin.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.
