### ISSUE TITLE
my favorite framewrok is laravel

### ISSUE THREAD

**Issue by H-web268** [tinymce/tinymce-docs#1981]
I use laravel to build my application in backend and livewire in frontend

**Comment by tylerkelly13** [comment]
Hi @H-web268,

We provide a PHP package through composer. You can find some instructions here: https://www.tiny.cloud/docs/general-configuration-guide/advanced-install/#composer

Let me know if this helps

Tyler

**Comment by H-web268** [comment]
hi tylerkelly13 thank you very much that helps

**Comment by tylerkelly13** [comment]
Thanks for letting me know @H-web268 

This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.

**Comment by H-web268** [comment]
thank you very much the issue is resolved

Le jeu. 3 juin 2021 à 00:45, Tyler Kelly ***@***.***> a
écrit :
