### ISSUE TITLE
Root tinymce "class" missing methods in API docs

### ISSUE THREAD

**Issue by spocke** [tinymce/tinymce-docs#199]
This should include all properties:
http://beta.tinymce.com/docs/api/class/tinymce/

That this one has:
http://www.tinymce.com/wiki.php/api4:class.tinymce

**Comment by kilianc** [comment]
@spocke basically you want me to expand the entire inheritance three right ? I can hard patch it for the time being but we should probably do this in moxiedoc for every class. I think we need a new column with `declared in` where we say were that method come from?

**Comment by kilianc** [comment]
I just went for it, since we're doing it let's do it right! take a look, http://stagecoach.tinymce.com/docs/pr/week-10/api/class/tinymce/

cc/ @r12s
