### ISSUE TITLE
Problem with page general-configuration-guide/basic-setup.md

### ISSUE THREAD

**Issue by whitsey** [tinymce/tinymce-docs#1991]
The setup is helpful for a newbie to get an instance into the page with minimal effort - straight out of the box.
But, Now I want to save the data to the DB using Ajax and the textarea content remains unchanged and nothing updates.
I don't even know what to look for - I've been searching - save content, update data???
I've been reading through the doco for the past 30 mins and I am yet to find anything that talks about saving content to the DB or accessing the changes in the textarea.
I'm guessing you have your own specific term for the "saving data" but to a newbie, I dont know your terminology.
I would've thought that the 2nd most important component after initialising the editor was working with the content in the editor and saving it to an external data source...

> *affected page: https://www.tiny.cloud/docs/general-configuration-guide/basic-setup/*

**Comment by tylerkelly13** [comment]
Hi @whitsey,

There are two ways to retrieve data from the editor: using a web "form" or using JavaScript.
- To learn more about retrieving data from a web form, see: https://developer.mozilla.org/en-US/docs/Learn/Forms
- If you want to use JavaScript to extract the content from the editor, you can use the TinyMCE `getContent` API described here: https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent

Let me know if this helps. If not, let me know if you are using a Framework such as ReactJs, Lavarel and I'll pass this question to one of our developers.

Tyler

**Comment by whitsey** [comment]
I eventually found (in google) someone else who had a similar issue.  Apparently tinyMCE.triggerSave(); is what I needed.
Form is now submitting data from TinyMCE not from the original textarea.

**Comment by tylerkelly13** [comment]
Happy to hear you got it working @whitsey
