### ISSUE TITLE
I can't find what I'm looking for: plugins/premium/powerpaste.md

### ISSUE THREAD

**Issue by varaprasad7007** [tinymce/tinymce-docs#1998]
Hi there! when I'm trying to copy and paste the content/img using snipping tool it's not working.

**Comment by tylerkelly13** [comment]
Hi @varaprasad7007, thanks for the report. PowerPaste is a premium product, so I'm afraid we can't assist via GitHub. If you have a support subscription, then please contact our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new
