### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/image.md

### ISSUE THREAD

**Issue by vancouver29** [tinymce/tinymce-docs#1999]
Hello Sir and Madam,

I tried to insert an Image link with the image plugin, but it then just showed an alter image, not the image i wanted to insert. Do you have any hint for me ? 

Thank you in advance

**Comment by tylerkelly13** [comment]
Hi @vancouver29,

I need more information before I can answer your question.

What is the Image link you are trying to insert?

If it's hard to explain, try reproducing it at https://fiddle.tiny.cloud/ and share a fork of the fiddle with an example of the issue.

Tyler

**Comment by vancouver29** [comment]
Hi Tyler,

Thank you for your quick response. It is just a standard image address link. For example: `https://image.flaticon.com/icons/png/512/147/147144.png`. 

I also would like to insert an image from a local resource, Is there any documentation for that option instead of adding an image address link? 

Best regard 
vancouver

**Comment by tylerkelly13** [comment]
Thanks @vancouver29,

This page on image upload options should help: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#imageuploadoptions

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.
