### ISSUE TITLE
h1 font size is smaller than h2

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#20]
Currently `h1` font size (derived from `#` in the markdown) is smaller than `h2` (markdown `##`). See the title "Plugins" on this page:

http://localhost:4000/getting-started/working-with-plugins/

(Note, the "plugins" title on this page is redundant and I'll remove it in my current edits, but there may be instances where we do need a `h1` and it won't be styled correctly.)

**Comment by kilianc** [comment]
@r12s hey can you confirm this has been fixed when we introduced blue headings?
