### ISSUE TITLE
Fixed the tinymcenext template to include root inherited members

### ISSUE THREAD

**Issue by spocke** [tinymce/tinymce-docs#200]
I added a new moxiedoc branch with that imports the root type stuff. Couldn't get jekyll to properly build and serve the docs not sure either how the API stuff is imported. So haven't been able to test this other than that the tinymce "class" is now populated with the inherited stuff from tinymce.EditorManager and tinymce.utils.Tools not sure if this is something we want or not so it's up to you if you want to include that.

The branch is called tinymcenext-root-types and it injects the root type members into the classes so not the nicest approach.

**Comment by kilianc** [comment]
I'll look into it thanks!
