### ISSUE TITLE
I can't find what I'm looking for: demo/full-featured.md

### ISSUE THREAD

**Issue by manikant0018** [tinymce/tinymce-docs#2003]
Please let me know how can I set set ALT with images and videos for for SEO pupuse?

Thanks & Regards,

Manikant Patidar

**Comment by manikant0018** [comment]
I mean html ALT attribute

**Comment by tylerkelly13** [comment]
Hi @manikant0018 

For end users, open the image edit (or in the image insert dialog), add the ALT text to the Alternative Description field:
![image](https://user-images.githubusercontent.com/14833627/122876967-70afb900-d379-11eb-9991-9c3bab39027a.png)

Is this what you were asking about?

Tyler

**Comment by manikant0018** [comment]
I got it. Thank you so much.

Have a nice day Tyler Kelly:)
