### ISSUE TITLE
Re-generate tinymce 4.3.0 API docs from private master

### ISSUE THREAD

**Issue by spocke** [tinymce/tinymce-docs#201]
You can re-generate the API docs form the moxiecode private master. It added a few missing pieces. Not sure how I would do that with the current setup.

**Comment by kilianc** [comment]
just edit https://github.com/tinymce/tinymce-docs/blob/master/.api-version

**Comment by androb** [comment]
@kilianc There is a new editor.setMode("design") API call that is new in 4.3, that isn't showing up in the docs yet. Probably need to regenerate the API docs?

**Comment by kilianc** [comment]
you just need to edit this https://github.com/tinymce/tinymce-docs/blob/master/.api-version with 4.3.0 !

**Comment by androb** [comment]
Alright, I just did :)
