### ISSUE TITLE
I can't find what I'm looking for: advanced/editor-icon-identifiers.md

### ISSUE THREAD

**Issue by FrankConijn** [tinymce/tinymce-docs#2050]
See https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/. What would be the easiest way to swap icons? I find the Save icon not intuitive. I'd like to have the Browse icon in its place, because that pictures what is actually going to happen: upload/save to the server. I can't use NPM or Node.js.  

Furthermore, I'm very happy with Tiny MCE. Good job, folks!

**Comment by tylerkelly13** [comment]
Hi @FrankConijn ,

For such a minor change, the easiest way would be to create a custom toolbar button with the desired icon and set the `onAction` for the button to trigger the `mceSave` command.

For docs on creating a "basic" toolbar button, see: https://www.tiny.cloud/docs/ui-components/typesoftoolbarbuttons/#basicbutton
For docs on the save plugin's save command, see: https://www.tiny.cloud/docs/plugins/opensource/save/#commands

(Note: This is how the save button is created by the plugin: https://github.com/tinymce/tinymce/blob/24daa28cec95262c10ce2d8fe9bfa44f4c5fe41e/modules/tinymce/src/plugins/save/main/ts/ui/Buttons.ts#L23)

**Comment by FrankConijn** [comment]
Hi @tylerkelly13, 

Thanks for your reply, but I'm afraid I don't yet fully understand it. This is what I have now: 

    tinymce.init({
        selector: '#main',
        inline: true,
        entity_encoding : 'raw',
        plugins: 'lists link table code save',
        toolbar: 'bold italic | styleselect | link | undo redo | numlist bullist | table | code | save',
        menubar: false,
        mode : 'textareas',
        language : 'nl',
        height: 600,
        style_formats : [
            {title : 'Kop 1', block : 'h1'},
            {title : 'Kop 2', block : 'h2'},
            {title : 'Kop 3', block : 'h3'},
            {title : 'Kop 4', block : 'h4'},
            {title : 'Alinea', block : 'p'},
            {title : 'Lijst-item', block : 'li'},
            {title : 'Tabel', block : 'table'},
            {title : 'Adres', block : 'address'},
            {title : 'Citaatblok', block : 'blockquote'}
        ]
    });

Would a simple addition suffice, or would I still have to entirely rewrite the toolbar?

**Comment by tylerkelly13** [comment]
Hi @FrankConijn,

Here is an example: https://fiddle.tiny.cloud/LKhaab

Note: This example will not disable the button when there are no unsaved changes like the normal TinyMCE one, but otherwise works.

**Comment by FrankConijn** [comment]
Great! Now I got the correct exact syntax, without which it all breaks. See https://fiddle.tiny.cloud/LKhaab/4 for the hybrid toolbar I created. However, I cannot get the added Cancel button to work. Clicking it does revert the changes in the `textarea`, but does not produce the alert or the desired relocation. 

What's my mistake, if you will?

**Comment by tylerkelly13** [comment]
Awesome! looks good :slightly_smiling_face:
