### ISSUE TITLE
I can't find what I'm looking for: demo/index.md

### ISSUE THREAD

**Issue by mycatdoitbetter** [tinymce/tinymce-docs#2064]
The lib have a document (microsoft word like) doc style? i can do something like this?

**Comment by tylerkelly13** [comment]
Hi @mycatdoitbetter ,

If you're looking for a lot of functionality, have a look at the demos on this page and remove what you don't need: https://www.tiny.cloud/docs/demo/full-featured/.

If you're looking for something that looks like word or gdocs, then there is the `document` content CSS that you can modify to suit your needs: https://www.tiny.cloud/docs/configure/content-appearance/#content_css
We also have two premium skins that have a word-like appearance: "fluent" and "fabric"
- https://www.tiny.cloud/docs/enterprise/premium-skins-and-icon-packs/fluent-demo/
- https://www.tiny.cloud/docs/enterprise/premium-skins-and-icon-packs/fabric-demo/

Does this answer your question?
Tyler

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please create a new issue if this issue should not have been closed.
