### ISSUE TITLE
Add Django to Tiny MCE supported frameworks

### ISSUE THREAD

**Issue by Alexeino** [tinymce/tinymce-docs#2087]
Add Django to Tiny MCE supported frameworks

**Comment by tylerkelly13** [comment]
Hi @Alexeino 

There is currently a third-party Django integration. Here is a link to documentation on it:
https://www.tiny.cloud/docs/integrations/django/

Is this what you were looking for?
Tyler

**Comment by Alexeino** [comment]
Hi Tyler,

Waited for 1 hour still didn't receive email verification email. Can't
continue my work if it doesn't let me add.

Regards,
Alexeino

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please reopen or create a new issue if this issue should not have been closed.
