### ISSUE TITLE
Initial tech support for "getting started" with trial period

### ISSUE THREAD

**Issue by dmsac** [tinymce/tinymce-docs#2093]
I'm unclear what tech support is offered during my 30-day trial period to resolve specific issues. These include:
1) **Have registered domain, but still have "domain unregistered" alerts in the editor**.  Domain is for a Google Script webapp html page, so the domain I registered is "script.google.com".  The webapp will not have a custom domain assigned.  This warning flag, of course, is a show stopper.
2) **Cannot use "inline" mode with textarea input elements of a form.**  Need inline mode with textarea inputs. (Div elements work with inline mode, but not textarea input elements.  Standard "form" mode works with textarea elements. )
3) Formatting of tables seems unmanageable, **no table settings for gridlines** and although I set "border" in the table properties, **there are no gridlines**.  It appears that for gridlines I can set "border" cell by cell, or row by row (which are both unmanageable), but there is no option even for column properties to set vertical grid lines. A more general question related to this:
4) **Can default formatting (for tables, but also for other html elements) be modified?**  --So that table properties, including borders, cell padding, table margins (I see no option in the editor to set a margin for tables), and gridlines can all be set in a default configuration?  That would avoid struggles with ad hoc formatting problems.  (Another example would be setting a default margin for media elements--images and videos.)
5) Another issue with table content entry: **Text entered in a single line in a table cell has no p-tag, while entering a single line followed by a paragraph return encloses the original line and the subsequent line in p-tag pairs.**  The result is that the formatting of the text will be different.  So if only a single line of text is entered, it still needs to be followed by a paragraph return (CR) to keep consistent formatting--is there a setting to overcome this, as users will not automatically enter paragraph returns for single lines? (Basically, is seems that text entered in table cells needs default formatting as paragraphs.)

I hope some assistance with these issues can be provided.  Searching StackOverflow has not been very helpful with these problems.  Issues 1 and 2 are critical to using the editor.

Thank you!

**Comment by tylerkelly13** [comment]
Hi @dmsac,

To receive tech support for TinyMCE from Tiny Cloud (including during the trial), please contact https://support.tiny.cloud/ with your questions to receive priority support.

Thanks
Tyler
