### ISSUE TITLE
The class "typ" is too big on the bottom margin

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#21]
The class "typ" is too big on the bottom margin so that when two instances of the class are applied to text sitting above/below each other (i.e. within the same sentence and where the sentence has wrapped) the effect applied to the span merges.

See the 3rd para on this page where 'file' and 'edit' merge with the word 'edit' below.

http://localhost:4000/getting-started/basic-configuration/#aquicklookatmenuandmenubarcontrols

It looks like it's too big by only 1px?

**Comment by kilianc** [comment]
fixed by setting `p` `line-height`
