### ISSUE TITLE
Wrong event names on Vue Integration page

### ISSUE THREAD

**Issue by livthomas** [tinymce/tinymce-docs#2107]
> *affected page: https://www.tiny.cloud/docs/integrations/vue/*

It looks like the documentation of event bindings for Vue.js has just been copy-pasted from the React one. All events are described as they would start with `on` prefix. But they don't work this way.

The following code doesn't work:
```vue
<editor @onInit="onInit" />
```

Instead, you need to write:
```vue
<editor @init="onInit" />
```

This is the correct way of naming events in Vue so just the documentation needs to be updated.

Please, remove `on` prefix from all events names and update the example above them.

**Comment by tylerkelly13** [comment]
Thanks for letting us know @livthomas !
We've fixed this issue and the fix is now live on the docs site: https://www.tiny.cloud/docs/integrations/vue/#eventbinding
