### ISSUE TITLE
Problem with 6.0-upcoming-changes.

### ISSUE THREAD

**Issue by itsmedeepakupadhya** [tinymce/tinymce-docs#2148]
you guys have mentioned

Plugins:
- imagetools (moving to premium)

Settings:
- paste_retain_style_properties - removed in 6.0
- paste_word_valid_elements - removed in 6.0
- table_responsive_width - removed in 6.0

but you guys not mentioned if we are uding it what we have to do ?

i have purchsed power paste plugin ? so al these available in powerpaste. plz explain .

> *affected page: https://www.tiny.cloud/docs/release-notes/6.0-upcoming-changes/*

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
