### ISSUE TITLE
update all codepens to use www. instead of beta.

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#215]

**Comment by r12s** [comment]
i have reviewed the html and js code. andrew has reviewed urls in the settings. i think this is good to close @androb ?

**Comment by kilianc** [comment]
@r12s still a lot of them with

![](https://www.dropbox.com/s/mso877kf5t3l1z8/Screenshot%202015-11-25%2011.42.19.png?dl=0)

going over all of them now!

**Comment by kilianc** [comment]
done
