### ISSUE TITLE
Problem with page release-notes/release-notes510.md

### ISSUE THREAD

**Issue by Rodney6** [tinymce/tinymce-docs#2152]
Like most U.S. Companies, you do not give a price for your software, nor the platforms that it will / will not run on.

> *affected page: https://www.tiny.cloud/docs/release-notes/release-notes510/*

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.

**Comment by Rodney6** [comment]
Thank you Tyler Kelly, I have been off deck for a little while but all good now.  Thank you for your reply.
Rodney Jackson
