### ISSUE TITLE
I can't find what I'm looking for: advanced/php-upload-handler.md

### ISSUE THREAD

**Issue by rore098** [tinymce/tinymce-docs#2162]
Hi,

I am trying to set up an image handler on my TinyMce. Whenever I try to post on my localhost, it gives me a 404 error on the postAcceptor.php file and I cannot seem to figure out what is wrong with. Do I need to install php on my visual studio code or is the php file in the wrong directory?

**Comment by tylerkelly13** [comment]
Hi @rore098 ,

The PHP upload handler script requires PHP to run it. We have provided an example in javascript you prefer JS: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/#images_upload_handler

Tyler

**Comment by rore098** [comment]
Thank you, I will try and run this after I install php. Does the php file need to be in a particular directory or can it be on the same file as my tinyMce setup file

**Comment by tylerkelly13** [comment]
it can be in the same directory

**Comment by rore098** [comment]
<img width="562" alt="error1" src="https://user-images.githubusercontent.com/79815968/140577864-a084621c-cff4-469d-b384-f90e65770edb.png">
<img width="413" alt="error" src="https://user-images.githubusercontent.com/79815968/140577869-b7ccca9b-6ef3-43c6-9e14-423894184f20.png">

**Comment by rore098** [comment]
Do you know why this is happening? I made sure I have PHP installed

**Comment by tylerkelly13** [comment]
the 404 status is returned because the `postAcceptor.php` is not reachable. if the php script is in a different directory from the page you are loading TinyMCE on, then you need to provide the relative or absolute URL so it knows where it is on the server.

**Comment by tylerkelly13** [comment]
This issue has been closed due to inactivity.
Please create a new issue if this issue should not have been closed.
