### ISSUE TITLE
Problem with page plugins/opensource/link.md

### ISSUE THREAD

**Issue by CBIweb** [tinymce/tinymce-docs#2166]
I'm using the cloud version of TMCE. I want to add a Links plugin. The documentation gives me all sorts of code snippets to use, but doesn't say anything about _where_ to put them. I tried one place and I did get the Links button, but all other editor buttons were gone. I only had the Links button.

It would be of immense help if the documentation told me where these snippets go.

> *affected page: https://www.tiny.cloud/docs/plugins/opensource/link/*

**Comment by tylerkelly13** [comment]
Hi @CBIweb ,

To add the links plugin, 
1. find your tinymce configuration on the page where TinyMCE is used (the Javascript object `{}` in the `tinymce.init()` function),
2. look for `plugins` and append `link`. If you don't have a `plugins` option in your configuration, you will need to add one.

If you're still not sure, please provide more details, such as how you are using TinyMCE.

Tyler

**Comment by CBIweb** [comment]
Thanks @tylerkelly13.  Yes, I intially added this to my configuration, as instructed in the tutorial, but all it did was give me the link button while all other buttons disappeared:

```
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'link',
  menubar: 'insert',
  toolbar: 'link'
});
```

After further digging, I found [another tutorial](https://www.tiny.cloud/blog/get-started-with-tinymce-self-hosted/), in the "Customizing TinyMCE" section, that said to add this code, and it worked perfectly:

```
tinymce.init({
  selector: "#mytextarea", (I changed this changed according to my HTML)
  plugins: [
    "advlist autolink lists link image charmap print preview anchor",
    "searchreplace visualblocks code fullscreen",
    "insertdatetime media table paste",
  ],
  toolbar:
    "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
});
```

Strangely, that was in a tutorial about the self-hosted version, and it works even though I'm using the cloud version. [[shrugs]]

**Comment by tylerkelly13** [comment]
That's awesome to hear. Note that the docs apply to both self-hosted and cloud unless they state otherwise.
