### ISSUE TITLE
I can't find what I'm looking for: configure/content-appearance.md

### ISSUE THREAD

**Issue by dwoydig** [tinymce/tinymce-docs#2177]
Hi,

sorry if this is a stupid question or i missed something obvious, but is there a way to get all applied css rules from the editor?
I have to store both html and css for each page in my project, because both could change eventually, so I cannot just apply one global file to different html. 
This was an issue in the past where new pages had a different css, fonts, colors etc., but then the new layout would break the old pages that had been saved with the previous css.

**Comment by tylerkelly13** [comment]
Hi @dwoydig 

If you are not changing the styles using the [`content_css`](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) or the [`content_style`](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) options, then the default styles being applied are here: https://github.com/tinymce/tinymce-dist/blob/master/skins/content/default/content.css (it's documented under the `content_css` option).

Hope this helps.
Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.

**Comment by dwoydig** [comment]
Hi Tyler and thanks for the reply,

I know i can set the current css via the option  content_css or the
content_style when initializing the editor, i have read this section about
it in your well structured documentation. :)
However what i tried to was to get the currently applied css rules from the
editor instance itself.

Here is what i'm trying to do, maybe there is a better way to do this and i
overlooked something in the docs:

The text written inside the tiny editor must eventually be storen in a
database and converted into a PDF, and it should look the same on screen
and PDF. To do this, i save the HTML-text and the applied CSS in 2
separate fields in my DB table, and then just pass it on to the PDF writer.
I cannot use a single global styles.css because the styles typically have
things added or removed every so often, and by using the current CSS on old
HTML text some styles will break - this is a problem we had in the past.

What i was looking for was a method to get all applied styles out of the
editor, so i can pass it on to the save function.
What i'm doing right now is to pass the contents of the current.css to the
editor and as a hidden var in the save function, which i guess works, but i
was wondering if tinyMCE will internally change it's css rules at some
point and the rules from my current.css and the TinyMCE instance are not
the same anymore. Not sure if this can happen?

cheers, Daniel
