### ISSUE TITLE
I can't find what I'm looking for: quick-start.md

### ISSUE THREAD

**Issue by ahmed-abdessadki** [tinymce/tinymce-docs#2180]
To remove the message "invalid domain" the tutorial says you have to insert the api key in the script source. 

This is what my script looks like. Im not sure where to insert the api-key though?

<script src="https://cdn.tiny.cloud/1/cqnkbe346tw8rwg4ii53hk96bzdp0zrw2h7jeqmi6bm8fcc1/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

**Comment by tylerkelly13** [comment]
Hi @ahmed-abdessadki ,

You need to log in to [tiny.cloud](https://www.tiny.cloud/my-account/domains/) and add the page domain as an Approved Domain. If you have any other issues with the cloud, please contact support at https://support.tiny.cloud/

Tyler
