### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/visualchars.md

### ISSUE THREAD

**Issue by EGameiro** [tinymce/tinymce-docs#2187]
I would like to have an icon for palette color in the toolbar. 
Is it available in some way..? 
Tks.

**Comment by tylerkelly13** [comment]
Hi @EGameiro,
We have two: 
- `forecolor`: Changes the text color
- `backcolor`: Highlights the text in the selected color
For a list of all available toolbar buttons, see: https://www.tiny.cloud/docs/advanced/available-toolbar-buttons/#imagetoolsplugin

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
