### ISSUE TITLE
Backticked text is larger than the text it is inline with 

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#22]
Instances of text with the class `prettyprint` and `prettyprinted` are noticably larger than the `p` text it is inline with. 

http://localhost:4000/getting-started/basic-configuration/#aquicklookatmenuandmenubarcontrols

Suggest either bringing this class font size down 1pt, or bring the `p` sizing up one. My preference is to bring the `p` sizing up 1pt as it is difficult to read on large screens. I realize it is readable on smaller screens, especially retina displays, but data says most users are on large screens.

**Comment by kilianc** [comment]
fixed
