### ISSUE TITLE
API reference #init() should reference config page and explain better what it does

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#223]
https://www.tinymce.com/docs/missed-these-ones/api/class/tinymce.editormanager/#init

That's basically the most used method and it should hint to other resources in the docs

cc/ @r12s @androb

**Comment by tylerkelly13** [comment]
The information for `init` has been updated. The API doc now links to the docs page: https://www.tiny.cloud/docs/api/tinymce/tinymce.editormanager/#init
