### ISSUE TITLE
как интергировать этот редактор в nuxt 2 / how to integrate this editor in nuxt 2

### ISSUE THREAD

**Issue by coaperator** [tinymce/tinymce-docs#2249]
сабж.
установил "@tinymce/tinymce-vue@^3" - для vue 2
но эта обертка TinyCloud загружает TinyCloud, заставить ее использовать self-hosted версию?
нормальная, человеческая инструкция есть?

пс: пытаюсь все это завести в nuxt 2

-------------------

set "@tinymce/tinymce-vue@^3" - for vue 2
but this TinyCloud wrapper loads TinyCloud, make it use the self-hosted version?
Is there a normal, human instruction?

ps: I'm trying to put all this in nuxt 2

> *affected page: https://www.tiny.cloud/docs-4x/integrations/vue/*

**Comment by EkimChau** [comment]
Hi,

We are unfamiliar with nuxt 2, you can try these docs
https://www.tiny.cloud/docs/integrations/vue/
There are instructions for self hosted
