### ISSUE TITLE
Problem with page advanced/creating-custom-notifications.md

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#228]
### [Create Custom Notifications](advanced/creating-custom-notifications.md) issue:

Declaration and allocation of variable `editor` is not available in the code snippets.

**Comment by kilianc** [comment]
Also the API reference is incomplete and doesn't explain how it works https://www.tinymce.com/docs/api/class/tinymce.notificationmanager/#open

**Comment by tylerkelly13** [comment]
The API doc has been updated: https://www.tiny.cloud/docs/api/tinymce/tinymce.notificationmanager/#open
The page now includes a link to the details provided here: https://www.tiny.cloud/docs/advanced/creating-custom-notifications/
