### ISSUE TITLE
Problem with page plugins/noneditable.md

### ISSUE THREAD

**Issue by adoerler** [tinymce/tinymce-docs#232]
### [Noneditable Plugin](plugins/noneditable.md) issue:
The documentation states, that "noneditable_regexp" is of type string, but if you look into the code (https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/noneditable/plugin.js) the plugin expects an array.

It counts the length and loops over this lenght to apply each given regex.

If one uses the documented string value, like:
```javascript
tinymce.init({
  selector: "textarea",  // change this value according to your HTML
  plugins: "noneditable",
  noneditable_regexp: "<a href=\"(.*?)\"></a>"
});
```
the count is 20 and a regex for each character (i.e. "<", "a", " ", "h", etc.) of the string is applied, which causes the editors content to break.

To make it work, you have to provide an array as configuration value: 
```javascript
  noneditable_regexp: ["<a href=\"(.*?)\"></a>"]
```

There seems to be a check in the plugin to map 
```javascript
    nonEditableRegExps = editor.getParam("noneditable_regexp");
    if (nonEditableRegExps && !nonEditableRegExps.length) {
        nonEditableRegExps = [nonEditableRegExps];
    }
```

but, this does not respect the case of a string which indeed has a length and is therfore not converted into an array.

This happens in Version 4.3.0 and the currently reworked noneditable plugin.

Kind regards
Andreas

**Comment by tim-thatcher** [comment]
@spocke Hey Spocke, please take a look at this and let us know how to resolve it.  Thanks.

**Comment by adoerler** [comment]
Hi,

after digging further, I've found out, that the String is directly used as regular expression, see:
```javascript
content.replace(nonEditableRegExps[i], replaceMatchWithSpan)
```
I think, this one should read:
```javascript
content.replace(new RegExp(nonEditableRegExps[i], "g"), replaceMatchWithSpan)
```

And in my use case I wanted to use a regex like this:
```javascript
var nonEditableRegExps = ['(<i class="des-symbol-[a-z]+?">.</i>)'];
```

I have an created a plugin which provides an icon font (like font awesome). It generates tags like
```javascript
<i class="des-symbol-textile">a</i>)
```
The problem is, that the result of the match gets encoded before it is reinserted between the noneditable spans. That means, the symbol will no longer be shown as symbol.

For me, the content should be replaced like this:
```javascript
'<span class="' + cls + '" data-mce-content="' + editor.dom.encode(args[0]) + '">' + args[0] + '</span>'
```

I'm aware that this has nothing to do with the documentation, but somehow the documentation should describe what happens.
The regex will be applied global (if you use my suggestion from above with the g-modifier) and must return a match. Than the matched part gets encoded before it is reinserted into the body.

It would be great, if the encoding of the value could be optional (it's okay to encode it for the data-mce-content attribute, but should imho be optional for the content itself).

Kind regards
Andreas

**Comment by spocke** [comment]
I've added details to the docs around the regexp option where it needs to be an array of regexps and that each of them needs to be globally matching things. The issue with encoding needs to be reported as a github issue on the tinymce project since it's more of a bug/feature request.

I guess in theory we should decode the value back to it's original value. But in order for us to prioritize that fix and also track the progress of it please report it as a separate ticket here: https://github.com/tinymce/tinymce/issues

Closing this one since it's resolved as a PR to the tinymce-docs repo.

**Comment by adoerler** [comment]
Hi Spocke,

thanks for making the documentation more clear.
Iv'e created an issue for the other thing here: https://github.com/tinymce/tinymce/issues/2529

Kind regards
Andreas
