### ISSUE TITLE
Problem with page demo/format-custom.md

### ISSUE THREAD

**Issue by bjodoin** [tinymce/tinymce-docs#233]
### [Custom Formats Example](demo/format-custom.md) issue:

The example that runs on codepen does not work at all. Im using Chrome Version 46.0.2490.86 (64-bit) on a Mac

**Comment by kilianc** [comment]
@bjodoin would you be so kind to attach a screenshot of your error from the console or describe what happens in more detail?

**Comment by r12s** [comment]
i am unable to replicate this on tinymce.com or codepen.io. marking closed.
tested on os x 10.11.1
safari 9.0.1
firefox 42.0
chrome 46.0.2490.86

OP, please re-open if you have screenshots of the console error or describe how to replicate. thanks for reporting.
