### ISSUE TITLE
codepens not showing source code in dialog box

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#236]
* try basic example -> Tools -> source code
* try fully featured example -> Tools -> source code

This can be replicated on codepen.io as well as tinymce.com.

Console throws a CORS font error when the pen is loaded. May be related to this?

**Comment by kilianc** [comment]
I discovered a bug in CORS headers that I literally just pushed, let's see if that fixes it. ~2h to let cloudfront breath.

**Comment by kilianc** [comment]
CORS is fixed, source doesn't show up

![](https://www.dropbox.com/s/jft3qhmv23mabif/Screenshot%202015-11-26%2014.49.00.png?dl=1)

**Comment by kilianc** [comment]
cc/ @spocke ?

**Comment by spocke** [comment]
Works on my chrome at least I can't understand why it shouldn't haven't been a problem before.

**Comment by kilianc** [comment]
so if you go here: https://www.tinymce.com/docs/demo/basic-example/ and click tools -> source code you see something? Do you mind sharing a screenshot ?

**Comment by spocke** [comment]
Ehh in FF:
.codepen body textarea {
    display: none;
}

I guess that's your problem. :)

**Comment by kilianc** [comment]
Thanks @spocke !
