### ISSUE TITLE
target_list has been renamed to link_target_list

### ISSUE THREAD

**Issue by Flaburgan** [tinymce/tinymce-docs#2446]
Hello, I don't have the time to check how this documentation is generated right now, sorry for opening an issue and not a pull request, but the page https://www.tiny.cloud/docs/plugins/opensource/link/#target_list isn't up-to-date, it mentions `target_list` instead of `link_target_list`.

**Comment by lnewson** [comment]
Hi @Flaburgan, that page is for TinyMCE 5 so it is correct. You can find the TinyMCE 6 documentation here: https://www.tiny.cloud/docs/tinymce/6/link/#link_target_list
