### ISSUE TITLE
Problem with page configure/content-formatting.md

### ISSUE THREAD

**Issue by MichaelFromin** [tinymce/tinymce-docs#246]
So we have this content regarding font sizes:

https://www.tinymce.com/docs/configure/content-formatting/#fontsize_formats

If you look at the section for font size formats we tell you that you can do this but we don’t mention that you *also need to add the font size button to the toolbar*.  Setting this value without exposing the button would be useless no?

Ironically we say this:

This option allows you to override the font sizes displayed in the font size select box using a space or comma separated list of font sizes

but searching for “font size select box” shows zero hits so you can’t even search your way to the answer.  

**I would think that the sample needs to include the init changes required or has a link to a page that documents the init change needed.**

> *affected page: https://www.tinymce.com/docs/configure/content-formatting/*

**Comment by androb** [comment]
I found the answer on StackOverflow... you need to add `fontsizeselect` to the toolbar  :)

http://stackoverflow.com/questions/28132337/getting-the-tinymce-4-font-sizes-drop-down-to-set-the-font-size-in-px-instead-of

tinymce.init({
    selector: 'textarea',
    toolbar: 'fontsizeselect',
    fontsize_formats: "8px 10px 12px 14px 18px 24px 36px"
});


Mind you, nothing seems to be documented around toolbar very well:
https://www.tinymce.com/docs/configure/editor-appearance/#toolbar

**Comment by spocke** [comment]
@androb Added back the control identifiers page form the old docs. So that fontsizeselect and other controls are documented at least in a list.
