### ISSUE TITLE
Problem with page plugins/advlist.md

### ISSUE THREAD

**Issue by rameshbgm** [tinymce/tinymce-docs#253]
Hi Team,

When I paste ordered list and unordered list then the text format is not retained

ex: Paste this kind of text

1. some text
     a. some sub text
     b. sub text

Output 
1. some text
     1. some sub text
     2. sub text
a. and b. will be replaced with 1. and 2 respectively 

> *affected page: https://www.tinymce.com/docs/plugins/advlist/*

**Comment by spocke** [comment]
If this is a bug report for tinymce please report it at: https://github.com/tinymce/tinymce/issues since this is a issue tracker for the documentation.
