### ISSUE TITLE
Documentation: option "branding": incorrect clause about "required" product attribution

### ISSUE THREAD

**Issue by mikkorantalainen** [tinymce/tinymce-docs#2562]
**What is the current behavior? Describe the bug**

The documentation at https://www.tiny.cloud/docs/configure/editor-appearance/#branding says following:
> Important: Product attribution is required for free and open source users. For information on TinyMCE attribution requirements, see: Logo & attribution requirements.

The current license for open source variant of TinyMCE is MIT which definitely doesn't require any branding or endorcement. The documentation should be fixed to match the current license.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Read the current documentation at https://www.tiny.cloud/docs/configure/editor-appearance/#branding

**What is the expected behavior?**

The documentation should say something like

> Notice that while the MIT license doesn't require endorcing or advertising TinyMCE, we would prefer you to keep the branding enabled if at all possible. This would help to increase the user base of the TinyMCE which will make it easier to get more resources for future development.

instead of claiming fictional requirements.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The TinyMCE source code license was changed before release of version 6.0 but the documentation was never fixed.

**Comment by stefan6419846** [comment]
> The [currently supported versions of TinyMCE 5](https://tiny.cloud/docs/enterprise/system-requirements/#supportedtinymceversions) (versions 5.10.6 and 5.9) are [licensed](https://github.com/tinymce/tinymce/blob/release/5.10/LICENSE.TXT) under the [LGPL, version 2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html). And the LGPL has an attribution requirement

Jumping on this: Does it mean that TinyMCE 5 has been `LGPL-2.1-only`, or did it allow for `LGPL-2.1-or-later`? The files only stated `Licensed under the LGPL or a commercial license.` and the license file has been LGPL-2.1, but it is not exactly clear for me here. (`LGPL-2.1-only` and `LGPL-2.1-or-later` might look similar, but tend to have a different meaning with further usage.) I am aware that TinyMCE 6 is more clear with the MIT license, but some libraries still depend on TinyMCE 5 with no clear timeline for an upgrade.

**Comment by brian-forte** [comment]
> Does it mean that TinyMCE 5 has been LGPL-2.1-only, or did it allow for LGPL-2.1-or-later? The files only stated Licensed under the LGPL or a commercial license. and the license file has been LGPL-2.1, but it is not exactly clear for me here.

TinyMCE 5 is clearly and explicitly licensed under LGPL 2.1. It’s the license [included with the source](https://github.com/tinymce/tinymce/blob/release/5.10/LICENSE.TXT).

Arguing this means LGPL 2.1 **or later** is inferring more from the text than is either safe or warranted, given the plain meaning of the text.

> some libraries still depend on TinyMCE 5 with no clear timeline for an upgrade.

There isn’t anything we can do about third-party libraries that depend on TinyMCE 5. The core TinyMCE 6 code-base is available under an MIT license. And this license is, if anything, more permissive as to what it allows third-parties to do with the source code. (No attribution requirement, for example.)

But it is still up to the third-party to update their software to make use of TinyMCE 6.

**Comment by stefan6419846** [comment]
Thanks for the clarification. I already assumed that `LGPL-2.1-only` is indeed the desired expression, but asking anyway does not really hurt ;)

And I am aware about the third-party stuff as well - I just wanted to provide some rationale on why I am still asking about the old TinyMCE 5 releases.
