### ISSUE TITLE
When should we include 4.3 changes

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#26]
@kilianc @andrew I noticed a 4.3 plugin `codesample` in the 4.2 docs. I think we should branch 4.2 into 4.3 and put changes in the new branch.

As to when should this happen? Before Wednesday obviously :-)

**Comment by androb** [comment]
IMHO we should just include them into master.

I've assigned an issue to Joakim to review the codesample plugin. I don't know that any other changes in 4.3 require changes to the docs.

**Comment by r12s** [comment]
Agreed that new 4.3 content is being merged into master. No version branching for docs on this update. Marking closed.
