### ISSUE TITLE
Dojo integration doc

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#260]
Create a page describing the project.

The project info can be found at http://blog.caitlinmarkert.com/2015/12/04/tinymce-4-widget-for-dojo-1-10/

We should notify Caitlin and tweet about it.

**Comment by androb** [comment]
@caitlinmarkert - fyi we intend to add a doc to the main TinyMCE site about your integration

**Comment by caitlinmarkert** [comment]
That's awesome! Go for it. I hope people find it useful. Thank you, I
appreciate it!
