### ISSUE TITLE
Problem with page configure/content-filtering.md

### ISSUE THREAD

**Issue by kappaluppa** [tinymce/tinymce-docs#261]
> *affected page: https://www.tinymce.com/docs/configure/content-filtering/*

I cannot find where to add this code. how does it affect the advanced options? so confusing!!! I'm just trying to add tables!

**Comment by r12s** [comment]
Thanks @kappaluppa I need more information to be able to resolve this issue. Which content-filtering option are you referring to?

**Comment by r12s** [comment]
Given the time elapsed since my reply I'm marking this closed.
