### ISSUE TITLE
Documentation out of date on website [Laravel]

### ISSUE THREAD

**Issue by allw1994** [tinymce/tinymce-docs#2638]
**What is the current behavior? Describe the bug**

Documentation calls to use Laravel mix, this is no longer included as default and instead should use vite.

https://www.tiny.cloud/docs/tinymce/6/laravel-composer-install/

**Comment by TheSpyder** [comment]
Transferred to docs. Ping @brian-forte

**Comment by brian-forte** [comment]
[Adam](https://github.com/allw1994),

Thank you for the report.

An internal task has been setup and scheduled to address this issue in the next documentation release.

Regards,

@brian-forte,
Senior Technical Writer
[tiny.cloud](https://tiny.cloud/)
