### ISSUE TITLE
Adding styling for toolbar and menubar associations in plugins

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#27]
@kilianc we need to add css for any plugins that have toolbar and menubar control associations. Currently there is a comment in any plugins with these associations, so we need to resolve how we're going to write this in the markdown.

**Comment by kilianc** [comment]
@r12s you mean like badges? cc/ @lucaorio

**Comment by kilianc** [comment]
Why is this a bug? I probably misunderstood the issue then

**Comment by r12s** [comment]
Not a bug. @kilianc @lucaorio Yes more like badges. The way I resolved the circular nature of the control -> plugins nav structure was to remove controls and embed the association into the relevant plugin or config option.

So we need some sort of graphical representation highlighting, for example, that a plugin adds a menu item and/or a toolbar button. The information within the section states what that control is, so we don't need to repeat it in the "badge".

Kilian, we currently have comments as placeholders, so we need to decide on the correct structure. Perhaps add it to the meta section and have your script/s so their magic?

**Comment by lucaorio** [comment]
Css and design already provided, Kilian will push the changes in few minutes!
