### ISSUE TITLE
Problem with page api/class/tinymce.editormanager.md

### ISSUE THREAD

**Issue by MichaelFromin** [tinymce/tinymce-docs#273]
The get() method's description is:

Returns a editor instance by id

I believe you want 

Returns **an** editor instance by id

> _affected page: https://www.tinymce.com/docs/api/class/tinymce.editormanager/_

**Comment by tylerkelly13** [comment]
Resolved. 
API docs updated and live: https://www.tiny.cloud/docs/api/tinymce/tinymce.editormanager/#get
