### ISSUE TITLE
Table cells have a leading space when entering data (IE Only)

### ISSUE THREAD

**Issue by AdamJorgenson** [tinymce/tinymce-docs#275]
Tables cells have a leading space when entering data (IE Only)

1 - Insert a table and begin entering data in a cell
Expected Result: Data is entered as typed
Actual Result: IE has a leading space in the table cell. The workaround is to backspace before entering any data.

**Comment by Afraithe** [comment]
How is this related to the documentation?

**Comment by AdamJorgenson** [comment]
It is not. My apologies, can you point me to the correct page for reporting
product issues?

Adam Jorgenson
