### ISSUE TITLE
Problem with page advanced/migration-guide-from-3.x.md (addToTop)

### ISSUE THREAD

**Issue by davidemoro** [tinymce/tinymce-docs#276]
Missing info about how to migrate addToTop events.

> _affected page: https://www.tinymce.com/docs/advanced/migration-guide-from-3.x/_

**Comment by davidemoro** [comment]
Having a look at the compat3x plugin it seems that addToTop is the same for add now, can you confirm please?

**Comment by tylerkelly13** [comment]
Looking at the compat3x plugin, addToTop was set to an empty function.
The function appears to have been deprecated in TinyMCE version 4.

**Comment by tylerkelly13** [comment]
Given the age of this issue and the work required to fix, this issue will now be closed.
Please reopen or create a new issue if this issue should not have been closed.
