### ISSUE TITLE
Problem with page advanced/migration-guide-from-3.x.md (init plugin & tinymce.create)

### ISSUE THREAD

**Issue by davidemoro** [tinymce/tinymce-docs#277]
No more `tinymce.create`on v4?

> _affected page: https://www.tinymce.com/docs/advanced/migration-guide-from-3.x/_

**Comment by tylerkelly13** [comment]
@davidemoro `tinymce.create` is documented for TinyMCE 4 & 5:
TinyMCE 4: https://www.tiny.cloud/docs-4x/api/tinymce/root_tinymce/#create
TinyMCE 5: https://www.tiny.cloud/docs/api/tinymce/root_tinymce/#create
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
