### ISSUE TITLE
Change event only fires first time with multiple editors (Most recent Version)

### ISSUE THREAD

**Issue by Ttante** [tinymce/tinymce-docs#278]
here's my code:
tinymce.init({
    selector: '#Description',
    setup : function(ed) {
        ed.on('change', function(e) {
            console.log('the content '+ed.getContent());
        });
    }
});

This works the first time but does not fire after that until i press an arrow key.
I've looked everywhere for a fix but I've found nothing. At this point i'll be switching to an older version.

**Comment by r12s** [comment]
Hi Tyler - would you mind posting this in the TinyMCE repo at https://github.com/tinymce/tinymce/issues so the devs can look into the issue? Thanks in advance.

**Comment by Ttante** [comment]
Ok will do thank you!
