### ISSUE TITLE
Problem with page plugins/code.md

### ISSUE THREAD

**Issue by aaronCL84** [tinymce/tinymce-docs#280]
How I could to pass the text of the "code" to a other div (in the same page) every time I press a key in the textarea tiny?

I think Im trying everything but I cannot do it. Sorry for my English 
Thank you

> *affected page: https://www.tinymce.com/docs/plugins/code/*

**Comment by r12s** [comment]
Hi @aaronCL84 best place to ask this question is the community forum.

http://archive.tinymce.com/forum/viewforum.php?id=1

Marking closed as not a problem with docs.
