### ISSUE TITLE
Problem with page api/class/tinymce.dom.domquery.md

### ISSUE THREAD

**Issue by nikolas** [tinymce/tinymce-docs#285]
The documentation for `DomQuery.hasClass()` is incorrect. This function takes two arguments, not one. See the source:
https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/dom/DomQuery.js#L101

https://www.tinymce.com/docs/api/class/tinymce.dom.domquery/#hasclass

The first argument is the node on which to check the class name, and the second argument is the class name.

> _affected page: https://www.tinymce.com/docs/api/class/tinymce.dom.domquery/_

**Comment by nikolas** [comment]
Actually, this function is meant to be called like this: `DomQuery(node).hasClass('someClass')`, but I didn't find that obvious from the the documentation. Maybe we could include some exampled in it?

**Comment by tylerkelly13** [comment]
The documentation for `DomQuery.hasClass()` has been updated and now includes an example: https://www.tiny.cloud/docs/api/tinymce.dom/tinymce.dom.domquery/#hasclass
