### ISSUE TITLE
Problem with page integrations/jquery.md

### ISSUE THREAD

**Issue by Manachi** [tinymce/tinymce-docs#2867]
> *affected page: https://www.tiny.cloud/docs/integrations/jquery/*

There is a link on this page [Official TinyMCE jQuery component](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/js/JqueryIntegration.js) which is broken and goes to a 404.

**Comment by brian-forte** [comment]
@Manachi,

FYI: the link on the [jQuery integration page](https://www.tiny.cloud/docs/integrations/jquery/) of the TinyMCE 5.x documentation has been corrected.

It now points to [the jQuery javascript component](https://github.com/tinymce/tinymce/blob/release/5.10/modules/tinymce/src/core/main/js/JqueryIntegration.js) in the TinyMCE 5.x source.

**Comment by zonesql** [comment]
@brian-forte - many thanks!

**Comment by Manachi** [comment]
@brian-forte - many thanks! 🙏
