### ISSUE TITLE
Problem with page plugins/colorpicker.md

### ISSUE THREAD

**Issue by rswhite** [tinymce/tinymce-docs#288]
Hi,

I have included the color picker but nothing is happening, It adds the text color as expected but only lists predfined options. It has not added in an ability to create custom colors.

Richard

> *affected page: https://www.tinymce.com/docs/plugins/colorpicker/*

**Comment by r12s** [comment]
@rswhite please ask this question in the community forum.

http://archive.tinymce.com/forum/viewforum.php?id=1
