### ISSUE TITLE
Problem with page api/class/tinymce.ui.factory.md

### ISSUE THREAD

**Issue by lakshme** [tinymce/tinymce-docs#294]
> *affected page: https://www.tinymce.com/docs/api/class/tinymce.ui.factory/*

This is not really an issue, but a suggestion.. I was looking for help on tinymce.ui.Factory.create.
All I got was :

"Creates a new control instance based on the settings provided

Parameters

settings (Object) - Name/Value object with items used to create the type."

This is not really helpful, since there is no information on what kinds of values the settings object accepts. Examples and more details in this regard would really help.

**Comment by r12s** [comment]
Hi @lakshme I agree and this is an issue we're discussing very actively. There is one example in the old version of the docs http://archive.tinymce.com/wiki.php/api4:method.tinymce.ui.Factory.create but all this really highlights is the need for examples in our API docs.

We can and will do better. I'm marking this closed as it won't be immediately fixed and I've made a note to discuss with the product and docs teams (which I do regularly anyhow). Thanks again!
