### ISSUE TITLE
table_default_container

### ISSUE THREAD

**Issue by cochran1832** [tinymce/tinymce-docs#297]
Could you add a "table_default_container" to the options of the table plugin.  There are instances where it is necessary to contain a table within a div or paragraph.  We should be able to define a block element as the container and then add classes, styles, attributes, ect. to the container.  I get there are work-arounds for this but it would be helpful to have a container added upon creation.

**Comment by r12s** [comment]
Thanks @cochran1832 please post this in https://github.com/tinymce/tinymce 

Marking closed as this isn't an issue with documentation.
