### ISSUE TITLE
Problem with page demo/basic-example.md

### ISSUE THREAD

**Issue by bomiredydnaresh** [tinymce/tinymce-docs#298]
Hi this is naresh,
I am trying to add new image from our desktop folder to the editor. But the image is not showing.It is showing blank.
![image](https://cloud.githubusercontent.com/assets/17196072/13005299/15b3784a-d1a7-11e5-9638-524d56274892.png)

> *affected page: https://www.tinymce.com/docs/demo/basic-example/*

**Comment by r12s** [comment]
Hi @bomiredydnaresh my apologies for not responding sooner. This isn't an issue with the docs (but I'm guessing trying to load a file using `file:///`).

btw, if you want to test the image tools functionality, use this demo: https://www.tinymce.com/docs/demo/image-tools/

Ping the community forum if you need help with your specific query http://archive.tinymce.com/forum/viewforum.php?id=1. All the best and thanks for using TinyMCE!
