### ISSUE TITLE
Write codesample plugin docs

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#30]
This needs to be documented:
https://github.com/tinymce/tinymce-docs/blob/master/plugins/codesample.md

**Comment by r12s** [comment]
I had a go at this, see commit 0f9eb7b.

**Comment by r12s** [comment]
@Afraithe when you have a moment, please advise any key/value options available, default states (e.g. dialog box dimensions) and i'll update the text and close this issue. thanks! cc/ @tim-thatcher

**Comment by r12s** [comment]
Email query with the dev team, will update upon response.

**Comment by r12s** [comment]
there are currently no exposed configuration options, e.g. codesample_dialog_height. there is another issue open on the entry for this plugin. marking closed.
