### ISSUE TITLE
Problem with page plugins/contextmenu.md

### ISSUE THREAD

**Issue by neonexus22** [tinymce/tinymce-docs#301]
I am using nanospell with tinymce. I have a right click menu appearing whenever there is a word that is not in our wordlist. I want to change the font family of the menu. when i add "\<b\>word\</b\>" to the right click menu, it doesnot render the html tag. How can i do that? Please help.

**Comment by Afraithe** [comment]
This isn't really related to the tinymce documentation itself.

If you have a bug report please file it in the proper project. If you have general question, try asking in the forums on http://archive.tinymce.com

If your a client with a support contract, use the proper Ephox support channels.

Thank you.
