### ISSUE TITLE
Problem with page api/class/tinymce.editor.md

### ISSUE THREAD

**Issue by sebflaesch** [tinymce/tinymce-docs#302]
What is the "dirty" editor event used for?

> *affected page: https://www.tinymce.com/docs/api/class/tinymce.editor/*

**Comment by r12s** [comment]
@sebflaesch please ask questions like this over in the community forum.

http://archive.tinymce.com/forum/viewforum.php?id=1

**Comment by sebflaesch** [comment]
By this question I wanted to report that the documentation is not describing well the "dirty" event.
"Fires when the editor becomes dirty"
What means "dirty"?
I assume it's when the user modifies the text, the editor is "dirty" until text is saved somehow...?
