### ISSUE TITLE
Problem with page configure/content-filtering.md

### ISSUE THREAD

**Issue by anden259** [tinymce/tinymce-docs#303]
The text and example for "valid_classes" is the same as for "valid_styles". I'm trying to allow all classes for all elements, but using the information in the documentation it is not possible. (Maybe it is impossible, but the doc's are still incorrect?)

> *affected page: https://www.tinymce.com/docs/configure/content-filtering/#valid_classes*

**Comment by r12s** [comment]
Thanks @anden259 this has been fixed in merge 304.

Marking closed.
