### ISSUE TITLE
Supported TinyMCE versions - End of support date info not available

### ISSUE THREAD

**Issue by indigoxela** [tinymce/tinymce-docs#3033]
**Documentation/Product Version**

TinyMCE v6 / Supported TinyMCE versions

**Links to Page(s) affected**

https://www.tiny.cloud/docs/tinymce/6/support/#supported-versions-and-platforms

**Description of Issue**

TinyMCE version 6.8.x is out since November, but the release info (End of support) doesn't seem to be published, yet.

**Suggested Fix**

While not urgent, it would be nice, if the info were easy to find, which currently isn't the case.

I hope, this is the correct issue queue for that report.

**Comment by TheSpyder** [comment]
The PR wasn't worded correctly to automatically close this. It has been fixed.
