### ISSUE TITLE
Problem with page demo/basic-example.md

### ISSUE THREAD

**Issue by moinulmithu** [tinymce/tinymce-docs#305]
I can't render text editor content with formcollection.serialize method in asp.net mvc 5 project. Can anyone please help me in this regards????
> *affected page: https://www.tinymce.com/docs/demo/basic-example/*

**Comment by r12s** [comment]
@moinulmithu please direct this query to the TinyMCE Community forum, where the community may be able to help you out. http://archive.tinymce.com/forum/viewforum.php?id=1

Marking closed, not a documentation issue.

**Comment by moinulmithu** [comment]
Thanks @r12s I have already solved my problem.
