### ISSUE TITLE
removeformat toolbar button

### ISSUE THREAD

**Issue by MichaelFromin** [tinymce/tinymce-docs#306]
I don't seem to be able to find any documentation on this toolbar option but its part of some our demos on the TinyMCE site. 

I would expect to be able to search for Clear Formatting or removeformat but both come up empty in the documentation.

**Comment by r12s** [comment]
@MichaelFromin can you point me to the relevant document in the old docs so that I can understand whether we have a search issue or a missing documentation issue.

**Comment by MichaelFromin** [comment]
@r12s I don't know that this was on the old site either - I believe this falls under "missing"

**Comment by r12s** [comment]
@Afraithe let's pick this one up in Slack, might be missing in the general docs.

**Comment by jayarjo** [comment]
Seems to be added, as of now. Can be found on the page of [commands](https://www.tinymce.com/docs/advanced/editor-command-identifiers/) and on the page of [controls](https://www.tinymce.com/docs/advanced/editor-control-identifiers/).

I will close this.
