### ISSUE TITLE
MoxieManager docs link "integrate with tinymce" causes issues

### ISSUE THREAD

**Issue by Afraithe** [tinymce/tinymce-docs#308]
The link to "integrate with tinymce" adds some google tracking stuff that interferes with the wiki on moxiemanager so the link will be blank.

**Comment by r12s** [comment]
@Afraithe which link?

**Comment by r12s** [comment]
bump @Afraithe

**Comment by androb** [comment]
The addition of the parameters helps us to track visitors between sites as
the same visitor.

We end up double-counting visitors if we do not use this GA plugin.

Given this is less than 6,000 sessions per month this might be acceptable?

We are left with the choice to:
- fix the wiki, or
- double count sessions

what is the level of effort to fix the wiki? I am leaning towards turning
off the GA plugin for moxiemanager.com and just double-counting the
visitors.

**Comment by Afraithe** [comment]
https://www.tinymce.com/docs/plugins/moxiemanager/

**Comment by Afraithe** [comment]
I might be able to look into that for the wiki, but not sure when I can sqeeze that in.

**Comment by androb** [comment]
@Afraithe - when do you think we can look at this? It is my preference to leave the GA plugin in place if possible.

cc @r12s

**Comment by Afraithe** [comment]
Fixed.

**Comment by androb** [comment]
Thank you!
