### ISSUE TITLE
Problem with page api/class/tinymce.windowmanager.md

### ISSUE THREAD

**Issue by davidsusu** [tinymce/tinymce-docs#311]
Please write a real documentation for `WindowManager::open`, which includes all of the available settings of the `param` argument (with complete and usable descriptions); and describe all available control types of the `body` option (with complete and usable descriptions).

Many thanks, David

> _affected page: https://www.tinymce.com/docs/api/class/tinymce.windowmanager/_

**Comment by r12s** [comment]
Thanks @davidsusu improving the API reference is a priority. We're currently determining the best way to do this. I can't promise a timeline on this just yet but do know it's been worked on.

**Comment by cjdubois10** [comment]
Hi @davidsusu it looks like this doc has been fixed. Take a look at the new windowManager api reference in the TinyMCE docs. This page has a list of all methods associated with windowManager. Each is paired with a summary, definition, and examples. The link is: https://www.tinymce.com/docs/api/tinymce/tinymce.windowmanager/

This issue should be closed.

**Comment by davidsusu** [comment]
@cjdubois10 I see this label, still:

> params (Object) - Options like title, file, width, height etc. 

If `params` is documented somewhere else, there should be a link here.

**Comment by tylerkelly13** [comment]
The TinyMCE WindowManager API docs have been updated: https://www.tiny.cloud/docs/api/tinymce/tinymce.windowmanager/#open
Note: params was incorrectly documented, the options are passed as part of `args`. A link has been added to the page pointing to the required information.
