### ISSUE TITLE
Problem with page demo/full-featured.md

### ISSUE THREAD

**Issue by TuningGuide** [tinymce/tinymce-docs#312]
Hi, me as a developer would like to have an example in the docs which shows all core buttons and available tinymce plugins in one demo.

Like: http://codepen.io/anon/pen/LNZJxz

What do you think about adding it beneath the full-featured Version as ultra-featured version? ;)

> *affected page: https://www.tinymce.com/docs/demo/full-featured/*

**Comment by r12s** [comment]
Hi @TuningGuide that's pretty cool, thanks. I want to keep examples reasonably specific and so won't add the pen to the docs. (btw, the editor breaks the pen's container when embedded).

But since it's pretty cool I'll share your work on social media. Cool?

**Comment by TuningGuide** [comment]
Sure. Regards
