### ISSUE TITLE
Problem with page api/class/tinymce.editor.md

### ISSUE THREAD

**Issue by rbecheras** [tinymce/tinymce-docs#314]
The links "Contribute to this page" in the top right of the docs pages are broken 

> https://github.com/tinymce/tinymce-docs/tree/master/api/class/tinymce.editor.md

And the links "helping us out" in "Well, that's awkward . Would you mind opening an issue or helping us out ?" are broken too - its the same :

> https://github.com/tinymce/tinymce-docs/tree/master/api/class/tinymce.editor.md
> 
> _affected page: https://www.tinymce.com/docs/api/class/tinymce.editor/_

**Comment by r12s** [comment]
Thanks @rbecheras that sure is awkward :-) will get these fixed asap, appreciate you raising the issue.

cc/ @kilianc

**Comment by spocke** [comment]
This one is fixed. The contribution link is now not available on the tinymce api pages. If you want to contribute to those you need to PR to the tinymce main repo since the API docs are generated from the source code. Thanks for reporting this.

**Comment by rbecheras** [comment]
Got it, thanks!
