### ISSUE TITLE
Problem with page configure/file-image-upload.md

### ISSUE THREAD

**Issue by atreyu5** [tinymce/tinymce-docs#321]
Hello, 

I don't manage to get the Image Tools plugin to actually upload the images to the server. I upload images with the jbimages plugin with no problem. But when a picture is edited with the Image Tools, although there's the uploading bar, which gets to 100%, it seems that it's only uploaded as a blob. The page calls the tinymce.activeEditor.uploadImages() function when submitting the form data, but it doesn't work. 

I use the 'postacceptor.php' file from the example (defined in 'images_upload_url') and the 'images_upload_base_path' is defined as well. 

The files are not uploaded to the server, and the img src remains a blob.

What could the problem be?
Thanks!

> *affected page: https://www.tinymce.com/docs/configure/file-image-upload/*

**Comment by r12s** [comment]
Hi @atreyu5 please ask this question on the community forum http://archive.tinymce.com/forum/viewforum.php?id=1
