### ISSUE TITLE
Document `target` option

### ISSUE THREAD

**Issue by lucthev** [tinymce/tinymce-docs#322]
Hey all! First off, thanks for the work you've put into the TinyMCE docs — they're a pleasure to read.

I was looking for a way to initialize an editor using an element directly instead of a CSS selector — I browsed through the source and came across the [target option][], but unfortunately it appears to be undocumented. Would there be interest in documenting this option, or is there a reason it's undocumented? I'd be happy to contribute the documentation, if there's interest.

[target option]: https://github.com/tinymce/tinymce/blob/47b6e614dd2a897a138594c545d0c2cabb731405/js/tinymce/classes/EditorManager.js#L340-L341

**Comment by r12s** [comment]
Hi @lucthev first up, thanks for the kind words re the docs. It's a work in progress and there's a long way to go yet :-)

I'd appreciate your contribution to the docs. Let's firstly take a look at where this would fit in the current structure and we can proceed from there. Sound reasonable?

**Comment by lucthev** [comment]
Sounds like a plan! Would the [Integration and setup docs](https://www.tinymce.com/docs/configure/integration-and-setup/) be a good place to document this option? The documentation for the similar `selector` option also lives on that page.
