### ISSUE TITLE
Problem with page demo/inline.md

### ISSUE THREAD

**Issue by mewiki** [tinymce/tinymce-docs#323]
ei.js:1 GET https://codepen.io/tinymce/embed/YydQoj?height=660&theme-id=0&slug-hash=YydQoj&default-tab=result&user=tinymce net::ERR_SSL_BAD_RECORD_MAC_ALERT

> *affected page: https://www.tinymce.com/docs/demo/inline/*

**Comment by r12s** [comment]
This was an issue with Codepen and has been resolved. Thanks for letting us know.
