### ISSUE TITLE
Problem with page integrations/angularjs.md

### ISSUE THREAD

**Issue by marvertin** [tinymce/tinymce-docs#326]
This example does not work. The editor has no toolbar and no menu unless you initialize it using explicit initialization using "tinymce.init".

https://plnkr.co/edit/CkUhd5XIkzAAgxJxLuPS?p=preview

**Comment by lnewson** [comment]
Sorry we've only just got back to this, but I had a look at your plunker and it's missing the `ui.tinymce` module in the dependency list in app.js. So if you change
```
var app = angular.module('plunker', [ ]);
```
to
```
var app = angular.module('plunker', [ 'ui.tinymce' ]);
```
then it works as expected: https://plnkr.co/edit/5JAwELqgd0zzmPqzm9J4?p=preview
