### ISSUE TITLE
Confirm fix_list_elements config option default state

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#328]
Client services note:

> The fix_list_element setting https://www.tinymce.com/docs/configure/content-filtering/#fix_list_elements documentation says that this setting is disabled by default but the Default Value shown is `True`. That needs to be changed to `False`.

**Comment by tylerkelly13** [comment]
https://www.tiny.cloud/docs/configure/content-filtering/#fix_list_elements has been updated.
the Default value is documented as `false`.
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
