### ISSUE TITLE
Problem with page enterprise/paste-from-word.md

### ISSUE THREAD

**Issue by Anenth** [tinymce/tinymce-docs#335]
PowerPaste in not available on cdn.js, How to use this plugin if the tinymce is imported from cdn.js

> *affected page: https://www.tinymce.com/docs/enterprise/paste-from-word/*

**Comment by r12s** [comment]
Hi @Anenth. PowerPaste is an enterprise plugin. Please ping the support team directly.
https://support.ephox.com/home
