### ISSUE TITLE
Please add documentation on how to bind event dispatchers / handlers to various tinymce events

### ISSUE THREAD

**Issue by dsifford** [tinymce/tinymce-docs#339]
I'm looking to add a custom event dispatcher to when tinymce gets removed and can't figure out how this is done. 

Any help is appreciated.

**Comment by dsifford** [comment]
I tried the following but it spit back a depreciation warning: 

```js
tinyMCE.activeEditor.onRemove.add(x)
```

where `x` is just `function(e) { console.log(e) }`

**Comment by dsifford** [comment]
Alright so apparently that DOES work with non-depreciated events...

Can you clarify what event I need to listen for for the scenario where a user switches from "text" to "visual" editor? Not able to find anything that fits that bill.

**Comment by dsifford** [comment]
This seems to be able to tell me the correct info, but how do I get this info immediately once it changes:

```js
tinyMCE.activeEditor.isHidden()
```

**Comment by dsifford** [comment]
Knock, knock. Anyone home?

**Comment by MagicMicah** [comment]
This would probably be a question best addressed in the tinymce Community: https://community.tinymce.com/. Also it appears that the ticket that @dsifford needed this information for has been closed. Can we close this ticket?
