### ISSUE TITLE
Problem with page advanced/php-upload-handler.md

### ISSUE THREAD

**Issue by jwatte** [tinymce/tinymce-docs#340]
> _affected page: https://www.tinymce.com/docs/advanced/php-upload-handler/_

The example script does not demonstrate best practices for secure web apps.

The documentation returns 500 errors for bad input data, which should be 400 errors.

The code also does a security bad: It uses a blacklist for "unallowed" characters. This lets attackers get various kinds of data by the blacklist through creative use of Unicode and UTF-8. The most secure way of making sure file names are OK is to replace all characters that are not a-z, A-Z, or 0-9 with a specific character (such as underscore _ or dash -) or to generate the image name using some other means (random, serial, SHA hash, etc.)
Yes, this will mangle localized image names. The problem of allowing "sane" Unicode names, yet avoiding "tricky" code points, is very complex, and requires more work, so it may not fit in this example. But, given that people will copy this sample into real web servers, strict-whitelist seems like a reasonable stance.

**Comment by jayarjo** [comment]
I'm afraid that what you suggest here is beyond the scope of that example.
