### ISSUE TITLE
Example code in docs for file_picker_callback doesn't work

### ISSUE THREAD

**Issue by anabright** [tinymce/tinymce-docs#3505]
I'm trying to implement a media file picker so that I can upload a video to a server and then have TinyMCE embed the video. Similar to how it works for images when `images_upload_url` is specified.
 
I was trying to reuse [the code provided in the interactive example in the docs](https://www.tiny.cloud/docs/tinymce/latest/image/#interactive-example) for the `file_picker_callback` option:

```
file_picker_callback: (cb, value, meta) => {
    const input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');

    input.addEventListener('change', (e) => {
      const file = e.target.files[0];

      const reader = new FileReader();
      reader.addEventListener('load', () => {
        /*
          Note: Now we need to register the blob in TinyMCEs image blob
          registry. In the next release this part hopefully won't be
          necessary, as we are looking to handle it internally.
        */
        const id = 'blobid' + (new Date()).getTime();
        const blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        const base64 = reader.result.split(',')[1];
        const blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        /* call the callback and populate the Title field with the file name */
        cb(blobInfo.blobUri(), { title: file.name });
      });
      reader.readAsDataURL(file);
    });

    input.click();
  },
```

But when `input.click()` is executed, instead of opening the file browser I see this in the console:
`File chooser dialog can only be shown with a user activation.`

This example code seems to be quite old because it seems it's no longer allowed to programmatically open a file chooser via JS.

Would it be possible to update the docs with an example that works?

Or can someone provide a way (or point me in the right direction) to do the following:
1. When clicking on Insert > Media
2. Show a file picker 
3. When selecting a video, upload it to a server
4. Insert the video URL in the Insert/Edit media dialog

So, basically I'd need something similar to `images_upload_url` but for media.

Thanks,

Ana

**Comment by TheSpyder** [comment]
If you're debugging it would certainly block the click due to lack of user activation, but either way I'm glad you figured it out. I've transferred this to the docs repo before closing it.
