### ISSUE TITLE
Problem with page api/class/tinymce.editorcommands.md

### ISSUE THREAD

**Issue by benvh** [tinymce/tinymce-docs#354]
How about adding a list of available commands?

> *affected page: https://www.tinymce.com/docs/api/class/tinymce.editorcommands/*

**Comment by whoisdis** [comment]
+1

Makes it hard to use queryCommandValue() as well without a list of available commands...

**Comment by jayarjo** [comment]
We maintain a list of currently exposed commands here: [Editor Command Identifiers](https://www.tinymce.com/docs/advanced/editor-command-identifiers/).
