### ISSUE TITLE
Problem with page integrations/angularjs.md

### ISSUE THREAD

**Issue by sidlack** [tinymce/tinymce-docs#358]
When I try loading my site in Google Chrome it stops angular from loading content but it works fine in firefox?
This is the error I get in the console:
Refused to execute script from 'https://raw.githubusercontent.com/angular-ui/ui-tinymce/master/src/tinymce.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by fyrkant** [comment]
This does not seem to be a problem with the documentation, so I am closing this. Please open an issue on the [correct repo](https://github.com/tinymce/tinymce/issues) if you still have a problem you need help with.
