### ISSUE TITLE
Problem with page configure/file-image-upload.md

### ISSUE THREAD

**Issue by stevehanson** [tinymce/tinymce-docs#359]
I have unsuccessfully been trying to figure out how to implement image uploading in TinyMCE and am just putting out a friendly request that the documentation be updated to be more clear. 

I am looking for a workflow like the following:
- Click Image Upload button on toolbar
- Browse to file on computer and select
- Image inserted into editor
- Upload to the server happens at some point before saving the content. Server returns the full URL which is saved in the content.

I've seen some pages in the docs that seem to touch on this type of functionality, but they don't provide enough context to figure out how to actually use these features. I would try to help improve the docs, but I unfortunately still don't understand the topic they cover.

> _affected page: https://www.tinymce.com/docs/configure/file-image-upload/_

**Comment by jayarjo** [comment]
While we provide some hooks that allow developers to write local file pickers, we do not bundle any implementations with TinyMCE. There's a commercial plugin however [MoxieManager](http://www.moxiemanager.com/), that can be purchased separately.
