### ISSUE TITLE
Problem with page api/class/tinymce.ui.slider.md

### ISSUE THREAD

**Issue by Cascuna** [tinymce/tinymce-docs#362]
> *affected page: https://www.tinymce.com/docs/api/class/tinymce.ui.slider/*

whole api doc doesnt seem to be working

**Comment by r12s** [comment]
apologies @Cascuna the url scheme changed for some api docs. correct page is: 

https://www.tinymce.com/docs/api/tinymce.ui/tinymce.ui.slider/
