### ISSUE TITLE
API docs missing a ton of stuff

### ISSUE THREAD

**Issue by Afraithe** [tinymce/tinymce-docs#370]
So we have had complaints about the API docs being worse now that on the new website.

First we had the problem that only some of the content was ported over, missing all the examples.

Looking further at the docs, there are parts greatly missing.

Compare the contents.
http://archive.tinymce.com/wiki.php/api4:class.tinymce.ui.Menu
https://www.tinymce.com/docs/api/class/tinymce.ui.menu/

**Comment by androb** [comment]
I presume this is a problem with the auto-generation of docs?

**Comment by androb** [comment]
Upon further investigation this is a problem in Moxiedoc. There is a private repo of Moxiedoc at https://github.com/ephox/moxiedoc/compare/tinymcenext-root-types

@spocke and @spocke

**Comment by r12s** [comment]
@Afraithe with the updates you and Spocke made, can we close this issue? Or is there still more to do? If so, perhaps we should open issues on specific bugs?
