### ISSUE TITLE
Overview of TinyMCE Docs

### ISSUE THREAD

**Issue by Barent** [tinymce/tinymce-docs#373]
I was requested to conduct a review of the documentation and below are my initial findings. Please review and provide feedback at your convenience.

Overview

After reviewing the documentation the main issue I found was a consistent use of awkward grammar. Specifically, this was manifested in a tendency to include items that would distract the reader from the purpose of a passage. This issue was most prevalent in the getting started section, but diminished as I progressed through the documentation. There were some other areas where I would suggest improvement.

Improvement Ideas

A possible major improvement that I could see would be to integrate the getting started section with the examples and demo section. This would be very helpful to new users as they could see the live code via codepens and it would help to solidify the concepts being discussed in the getting started section. Even though I was familiar with codepen I found myself setting up a basic node environment to tinker. This was simply because it did not occur to me to use codepen.

Another possible improvement could be the addition of a pre-requisite section. This could include an overview of the technologies a reader should be familiar with in order to work with TinyMCE. It could also contain a basic explanation of environments where you could use TinyMCE (codepen, localdev, ect).

Conclusions

Overall the documentation was better than originally described to me. I did not find myself confused about the product and it seemed to offer a great deal of depth. With the additions I suggested and the inclusion of the grammar changes I submitted in a previous pull request I believe the documentation would be in a good place.

NOTES
1. Customize-ui.md should have an explaination of the difference between skins and themes.
2. It would be good to have an overview at the beginning of each page in the docs.
3. In the filter-content.md item you mention something likely should’ be included there. I would say don’t include it then.
4. System requirements should be at the beginning of getting started. You should simply state which browsers are supported.
5. Integrations section needs more examples.
6. The check spelling section under enterprise should have a stronger index page. IE the index page links to the setup instructions. These instructions could be more straight forward as well.
7. Consider integrating demos into the examples section.

.

**Comment by jayarjo** [comment]
I think awkward grammar is caused by the fact that only some of us are native english speakers :)

**Comment by r12s** [comment]
The recommendations were completed separately of this issue. Marked closed.
