### ISSUE TITLE
Problem with page integrations/jquery.md

### ISSUE THREAD

**Issue by cobicarmel** [tinymce/tinymce-docs#378]
The [fiddle](http://fiddle.tinymce.com/rsdaab) example which attached to that page doesn't work.

Tested in Chrome, Firefox and Safari.

> _affected page: https://www.tinymce.com/docs/integrations/jquery/_

**Comment by jayarjo** [comment]
It lacked jQuery wrapper for TinyMCE. Should be fixed now.
