### ISSUE TITLE
TinyMCE bullets & numbering issue.

### ISSUE THREAD

**Issue by javeriburhan** [tinymce/tinymce-docs#380]
Hi guys,

Actually m using tinymce in Interwoven Teamsite/livesite. In tinymce i need to customize the bullet/numbering style feature. On clicking bullet icon I want tinymce to embed : 
`<ul class="opshwList">
<li></li>
</ul> 
`
Instead of
`<ul>
<li></li>
</ul> 
`
Is this possibble?? If yes then please let me know how this can be achieved

**Comment by r12s** [comment]
Hi @javeriburhan thanks for reaching out. Please ask this question in the TinyMCE community support forums. Thanks and all the best.
