### ISSUE TITLE
Problem with page plugins/autosave.md

### ISSUE THREAD

**Issue by mantas-done** [tinymce/tinymce-docs#381]
> _affected page: https://www.tinymce.com/docs/plugins/autosave/_

when option is set: **forced_root_block: false**,
**autosave_restore_when_empty: true** - doesn't work

**Comment by r12s** [comment]
Thanks @mantas783 is this an issue with the tinymce editor, or with the docs?

If an editor bug, please open an issue in the tinymce repo: https://github.com/tinymce/tinymce/issues

**Comment by r12s** [comment]
No response from OP. Marking closed.
