### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by rebootcode** [tinymce/tinymce-docs#389]
Problem with page plugins/codesample.md

Codesample is stripping "HTML Tags" inside 
```
<pre><code></code></pre>
```

**Comment by jayarjo** [comment]
Sorry, is it problem of documentation or the plugin?

**Comment by rebootcode** [comment]
I had to use htmlentities to format the code properly.

This issue has been resolved.

Thanks
