### ISSUE TITLE
The text color for Notes is too light

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#39]
The text color for Notes (designated by the green side bar) within articles is too light.  Users with less than ideal eye sight/color perception could have an issue.  This would not pass an accessibility test.   I suggest using something that is darker to create greater contrast.

**Comment by r12s** [comment]
Agree. @kilianc Tim is referring to blockquote elements denoted in the markdown with `>`.

**Comment by kilianc** [comment]
Yep, I am deploying a bunch of css changes, I think they will close most of the tickets here :beers:

**Comment by kilianc** [comment]
fixed
