### ISSUE TITLE
Problem with page plugins/compat3x.md with indicime plugin

### ISSUE THREAD

**Issue by Keshavmca12** [tinymce/tinymce-docs#392]
I have compact3x plugin to integrate with indicime plugin as suggested in the documentation.But i got this error in console 
**Deprecated TinyMCE API call: <target>.onPreInit.add(..)
VM4428:1 Uncaught TypeError: Cannot read property 'select' of undefined**

How can I resolve this issue???

**Comment by r12s** [comment]
Hi @Keshavmca12 please ask the TinyMCE community for an answer on this. https://community.tinymce.com/

Or create an issue in the tinymce repo: https://github.com/tinymce/tinymce/issues

> Marking closed, not an issue with docs.
