### ISSUE TITLE
Problem with page TinyMCE3x@Installation.md

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#393]
On this page the link to “For Dummies” returned a 404
https://www.tinymce.com/docs-3x//TinyMCE3x@Installation/ (edited)

then clicking “Contribute to this Page” produced a 404
otherwise I would have fixed it :wink:

> _affected page: https://www.tinymce.com/docs-3x//TinyMCE3x@Installation/_

**Comment by jayarjo** [comment]
First problem seems to be solved now. The second one seems to be a complex one, since basically every docs-3x “Contribute to this Page” produces 404.

**Comment by r12s** [comment]
The issue is that the `docs-3x` repo is locked. This is an oversight as the "contribute" url should have been removed when creating the 3x repo. Will discuss w/ @androb. Marking closed.
