### ISSUE TITLE
display raw html that is wrapped in code/pre, not rendered!

### ISSUE THREAD

**Issue by kaloraat** [tinymce/tinymce-docs#397]
Everytime i create an article that contains code such as html meta tag wrapped in code/pre. Once i reload the page to edit, it disappears. If i set the encode raw that it does not disappear in backend but displays all raw html in front end. I want to display only raw html in frontend that is wrapped in code/pre. I dont know how many days i need more to solve it? All i want is to display html code in my blog, raw html code, not rendered!  This is my thread in stackoverflow. Please help.

http://stackoverflow.com/questions/39411304/code-snippet-disappears-only-plain-text-remains-in-tinymce?noredirect=1#comment66161128_39411304

> *affected page: https://www.tinymce.com/docs/plugins/code/*

**Comment by r12s** [comment]
Hi @kaloraat pardon the delay in responding. This isn't an issue with the docs. If your problem remains unresolved, please ask the TinyMCE community on our new forum: https://community.tinymce.com/

> Marking closed, not an issue with docs.
