### ISSUE TITLE
Problem with page demo/inline.md

### ISSUE THREAD

**Issue by sjfloat** [tinymce/tinymce-docs#403]
It's empty. There's nothing there. No demo for you!

> *affected page: https://www.tinymce.com/docs/demo/inline/*

**Comment by fyrkant** [comment]
Is this still a problem for you @sjfloat ? The inline example shows up without error for me.

**Comment by jayarjo** [comment]
Could have been temporary CodePen connection problem. Seems to be ok at the moment.
