### ISSUE TITLE
Intermingling Pro/Enterprise info within the doc is problematic

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#42]
We need to either create Pro / Enterprise 'companion' docs, or create a separate Pro / Enterprise section of this doc.  For a number of reasons:
* the pro plugins get lost in the long list of standard plugins. That list is already too long and adding the pro plugins just makes it worse. We'll need to eventually categorize the plugin list which would just make it worse if we have pro plugins spread across a bunch of different categories.
* System requirements differ between Community and Suported versions
* Support differs not only between Community and fee...but will differ between the different fee based coverings.  
By spreading the Pro / Enterprise info out across the document we are making it more difficult for our paying clients and we create more opportunities for people to be confused.

**Comment by androb** [comment]
So #1 is to be addressed through a Pro badge.
And #2 and #3 might be better addressed through a Support section?

**Comment by tim-thatcher** [comment]
I don't believe #1 is adequately addressed by pro badges...especially if we categorize plugins (which we will need to do given the length of the nav bar).

**Comment by r12s** [comment]
This is an important conversation to have and we should move it offline. Marking closed.
cc/ @androb @tim-thatcher

**Comment by androb** [comment]
@r12s I believe it is resolved. We have both now... intermingled and its own section. There isn't much duplicate content. It seems to work.
