### ISSUE TITLE
Link to TinyMCE GZIP Compressors isn't valid

### ISSUE THREAD

**Issue by darrylhein** [tinymce/tinymce-docs#421]
The link ends up redirecting to the default download page (compressor.php page doesn't exist). On the download page there's no information about GZIP compression. Because of this, the rest of the page doesn't really matter anymore – is there even a "GZIP" version of TinyMCE and does it matter any more (if the server has GZIP turned on)?

> _affected page: https://www.tinymce.com/docs/advanced/using-the-gzip-compressors/_

**Comment by fyrkant** [comment]
As spocke states in tinymce/tinymce#3360 gzip is built into most http servers nowadays. The Gzip documentation has been removed.
