### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by Maciej86** [tinymce/tinymce-docs#422]
> *affected page: https://www.tinymce.com/docs/plugins/codesample/*
When edit article not code? But is done html.

**Comment by fyrkant** [comment]
I am sorry but I do not understand your question, could you try to explain it again? Is it a problem with the codesample plugin documentation>

**Comment by Maciej86** [comment]
When I save an article  to the database is OK. But when editing the article does not code.

New articel is OK
`<ul>
    <li>Lista 1</li>
    <li>Lista 2</li>
    <li>Lista 3</li>
    <li>Lista 4</li>
</ul>`

Edit article is not OK (no code)
- Lista 1
- Lista 2
- Lista 3
- Lista 4

**Comment by Maciej86** [comment]
It is well, sorry
