### ISSUE TITLE
Problem with page integrations/angularjs.md

### ISSUE THREAD

**Issue by JavaTimeWilson** [tinymce/tinymce-docs#425]
Hi There followed the instructions on the link below:

https://www.tinymce.com/docs/integrations/angularjs/

however upon loading getting an issue of not finding (404) the resource

http://tinymce.cachefly.net/4.0/themes/modern/theme.min.js

**Comment by fyrkant** [comment]
Are you not installing tinymce with bower?

**Comment by r12s** [comment]
No response from OP. Marking closed.
