### ISSUE TITLE
Problem with page plugins/print.md

### ISSUE THREAD

**Issue by filmatt** [tinymce/tinymce-docs#428]
Beautiful work
But

How do you stop the URL from being appended to the top of the page?

Thank You

> *affected page: https://www.tinymce.com/docs/plugins/print/*

**Comment by fyrkant** [comment]
As this doesn't seem to be an issue regarding the documentation I am closing this issue, but please leave a comment if there if there's anything else you're wondering about and I can open the issue again. For any questions or bug reports regarding the functionality of TinyMCE, please [open an issue on that repository](https://github.com/tinymce/tinymce).
