### ISSUE TITLE
Problem with page plugins/colorpicker.md

### ISSUE THREAD

**Issue by geotonics** [tinymce/tinymce-docs#429]
how do I add a plugin to tinymce? 
> *affected page: https://www.tinymce.com/docs/plugins/colorpicker/*

**Comment by fyrkant** [comment]
As this doesn't seem to be an issue regarding the documentation I am closing this issue, but please leave a comment if there if there's anything else you're wondering about and I can open the issue again.

Regarding how you add a plugin to tinymce you can follow the examples in the documentation, like [this one](https://www.tinymce.com/docs/demo/basic-example/) (click on the html and js tabs in the live example to see the code). For any questions or bug reports regarding tinymce, please open an issue on [that repository](https://github.com/tinymce/tinymce).
