### ISSUE TITLE
TinyMCE Language Article requires changes

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#44]
Required changes:
* This article uses the term internationalization improperly.  What the article is mainly talking about is localization, not internationalization. 
* We should make it clear that these translations are provided by the Community.  (btw...these are not included in our Enterprise Offering and are not supported).
* The link is pointing to the old site.  Will this be part of the re-do?

**Comment by r12s** [comment]
Thanks @tim-thatcher I'll take the first two points and action.

@androb to Tim's last point the docs point to pages we haven't discussed in the redesign, e.g.:
* http://www.tinymce.com/i18n/index.php

There are others:
* http://www.tinymce.com/download/compressors.php 
* http://www.tinymce.com/develop/changelog/?type=tinymce

**Comment by r12s** [comment]
Reopen issue as we need to resolve pages not yet discussed in site redesign. (nb: the localization changes were implemented in commit 678de5b.)

**Comment by r12s** [comment]
I have moved the query regarding the old site content to a new issue. The issue regarding localization has been fixed.
