### ISSUE TITLE
Broken links in /api/tinymce/tinymce.editorobservable/

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#455]
Reported by @ephox-allen, links to the Editor Events doc are broken on the [`editorobservable` page](https://www.tinymce.com/docs/api/tinymce/tinymce.editorobservable/).

The broken url is missing the `/docs/` portion of the url:

It is currently: `https://www.tinymce.com/advanced/events`

and should be

`https://www.tinymce.com/docs/advanced/events/`

![tinymce___tinymce_editorobservable-1](https://cloud.githubusercontent.com/assets/2252896/21268411/9099db90-c363-11e6-9cab-20019b8c5013.png)

**Comment by jayarjo** [comment]
We fixed this a while ago I think.
