### ISSUE TITLE
Basic Configuration Article - Toolbar Config

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#46]
A few items here:
* We talk about 'core' controls.  I don't know if we are trying to stress the term 'core', but it would be much clearer to the reader if we said these were the default controls.
* I don't know when we list the default controls using:
```
xx
```
In the rest of the doc we seem to only use that for display if real code snippets.  What is contained here is not a code snippet.  I find that confusing.  
* We also don't define what these mean.  Shouldn't we spell out what the controls do?
* Would it help to include screenshots of the default config in the document?

**Comment by r12s** [comment]
* Re core controls, this is how toolbar and menu controls were referenced on the old site and a lot of terminology was ported across too. However, I agree and 'core' has been replaced with 'default'.
* Re snippet, agree. Fixed.
* Re explanation, text updated to be more informative. If you mean we should explain the individual functionality of the control, the Get Started guide isn't the place. We could link the control to their plugin association?
* Added a screenshot. We want to keep page weight to a minimum, but agree we should add a screenshot in the right places when it adds value.

http://127.0.0.1:4000/docs/get-started/basic-setup/

**Comment by r12s** [comment]
Changes implemented. Reasonable solution to point re explaining what controls do.
