### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by gautamz07** [tinymce/tinymce-docs#469]
> *affected page: https://www.tinymce.com/docs/plugins/codesample/*

in the 2nd code example:

`tinymce.init({
  selector: "textarea",
  codesample_languages: [
        {text: 'HTML/XML', value: 'markup'},
        {text: 'JavaScript', value: 'javascript'},
        {text: 'CSS', value: 'css'},
        {text: 'PHP', value: 'php'},
        {text: 'Ruby', value: 'ruby'},
        {text: 'Python', value: 'python'},
        {text: 'Java', value: 'java'},
        {text: 'C', value: 'c'},
        {text: 'C#', value: 'csharp'},
        {text: 'C++', value: 'cpp'}
    ],
  toolbar: "codesample"
});`

please add the following line:

`plugins: "codesample",`,

without which the plugin does't function ! :)

**Comment by spocke** [comment]
We fixed this problem now thanks for the report.
