### ISSUE TITLE
Basic Configuration Article - Example

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#47]
Ehe Basic Configuration example introduces config settings that were not previous introduced in the article.  Width and Height are pretty simple so not much of a problem.  Theme is probably ok too.  But I have a hard time with style formats.  If we are going to include the in the example then we should introduce the beforehand.  If not, then I suggest we remove them from the example.  I'm thinking these maybe too much for a basic config.  

Also the link at the end to 'formats configuration' is broken.

**Comment by r12s** [comment]
Thanks @tim-thatcher I agree re formats, too advanced for this stage and doesn't add enough value to the reader. Plus it is discussed in the Content Filtering section of Configuration Settings. I will remove it.

I have fixed the broken link and this will be pushed with the next bunch of changes.

Marking this closed.
