### ISSUE TITLE
Table plugin should have a header row option and button

### ISSUE THREAD

**Issue by tobia** [tinymce/tinymce-docs#470]
Hello

I think the table plugin should create the first row as a `<thead>` with `<th>` cells, or at least have a configuration option to do so.

Also, there should be an easy button to add or remove the header row. Right now one needs to set the row to header type, in the somewhat hidden row properties (as in, not present in the popup toolbar) and *also* then set the cells to header type in the cell properties.

By contrast, this is what the Atlassian Confluence new table widget looks like. It has a default first header row that can be turned off with a shortcut key:

![confluence1](https://cloud.githubusercontent.com/assets/48756/21895217/24a180c0-d8e2-11e6-98a8-9123952781a0.png)

Also, the table toolbar has header row and header column toggle buttons:

![confluence2](https://cloud.githubusercontent.com/assets/48756/21895229/317a28a6-d8e2-11e6-9832-c472826967ad.png)

**Comment by Afraithe** [comment]
You should maybe have submitted this in tinymce reporistory, not the documentation.
