### ISSUE TITLE
Improve Documentation Around Content Formatting "Exact" Setting

### ISSUE THREAD

**Issue by jhned** [tinymce/tinymce-docs#471]
Hey there,

I'm having a hard time understand what exactly the "Exact" parameter of a tinyMCE format is supposed to do, as documented on this page: https://www.tinymce.com/docs/configure/content-formatting/

It currently reads "Exact: Disables the merge similar styles feature when used. This is needed for some CSS inheritance issues such as text-decoration for underline/strikethough."

I've searched around for an explanation on what the "merge similar styles" feature is, but have come up empty. Every site I've looked at amusingly copies the tinyMCE documentation verbatim.

My guess is that setting this to "true" would apply CSS styles from multiple formats. E.g., if Format1 has a styles parameter set to `color: 'red'` and Format2 has a styles parameter set to `color: 'blue'`, then the output would be `<some-tag style="color: red; color: blue">` .

Is this right, or am I misreading this?

**Comment by jayarjo** [comment]
When format is applied to the selected element(s) it usually creates a wrapper with corresponding CSS styles around it. Naturally after some time some excessive wrappers might be created, duplicating formats of each other. So internally we simplify this and merge appropriate ones.

By settings `exact` option to true, one basically tells internal merger to not process the specified format.
