### ISSUE TITLE
Document 'drop' event

### ISSUE THREAD

**Issue by MichaelFromin** [tinymce/tinymce-docs#477]
> *affected page: https://www.tinymce.com/docs/advanced/events/*

At present this page does not document the existence of a drop event but in the source code for TinyMCE exists both:

`editor.fire('drop'...)`
...and...
`editor.on('drop'...)`

...so I would think it makes sense to add this to the documentation.

**Comment by tylerkelly13** [comment]
Hi @MichaelFromin, the missing events have been added to the documentation, see: https://www.tiny.cloud/docs/advanced/events/#supportedbrowser-nativeevents
