### ISSUE TITLE
Problem with page plugins/code.md

### ISSUE THREAD

**Issue by Kristiansky** [tinymce/tinymce-docs#478]
`plugins: [
				'advlist autolink lists link image charmap print preview hr anchor pagebreak',
				'searchreplace wordcount visualblocks visualchars code fullscreen',
				'insertdatetime media nonbreaking save table contextmenu directionality',
				'emoticons template paste textcolor colorpicker textpattern imagetools'
],`
These are the plugins i use, but only the CODE doesn't work.

I cannot click on the textarea appearing after clicking the '<>' icon. I click but i cannot write code inside of it.
![image](https://cloud.githubusercontent.com/assets/11662094/22149818/a1a2ba2a-df1e-11e6-9eae-2f37ea736027.png)

> *affected page: https://www.tinymce.com/docs/plugins/code/*

**Comment by fyrkant** [comment]
Is this a problem with the documentation or a problem with the tinymce editor itself? Please open an issue [on the right repository](https://github.com/tinymce/tinymce) if it is a problem with the editor.

**Comment by Kristiansky** [comment]
How could i know? I didn't wrote it.
All i know is that i cannot write in the textarea, appearing after i click the `<>` icon.

**Comment by fyrkant** [comment]
Please open an issue on the [TinyMCE Editor repository](https://github.com/tinymce/tinymce) instead and include a [fiddle](http://fiddle.tinymce.com/) where you reproduce the problem you are having. 

This is the repository for the documentation page, only meant to be used if you find typos or something like that in the documentation.
