### ISSUE TITLE
Vue wrapper - add to list of Integrations

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#479]
https://twitter.com/madewithvuejs/status/822890317338857473

**Comment by androb** [comment]
https://github.com/mbouclas/tinymce-vue-2?files=1

**Comment by MagicMicah** [comment]
Is this going to be a future section under https://www.tinymce.com/docs/integrations/ or should this be a support ticket under https://github.com/tinymce/tinymce as an integration you would like to happen?

**Comment by tylerkelly13** [comment]
Vue integration and the documentation for using it has been released.
The documentation can be found here: https://www.tiny.cloud/docs/integrations/vue/
Closing this issue.
Please reopen or create a new issue if this issue should not have been closed.
