### ISSUE TITLE
Problem with page advanced/migration-guide-from-3.x.md

### ISSUE THREAD

**Issue by diggetydog** [tinymce/tinymce-docs#481]
> *affected page: https://www.tinymce.com/docs/advanced/migration-guide-from-3.x/*

I feel there should be some kind of instruction here. Even it is as simple as replacing the contents of the tiny_MCE folder. I realize it is as simple as that but would be nice to say that. Just add upgrading is as simple as replacing your folder contents" but something way sexier.

This just tells me what is different.

**Comment by jayarjo** [comment]
Simply replacing folders wouldn't work. You will need to accommodate to the changes outlined on that page, including script url, outdated plugins, altered themes, etc. All crucial points are listed.

**Comment by jayarjo** [comment]
I've added the toc at the top.
