### ISSUE TITLE
Problem with page plugins/template.md

### ISSUE THREAD

**Issue by raxan** [tinymce/tinymce-docs#492]
More example would be useful for custom template.

Missing also example of making snippet:
https://www.tinymce.com/docs/plugins/template/#makingsnippets

And here for custom variable there is not explained how to render them using {$varName}: https://www.tinymce.com/docs/plugins/template/#example

I just found on bottom under making snippet, but without that I was trying how to render variable "username" and "staffid" of the examples.

> *affected page: https://www.tinymce.com/docs/plugins/template/*

**Comment by tylerkelly13** [comment]
The TinyMCE 5.1 documentation has been released, including an updated Template plugin page addressing these issues: https://www.tiny.cloud/docs/plugins/template/
