### ISSUE TITLE
Invalid link to accessibility checker demo in page plugins/a11ychecker.md

### ISSUE THREAD

**Issue by OlivierJaquemet** [tinymce/tinymce-docs#493]
> *affected page: https://www.tinymce.com/docs/plugins/a11ychecker/*

There is a link to "a live demo of the accessibility checker here" however it redirect to the pricing page

either there is a live demo, and the link should be fixed 
else there is none, and text should be updated accordingly

**Comment by jayarjo** [comment]
Accessibility plugin is included in the demo on the main page [here](https://www.tinymce.com/).
