### ISSUE TITLE
h2 and h3 not clearly differentiated

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#50]
The font size and weight of h2 (md ##) and h3 (md ###) elements are quite similar, making it difficult to differentiate between titles in sections. This is an issue for context when reading lengthly sections that have many h2 and h3 heads.

Suggest increasing h2 font weight and slightly decreasing h2 font size.

**Comment by kilianc** [comment]
@r12s got a I link that I can experiment with?

**Comment by kilianc** [comment]
@r12s this should have been fixed, if it isnt, please provide a link that I can look at :+1:

**Comment by r12s** [comment]
This is fixed. Marking closed.
