### ISSUE TITLE
Problem with page demo/file-picker.md

### ISSUE THREAD

**Issue by Federico-G** [tinymce/tinymce-docs#504]
The image upload server is down:
https://s.codepen.io/tinymce/fullembedgrid/postAcceptor.php

> *affected page: https://www.tinymce.com/docs/demo/file-picker/*

**Comment by cjdubois10** [comment]
Hi @Federico-G it looks like this issue was fixed. On the affected page, the image upload server now directs users to a different URL which is working. The new URL is:
https://codepen.io/tinymce/pen/132465f8d1e8c9666faf161255cb7eb8 

This issue should be closed.

**Comment by jayarjo** [comment]
It's was only demo. Upload was never functional in there (that's why `images_upload_url` is commented out). If you are going to implement this locally you should have your own upload handler up and handling uploaded files.
