### ISSUE TITLE
`description` page field is sometimes too long for index pages

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#51]
![](https://www.dropbox.com/s/235skcl2bagrzj6/Screenshot%202015-11-09%2015.42.08.png?dl=1)

We need to introduce `description_short` in the front matter to handle this, I am going to prepare the code side, @r12s I'll leave the content part to you

**Comment by kilianc** [comment]
@r12s all yours see: getting-started/basic-configuration.md

**Comment by r12s** [comment]
The content side is in progress. The issue is resolved technically. Marking closed.
