### ISSUE TITLE
Problem with page demo/format-custom.md

### ISSUE THREAD

**Issue by Moondrop** [tinymce/tinymce-docs#511]
> *affected page: https://www.tinymce.com/docs/demo/format-custom/*

Viewing on Chrome 57, I don't see the example `My custom format` in the toolbar.

The example js has this in it:

`customformat: { inline: 'span', styles: { color: '#00ff00', fontSize: '20px' }, attributes: { title: 'My custom format' }, classes: 'example1' },`

But in the output tinymce I see:

![tinymce-custformat-2](https://cloud.githubusercontent.com/assets/1851892/24271976/debda5e4-0fe0-11e7-9b38-1dd208cd7216.gif)

![tinymce-custformat-3](https://cloud.githubusercontent.com/assets/1851892/24271980/e1c7209e-0fe0-11e7-8095-59728efcf0fb.gif)

**Comment by jayarjo** [comment]
Formats defined through the `format` option are meant to be used [through the API](https://www.tinymce.com/docs/configure/content-formatting/#usingcustomformats) and are not visualized in the Formats menu (might be a bit confusing, but that's what we have at the moment). If you are looking to add more formats to the Formats menu, you should use [style_formats](https://www.tinymce.com/docs/configure/content-formatting/#style_formats) instead.
