### ISSUE TITLE
Example to allow script elements

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#518]
From the TinyMCE Community

https://community.tinymce.com/communityQuestion?id=90661000000Ih9oAAC

script elements removed by default
I was reading today about valid_elements and that ...

The default rule set for this option is a mixture of the full HTML5 and HTML4 specification or the HTML5 or HTML4 specification depending on the configured schema.

But I have noticed that <script> elements are being removed.  I took a look at the changelog to see if anything popped out at me and I found this entry in the 4.2.0 release:

Fixed so script elements gets removed by default to prevent possible XSS issues in default config implementations.

So, this is by design?  If so, can you confirm for me?  And perhaps update the docs, I guess.  In the meantime I'll pull the latest source and have a look at the default value for HTML5.

Thanks in advance!

Solution:

I found it in the compileSchema function:

        // Delete scripts by default due to possible XSS
        delete schema.script;

If anybody needs to allow script elements again you can use the extended_valid_elements:
        `extended_valid_elements : "script[src|async|defer|type|charset]"`
Just a suggestion, maybe update the docs?  :)  I know, you have plenty to do as it is ;)

[r12s Comment:] Add this as an example to the config options. Algolia will surface well written content in our search results.

**Comment by saphaljha** [comment]
@r12s , Hello Thank you for suggestion I have tries the same but I am getting below error in console:

> Uncaught TypeError: Cannot set property 'src' of undefined

**Comment by tylerkelly13** [comment]
Information on allowing script elements as been added to the TinyMCE 5.1 documentation: https://www.tiny.cloud/docs/configure/content-filtering/#usingextended_valid_elementstoallowscriptelements
