### ISSUE TITLE
Problem with page integrations/angular2.md

### ISSUE THREAD

**Issue by theutz** [tinymce/tinymce-docs#526]
When I follow the instructions exactly, the "setup" function is never called. (I put a console.log in the body of the arrow function, and it never fires.) As a result, the "editor" property remains undefined and my textbox just looks...sad. :) However, the tinymce variable seems to be accessible from the Chrome DevTools console, so I know it's loading, etc.

> *affected page: https://www.tinymce.com/docs/integrations/angular2/*

**Comment by r12s** [comment]
@fyrkant can I get your input on this?

**Comment by theutz** [comment]
I was able to resolve the issue. It was necessary to run the `tinymce.init()` code in the `AfterContentChecked` hook. In order to improve performance, I put the code in a conditional checking to see if `this.editor` was undefined. Hope that helps!

**Comment by tylerkelly13** [comment]
Hi @theutz,
The Angular documentation has recently been updated and has been tested to ensure it works. It looks like the integration has changed since this issue was logged. The updated page is live at: https://www.tiny.cloud/docs/integrations/angular/
