### ISSUE TITLE
Problem with page advanced/creating-a-custom-button.md

### ISSUE THREAD

**Issue by ymages** [tinymce/tinymce-docs#527]
> *affected page: https://www.tinymce.com/docs/advanced/creating-a-custom-button/*

Hi very nice description , but where do you write that code , in which file ?

I want to add a picture/source button  and  a youtube button

thank you

**Comment by jayarjo** [comment]
> but where do you write that code , in which file ?

What do you mean? Fully functional example is provided in that tutorial.

**Comment by MagicMicah** [comment]
@ymages and @jayarjo - Do you think this issue is resolved enough to close the ticket? If you have any more issues perhaps you can consult https://community.tinymce.com/

**Comment by cjdubois10** [comment]
I actually agree with @MagicMicah . Since this is a specific question, it should probably be posted on the community site. I do not think that it should be an open documentation issue. Maybe consider closing it?

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
