### ISSUE TITLE
Rendering of banner on features page is wrong

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#53]
See attached. I haven't been able to replicate exactly when this occurs but I have seen it multiple times.

I believe it has to do either with first load, retina displays or large screens!

<img width="717" alt="screen shot 2015-11-09 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/2160304/11051247/69851856-8702-11e5-93cd-f765b849f9f6.png">

**Comment by lucaorio** [comment]
@androb does it happen when you're using a retina device, attached to an external non-retina one (i.e. the AirDisplay monitor in the Wombat room)?

**Comment by kilianc** [comment]
![](http://s3-static-ak.buzzfed.com/static/2014-06/4/13/campaign_images/webdr03/please-enjoy-the-first-installment-of-wombat-wedn-2-32666-1401904265-0_big.jpg)

**Comment by lucaorio** [comment]
fixed, already on http://beta.tinymce.com/features/
