### ISSUE TITLE
style_formats: replace style

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce-docs#541]
In `images_class_list` I can specify single select classes. On change they will be overwritten/replaced.
How do I achieve the same effect (replace class) in `style_formats`?
For example if I have the two classes "img-left" and "img-right" both classes selected in `style_formats` makes no sense. How do I make them "switchable"?
regards
manu

**Comment by spocke** [comment]
We should probably expand on the docs on this subject. You can specify attributes and if you specify "class" that way it will overwrite. Toggling classes makes sense if you have styles like "blue" and "big" then you can combine blue + big. Image alignment can also be done with classes and using the alignment buttons using formats option.

**Comment by manu37** [comment]
Perfect, @spocke! That did the job.
`attributes: {class:'img-left'}` resp.
`attributes: {class:'img-right'}`
