### ISSUE TITLE
NO Specific Font Size

### ISSUE THREAD

**Issue by jonjie0317** [tinymce/tinymce-docs#542]
How can I set specific **font size**? I had a set up of font size which is the sizes are limited, only `8pt, 10pt, 12pt,  14pt, 18pt,` etc. What if I want to change the font size to **7pt**?  or **3.5em**? or **9px**?  Need help about this. Thank you,

**Comment by fyrkant** [comment]
This can be set with the `fontsize_format` option: https://www.tinymce.com/docs/configure/content-formatting/#fontsize_formats
