### ISSUE TITLE
Improve styling of changelog

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#55]
The changelog is awfully plain right now.

I really like this one:
https://help.us-themes.com/zephyr/changelog/

**Comment by kilianc** [comment]
can be done with little css I would love @lucaorio to make the palette

**Comment by kilianc** [comment]
@androb reading at the changelog there is no real standard at the source for Additions, Fixes and removal of features. Maybe we can decide on one and move forward?

**Comment by lucaorio** [comment]
Just added the relative scss to the shared stylesheet!
It's going to look like this:
![screenshot 2015-11-10 22 26 16](https://cloud.githubusercontent.com/assets/299621/11085347/13c38d32-87fa-11e5-95c2-787d3f3dacc4.jpg)
