### ISSUE TITLE
Document "merge_siblings" format parameter

### ISSUE THREAD

**Issue by pcworld** [tinymce/tinymce-docs#556]
There's a useful, [undocumented content format parameter called `merge_siblings`](https://github.com/tinymce/tinymce/blob/48ee216730508df92f486df1b7da73f6643c5e79/src/core/src/main/js/Formatter.js#L758) which when set to `false` prevents two successive custom format nodes from being merged. It should be documented.

**Comment by tylerkelly13** [comment]
The documentation has been updated to include information on using `merge_siblings`. The New content can be found here: https://www.tiny.cloud/docs/configure/content-formatting/#merge_siblings
