### ISSUE TITLE
Problem with page demo/file-picker.md

### ISSUE THREAD

**Issue by a-kolybelnikov** [tinymce/tinymce-docs#566]
> *affected page: https://www.tinymce.com/docs/demo/file-picker/*

the following line cannot be integrated in angular2 ts-file:
var file = this.files[0];

error msg: [ts] Property 'files' does not exist on type 'HTMLElement'.

**Comment by fyrkant** [comment]
This is not a problem with TinyMCE, check this StackOverflow question: 
https://stackoverflow.com/questions/12989741/the-property-value-does-not-exist-on-value-of-type-htmlelement

I think you can just type this in the input onchange function like this:

```ts
input.onchange = function (this: HtmlInputElement) {}
```
