### ISSUE TITLE
Problem with page integrations/angularjs.md

### ISSUE THREAD

**Issue by alacret** [tinymce/tinymce-docs#567]
It does not instruct how to reference the plugins or themes in a minified enviroment

> *affected page: https://www.tinymce.com/docs/integrations/angularjs/*

**Comment by tylerkelly13** [comment]
if you are using a module loader, see: https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/
if you need minified versions of the plugins or themes, use the [suffix setting](https://www.tiny.cloud/docs/configure/integration-and-setup/#suffix).
