### ISSUE TITLE
First time setup error: "An error occurred while installing nokogiri (1.6.6.4)" on macOS

### ISSUE THREAD

**Issue by indiesk** [tinymce/tinymce-docs#578]
I've tried looking for any similar issue here, but I could not find it so here is a quick fix for those who are facing an error while installing `nokogiri`:

I've changed a few files.

Inside `/_scripts/init.sh`, I've added a couple more lines before calling `bundle install`

```
echo " > installing gems into ./vendor/bundle"
bundle config build.nokogiri --use-system-libraries \
  --with-xml2-include=$(brew --prefix libxml2)/include/libxml2
bundle install --path vendor/bundle --verbose
```

I've also updated the `Gemfile` to install the latest version of `nokogiri`.

```
gem 'nokogiri'
```

To use the latest version of `nokogiri`, I needed to update the `Gemfile.lock` to tell the correct dependencies. The latest version of `nokogiri` uses `mini_portfile2` instead of `mini_portfile`.

```
...
mini_portile2 (2.2.0)
...
nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
...
```

This resolved my issue, and hopefully this helps others who are trying to setup for the first time on a mac. If anyone sees some other errors while installing `nokogiri`, here is a link to their document on installing on macOS:

http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x

Please feel free to comment for better solutions.

**Comment by tylerkelly13** [comment]
Hi @indiesk,

Sorry for the slow response. We're updating the readme at the moment and we tested the documentation build from scratch. It appears that this bug has been resolved. The Nokogiri and mini_portile gems were updated in the Gemfile in 2018 and have been updated a few times subsequently. Thanks for the well documented workaround.

Moving this issue to closed. Thanks again for your help.
Tyler
