### ISSUE TITLE
Problem with page advanced/creating-custom-dialogs.md

### ISSUE THREAD

**Issue by anitagraham** [tinymce/tinymce-docs#585]
The page doesn't do what its title says "Create Custom Dialogs". It tells you how to create custom dialogs the 3.x way, but says little about how they should be created in 4.

_In TinyMCE 3.x all dialogs were HTML pages that got loaded into an iframe or window. This was changed in TinyMCE 4 to make it easier to make plugins and fully support CDNs. But you can still load HTML based pages into TinyMCE dialogs by using the WindowManager._

> *affected page: https://www.tinymce.com/docs/advanced/creating-custom-dialogs/*

**Comment by feliciath** [comment]
Hi Anita,

I am also facing a similar issue where we are migrating custom plugins.
It would be really helpful if you could  let me know  any updates on this.

Thanks,
Felicia

**Comment by fyrkant** [comment]
Yes this page should definitely be improved with more examples on how to create dialogs correctly in 4.X. I will create a ticket in our internal issue tracker to do this, but in the meantime do you have any specific things that you want the page to explain?

**Comment by tylerkelly13** [comment]
Hi @anitagraham, @feliciath, @fyrkant.
This page was updated for the TinyMCE 5 documentation, and can be found here: https://www.tiny.cloud/docs/ui-components/dialog/
Currently, all updates are made to the TinyMCE 5 documentation. Updates are only made to the TinyMCE 4 documentation for critical fixes.
Please reopen or create a new issue if this issue should not have been closed.
