### ISSUE TITLE
Problem with page advanced/migration-guide-from-3.x.md

### ISSUE THREAD

**Issue by feliciath** [tinymce/tinymce-docs#586]
> *affected page: https://www.tinymce.com/docs/advanced/migration-guide-from-3.x/*

Hi,

We are currently migrating to Tinymce 4.x from 3.x. We have  a couple of custom plugins where we need to have the dialogs as HTML files. I have followed the instructions in the page but I am not able to get an editor instance in the HTML file.

If I try to use top.tinymce.activeEditor.windowManager.close(); or any such reference it throws an error telling top.tinymce.activeEditor is undefined.

Could you please help me in this issue.

Thanks,
Felicia

**Comment by jayarjo** [comment]
This probably should be filed as an issue on [TinyMCE issue tracker](https://github.com/tinymce/tinymce/issues) rather than here.

Editor instance should be initialized and ready, otherwise `top.tinymce.activeEditor` will return undefined. This is expected.
