### ISSUE TITLE
Problem with page demo/format-custom.md

### ISSUE THREAD

**Issue by Lotykun** [tinymce/tinymce-docs#598]
THERE IS NO EXAMPLE HOW TO USE THE COSTUM FORMAT DEFINITION. Where or when do i have to use the tinymce.activeEditor.formatter.register('custom_format', {inline : 'span', styles : {color : '%value'}}); sentence??

> *affected page: https://www.tinymce.com/docs/demo/format-custom/*

**Comment by jmadden85** [comment]
👍  +1 on this issue.  That page is basically useless.

**Comment by tylerkelly13** [comment]
Select the `JS` tab above the demo to view the example code used. The custom formats are defined by `style_formats`.
https://www.tiny.cloud/docs-4x/demo/format-custom/
https://www.tiny.cloud/docs/demo/format-custom/
Please reopen or create a new issue if this issue should not have been closed.
