### ISSUE TITLE
Problem with page demo/full-featured.md

### ISSUE THREAD

**Issue by zjean** [tinymce/tinymce-docs#600]
Demo's aren't working at all.
> *affected page: https://www.tinymce.com/docs/demo/full-featured/*

**Comment by r12s** [comment]
Hi @zjean thanks for raising the issue. I'm unable to replicate this.

fwiw, we use Codepen for the demos. Occasionally a service interruption on the Codepen side takes the demos offline. Not ideal, but the benefits Codepen offers everyone outweigh these rare instances.

I'll mark this closed, but by all means re-open this if you see the issue again.
