### ISSUE TITLE
PHP upload handler returns wrong status code

### ISSUE THREAD

**Issue by vanillajonathan** [tinymce/tinymce-docs#603]
It returns 500 instead of 400.
It also returns HTTP/1.0 instead of HTTP/1.1.

**Comment by Afraithe** [comment]
It is meant as a reference mostly.

**Comment by vanillajonathan** [comment]
Well the reference could be improved to be more correct in its behavior.

**Comment by jayarjo** [comment]
@vanillajonathan I've updated it as you suggested.

**Comment by vanillajonathan** [comment]
Reference: d0ff5e2

Great! 👍
