### ISSUE TITLE
Search in API reference links to wrong URL

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#610]
Search for "getContent"

A result is returned in the search, but the link is wrong.

It should go to https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#getcontent

Instead, it goes to https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#editor

This occurs for all pages in the API reference and makes it significantly more difficult to use.

**Comment by fyrkant** [comment]
This was caused by a problem with the algolia docsearch config, I did a PR to the file that has now been merged in and it seems to be working better!
