### ISSUE TITLE
Problem with page plugins/advlist.md

### ISSUE THREAD

**Issue by Menazanie** [tinymce/tinymce-docs#613]
Well hello.

I was starting a project where people can edit their own piece of text by using WYSIWYG. I followed the tutorial like they way it was presented to me. I was stuck here and had no idea what I did wrong. I added the toolbar: 'advlist' with the advlist possibilities. It kept on not working. I thought that I did something wrong because console didn't push anything back towards me that something was wrong. After a little bit of frustration, I googled TinyMCE Advanced List plugin. I quickly found out that I had to add 'lists' to the toolbar. Looked back at what I did and there was no mention of 'lists'.

You may think that this might be common sense but experiencing this was new for me and thought it was kind of strange to let out the function that shows what you did. 

Let me know where it's stated. Just maybe I overlooked it.

> *affected page: https://www.tinymce.com/docs/plugins/advlist/*

**Comment by fyrkant** [comment]
Thank you for this issue, I added a note to the advlist plugin page that the lists plugin is needed for it to work.
