### ISSUE TITLE
Provide examples of code that manipulates checkboxes, radio buttons, text boxes select boxes

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#617]
From @paulschreiber:
Provide examples of code that manipulates checkboxes, radio buttons, text boxes select boxes

My understanding of this requirement:

As a developer, I want to interact with checkboxes, radio buttons, text boxes and select boxes in TinyMCE dialogs. I am able to hack a solution to this at the moment, but clearer examples would help.

**Comment by r12s** [comment]
@androb is the requirement to create "how-to" type content, rather than to fix existing issues w/ docs? If so, I'll work with the team (and Paul) to scope the requirement.

**Comment by tylerkelly13** [comment]
This issue was resolved with the release of TinyMCE 5.0. The API methods for these tasks can be found here: https://www.tiny.cloud/docs/ui-components/dialog/#dialoginstanceapi
