### ISSUE TITLE
Problem with page demo/file-picker.md

### ISSUE THREAD

**Issue by JRichmond27** [tinymce/tinymce-docs#620]
The CodePen link is broken: http://codepen.io/tinymce/pen/yVqpjq/

> *affected page: https://www.tinymce.com/docs/demo/file-picker/*

**Comment by cjdubois10** [comment]
@JRichmond27 it looks like the CodePen link was changed to https://codepen.io/tinymce/pen/132465f8d1e8c9666faf161255cb7eb8 and now works

**Comment by cjdubois10** [comment]
@JRichmond27 is that the fix that you were looking for? If so, I think that this issue should be closed.

**Comment by fyrkant** [comment]
Yes this seems to work now, closing this.

**Comment by JRichmond27** [comment]
@cjdubois10, yep, looks good to me. Thanks!
