### ISSUE TITLE
Problem with page plugins/legacyoutput.md

### ISSUE THREAD

**Issue by musicpanda** [tinymce/tinymce-docs#621]
> *affected page: https://www.tinymce.com/docs/plugins/legacyoutput/*

I want to use this plugin for preparing email content. However, it produces a "save" button - that I don't want. And when I use the getContent() function it delivers content that has not been converted to legacy.

**Comment by idempotency** [comment]
Which version of TinyMCE are you using? In 4.7.4 I can't see any "save" button when I enable `legacyoutput`, and `getContent()` outputs converted HTML just fine.

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
