### ISSUE TITLE
Problem with page plugins/codesample.md - Example using Prism.js script section

### ISSUE THREAD

**Issue by laultman** [tinymce/tinymce-docs#626]
I understand your code examples elsewhere. In this case the example has three lines. It doesn't show enough information to indicate how it would actually be used in a webpage's html code. In short, where does it go?

> *affected page: https://www.tinymce.com/docs/plugins/codesample/*

**Comment by r12s** [comment]
Hi @laultman thanks for the question. I'm not sure what you're asking, so help me out here.

Is the issue that it's not clear where to place the `init` in the HTML? Or where the `selector` goes in the HTML `body`? Or how an author marks code so that the Prism effect is applied?

**Comment by laultman** [comment]
Its clear how to init. But beyond that how would I the writer of the html actually cause it to work in an html document. Maybe a working example might be in order, not just a snippet. What do you put in the html body to actually cause something to happen?

**Comment by laultman** [comment]
By the way - I went totally in another direction because it was too much trouble to try and figure out the example.

**Comment by r12s** [comment]
Thanks for the feedback @laultman I added a Codepen to the page to better explain how it works for the end user. Marking this closed.
