### ISSUE TITLE
Problem with page configure/content-formatting.md

### ISSUE THREAD

**Issue by KatkayApps** [tinymce/tinymce-docs#627]
You guys start on the premise that one knows where to add these snippets...
> *affected page: https://www.tinymce.com/docs/configure/content-formatting/*

for example:

tinyMCE.init({
        ...
        inline_styles : false
});

Where do I add these? Your entire documentation fails to tell us where to add stuff.

**Comment by MagicMicah** [comment]
Hi @KatkayApps,
Perhaps this page http://fiddle.tinymce.com/ or this page https://www.tinymce.com/docs/get-started-cloud/features-only/ could help you. If you have anymore questions the https://community.tinymce.com/ may also be helpful. 

It is my understanding that 'tinyMCE.init' is the javascript element where you can choose what plugins or features you would like to use. I am looking to improve the tinymce comminity and created this html to test plugins and what not https://github.com/RubberDuckies2017/tinymce/blob/testenv/test/TestEnvironment.html

**Comment by r12s** [comment]
Thanks @MagicMicah for helping here!

@KatkayApps the docs contain a "Get Started" section https://www.tinymce.com/docs/get-started/first-steps/ that answers this question. The [Basic Setup](https://www.tinymce.com/docs/get-started/basic-setup/) page (in the same section of the docs) contains a functional snippet that should help.

I believe this answers the question. Thanks and marking closed.
