### ISSUE TITLE
Tiled page content hidden by footer

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#63]
@kilianc content in pages using the tiled layout with greater than 10 items disappear into the footer. The page stops scrolling.

See attached image, where items 11 and 12 are behind in the footer. 

Ref http://beta.tinymce.com/docs/get-started/

![screen_2015-11-10_11-43-57_am](https://cloud.githubusercontent.com/assets/2252896/11073682/a67b984a-87a0-11e5-94c6-ed98edef8c83.png)

**Comment by kilianc** [comment]
on it
