### ISSUE TITLE
Missing icons on menubar

### ISSUE THREAD

**Issue by MEChasle** [tinymce/tinymce-docs#633]
Hi,
Sorry for my english !
Here is my code reproduction.
```
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.4/tinymce.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.4/plugins/fullscreen/plugin.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.4/plugins/lists/plugin.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.4/plugins/textcolor/plugin.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.4/themes/modern/theme.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.5/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-tinymce/0.0.19/tinymce.min.js"></script>
    <script>
        angular.module('app', ['ui.tinymce']);
    </script>
</head>
<body ng-app="app">
    <textarea ui-tinymce="{plugins: 'fullscreen textcolor lists'}" ng-model="$ctrl.model"></textarea>
</body>
</html>
```
Click on ```View```, icon on ```Fullscreen``` is missing. Others icons are missing too in other menu.
Did I miss something ?
Thanks for answers

**Comment by r12s** [comment]
@MEChasle this appears to be an issue regarding the implementation of the editor and is out of scope for the docs issue tracker. The [TinMCE Community](https://community.tinymce.com/) is a better place for this question. Please [create an account](https://community.tinymce.com/communityRegister) to get started.

Marking issue closed.

**Comment by MEChasle** [comment]
Thanks.
More information https://community.tinymce.com/communityQuestion?id=9066100000097HzAAI
