### ISSUE TITLE
Problem with page integrations/react.md

### ISSUE THREAD

**Issue by flanamacca** [tinymce/tinymce-docs#634]
> *affected page: https://www.tinymce.com/docs/integrations/react/*

This does not work - throws an error 
uncaught at handleCall TypeError: Cannot set property 'onload' of null

This is only solvable by using React 16 error boundaries and then works, indicating that the integration code is looking for events that are not defined yet.

**Comment by fyrkant** [comment]
If you have a problem with the `@tinymce/tinymce-react` package please create an issue there instead: https://github.com/tinymce/tinymce-react
