### ISSUE TITLE
Enhancement: Page demo/custom-toolbar-menu-button.md

### ISSUE THREAD

**Issue by CaMer0n** [tinymce/tinymce-docs#639]
Would like to see an example included of a secondary drop-down menu. 

eg. 
![image](https://user-images.githubusercontent.com/2825679/34010914-26a35c06-e0c3-11e7-9cdb-24a1b3cd0a14.png)

> *affected page: https://www.tinymce.com/docs/demo/custom-toolbar-menu-button/*

**Comment by jayarjo** [comment]
I've added example of submenu.

**Comment by CaMer0n** [comment]
@jayarjo Thank you!
