### ISSUE TITLE
Problem with page plugins/bbcode.md

### ISSUE THREAD

**Issue by MaxPerl** [tinymce/tinymce-docs#640]
Can't initialize BBCODE Plugin with the example code.
And please add a tutorial, how to add custom bbcodes or dialects...

> *affected page: https://www.tinymce.com/docs/plugins/bbcode/*

**Comment by jayarjo** [comment]
Currently there are no plans to add other bbcode dialects. The only way one could add some himself would be to clone the bbcode plugin and modify it to requirements.

I've added a live example on the page.
