### ISSUE TITLE
Problem with page configure/content-filtering.md

### ISSUE THREAD

**Issue by DavidDeSloovere** [tinymce/tinymce-docs#646]
The default is not specified. It's probably 'allow all', but it's unsure.

> *affected page: https://www.tinymce.com/docs/configure/content-filtering/*

**Comment by DavidDeSloovere** [comment]
My bad. Didn't realize the anchor was not in the url.
It's: **valid_styles**

**Comment by r12s** [comment]
https://www.tinymce.com/docs/configure/content-filtering/#valid_styles

**Comment by tylerkelly13** [comment]
The description has been updated and will be live later this week.
