### ISSUE TITLE
Adding another integration to extras/TinyMCE3x@Software_using_TinyMCE.md

### ISSUE THREAD

**Issue by pirobase-luca** [tinymce/tinymce-docs#651]
I wanted to edit a page in the docs (add an integration to this page: https://www.tinymce.com/docs-3x//extras/TinyMCE3x@Software_using_TinyMCE/) but the link "Contribute to this page" at the top is broken and throws a 404 Page Not Found.

**Comment by tylerkelly13** [comment]
Hi @pirobase-luca,
The `tiny-docs-3x` github repo has been deprecated and the version 3 docs cannot be updated via github.
Apologies for the inconvenience.
Please reopen or create a new issue if this issue should not have been closed.
