### ISSUE TITLE
Problem with tinymce,init

### ISSUE THREAD

**Issue by bbxrider** [tinymce/tinymce-docs#655]
there are numerous examples how to use tinymce.init, eg,
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'fontsizeselect',
  fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt'
});

but for some unknown reason there is never any documentation on which file to place the code into??????????????????????????????????????????
a .css file?
a .js file?
a .php file?

after such great detailed documentation on what the code is, why not let everybody in on the secret to where it goes?

> *affected page: https://www.tinymce.com/docs/advanced/creating-a-sidebar/*

**Comment by r12s** [comment]
Hi @bbxrider thanks for the praise. To answer your Q, we do actually:

https://www.tinymce.com/docs/get-started/first-steps/

![_grab 2018-02-22_10-00-44_am](https://user-images.githubusercontent.com/2252896/36555577-4b6a4f74-17b7-11e8-839f-98b428ed72fa.png)

fwiw, the assumption is that the reader starts with the Get Started guide. You'll see in the example above, the docs would be too verbose if every snippet included the full init. So we keep examples focused on the topic we're discussing. I'll mark this one closed and thanks for using Tiny!
