### ISSUE TITLE
Problem with page get-started/first-steps.md - suggests using Cloud hosted script but is located under "Self Hosted"

### ISSUE THREAD

**Issue by SimonEast** [tinymce/tinymce-docs#656]
> *affected page: https://www.tinymce.com/docs/get-started/first-steps/*

This page is located under the "Self Hosted" section but then describes steps for embedding TinyMCE via the Cloud solution. It's a bit confusing.

**Comment by tylerkelly13** [comment]
Hi @SimonEast,
This page has moved to https://www.tiny.cloud/docs/quick-start/ and is no-longer located under the "Self Hosted" section.
Please reopen or create a new issue if this issue should not have been closed.
