### ISSUE TITLE
Problem with page advanced/creating-custom-dialogs.md

### ISSUE THREAD

**Issue by manu144x** [tinymce/tinymce-docs#657]
It's useful knowing how to pass data from tinymce to the modal window, but what about the other way around, passing data from the window loaded, back to the parent tinymce that opened it?
> *affected page: https://www.tinymce.com/docs/advanced/creating-custom-dialogs/*

**Comment by tylerkelly13** [comment]
Hi @manu144x,
The method is different for version 4 and version 5.
TinyMCE version 4: https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.windowmanager/#getwindows
TinyMCE version 5: https://www.tiny.cloud/docs/ui-components/dialog/#interactivedialogs
Please reopen or create a new issue if this issue should not have been closed.
