### ISSUE TITLE
Problem with page plugins/directionality.md

### ISSUE THREAD

**Issue by ArabGenius** [tinymce/tinymce-docs#659]
> *affected page: https://www.tinymce.com/docs/plugins/directionality/*

Hello
I cant init tinymce as RTL 

this is my code
```
tinymce.init({
  mode : "exact",
  elements : "text_ar",
  directionality : 'rtl',
  language: 'ar',
  branding: false,
  height: 400,
  theme: 'modern',
  plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern help',
  toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat | ltr rtl',
  image_advtab: true
 });
```

**Comment by r12s** [comment]
Hi @ArabGenius including the following in your `init` (as you've done above) will default the content of the editor right-to-left, and change the language of menu bars, etc, to Arabic.

```
directionality: 'rtl',
language: 'ar',
```

![_grab 2018-03-08_05-05-34_pm](https://user-images.githubusercontent.com/2252896/37135759-efa4ea4a-22f2-11e8-98be-4ddf57cf33ab.png)

We're unable to provide support in the docs, please ask your question in the TinyMCE Community https://community.tinymce.com/ Thanks!
