### ISSUE TITLE
Images not deploying

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#66]
Images in here are not getting deployed:
http://beta.tinymce.com/docs/enterprise/check-spelling/troubleshoot/

**Comment by kilianc** [comment]
the url or the image needs to be `{{ site.baseurl }}/path/to/image.png`

http://beta.tinymce.com/docs/images/spell-checking-curl-windows-3.png

**Comment by kilianc** [comment]
I suggest you add `baseurl: "/docs"` to your `config-local.yml`
