### ISSUE TITLE
Problem with page advanced/creating-custom-dialogs.md

### ISSUE THREAD

**Issue by guiu-rocafort** [tinymce/tinymce-docs#668]
This page shows how to create a dialog using the old v3 method using an html file. 
It doesn't document though how to create a custom dialog using the new v4 way.

Found this article: https://makina-corpus.com/blog/metier/2016/how-to-create-a-custom-dialog-in-tinymce-4 

I can't find this documentation in the tinymce documentation anywhere. How to populate the body with the different widgets.

> *affected page: https://www.tinymce.com/docs/advanced/creating-custom-dialogs/*

**Comment by tylerkelly13** [comment]
Hi @guiu-rocafort,
There is now an example of how to create dialog using a html file.
The content has also moved.
See: https://www.tiny.cloud/docs/ui-components/urldialog/#example
This issue has been resolved and will now be closed.
Please reopen or create a new issue if this issue should not have been closed.
