### ISSUE TITLE
Problem with page reference/configuration/Configuration3x@encoding.md

### ISSUE THREAD

**Issue by TBearSantaCruz** [tinymce/tinymce-docs#685]
I am finding that having text like "<3" results in the "<" being encoded.   The documentation indicates encoding should be off by default.  I have no  setting for encoding and tried explicitly setting it to off, but the characters is still being encoded.

**Comment by fyrkant** [comment]
Please open up an issue on the [correct repo](https://github.com/tinymce/tinymce) for bug reports, this repo is only about the documentation.
