### ISSUE TITLE
How add class and content with page plugins/anchor.md

### ISSUE THREAD

**Issue by Hop-Seb** [tinymce/tinymce-docs#687]
Hello,

I would like to custom anchor.
Basically the anchor is for example : 
`<p><a id="start"></a>Hello, World!</p>.`

But I would like to add class and content, something like : 
`<p><a id="start" class="myClass">MyContent</a>Hello, World!</p>.`
And of course I would lik to add these automaticaly!

I have tried several solutions like : 
`selectedNode.setAttribute('class','anchor');`
or
`selectedNode.createAttribute('class');
selectedNode.className = 'anchor';
`
In the plugin.js file in the anchor folder from the mce tiny module...

Thank you for help.

> *affected page: https://www.tinymce.com/docs/plugins/anchor/*

**Comment by fyrkant** [comment]
This isn't the correct repository for this, open up an issue on the [correct one](https://github.com/tinymce/tinymce) for issues/feature requests about tinymce.

But I can answer your question here anyway, no there's no way to configure the anchor plugin to do what you want it to. I'd recommend forking the plugin and implementing it yourself if it's something you really need.
