### ISSUE TITLE
include API examples back in reference

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#69]

**Comment by r12s** [comment]
A number of issues are appearing regarding the API reference. imho, this is now a critical issue impacting user experience with the documentation. Adding to critical milestone.

For example:
http://archive.tinymce.com/wiki.php/api4:method.tinymce.AddOnManager.add
https://www.tinymce.com/docs/api/class/tinymce.addonmanager/

**Comment by kilianc** [comment]
take a look :sunglasses: http://stagecoach.tinymce.com/docs/pr/week-10/api/class/tinymce.editor/

**Comment by androb** [comment]
Looking good Kilian!
