### ISSUE TITLE
Problem with page demo/basic-example.md

### ISSUE THREAD

**Issue by ChangePlaces** [tinymce/tinymce-docs#692]
the 'result' section shows a blank space - and a quick cursory glance shows it happens on the others.

firefox 60.0.1 / windows

> *affected page: https://www.tinymce.com/docs/demo/basic-example/*

**Comment by tylerkelly13** [comment]
The example appears to have been fixed and works as expected at this time.
Please reopen or create a new issue if this issue should not have been closed.
