### ISSUE TITLE
Problem with page advanced/creating-a-skin.md

### ISSUE THREAD

**Issue by Loni2Shoes** [tinymce/tinymce-docs#693]
Instructions indicate that the variables.scss file, but no such file exists in the NPM install, the production download, or the development download. I think these instructions need to be modified, either for correctness or specificity.

> *affected page: https://www.tinymce.com/docs/advanced/creating-a-skin/*

**Comment by tylerkelly13** [comment]
Hi @Loni2Shoes,
The *Create a skin for TinyMCE* page has been updated with the correct file and location.
The issue has been resolved and will now be closed.
Please reopen or create a new issue if this issue should not have been closed.
