### ISSUE TITLE
Problem with page reference/TinyMCE3x@Command_identifiers.md

### ISSUE THREAD

**Issue by EmanueleCiriachi** [tinymce/tinymce-docs#694]
The example of mceReplaceContent is vague and unclear.

> *affected page: https://www.tinymce.com/docs-3x//reference/TinyMCE3x@Command_identifiers/*

**Comment by tylerkelly13** [comment]
Closing this issue. 
TinyMCE 3 is no-longer supported and we no-longer maintain the documentation.
Please reopen or create a new issue if this issue should not have been closed.
