### ISSUE TITLE
Problem with page demo/full-featured.md

### ISSUE THREAD

**Issue by jayenashar** [tinymce/tinymce-docs#700]
I can't seem to load any demos.

> *affected page: https://www.tinymce.com/docs/demo/full-featured/*

I see this in the console (Firefox 60):
> SecurityError: The operation is insecure.
tinymce.min.js:8
ReferenceError: tinymce is not defined[Learn More]
NGegZK:89:7
SecurityError: The operation is insecure.
storage.js:2

**Comment by jayenashar** [comment]
maybe duplicate of #692

**Comment by tylerkelly13** [comment]
The example appears to have been fixed and works as expected at this time.
Please reopen or create a new issue if this issue should not have been closed.

**Comment by jayenashar** [comment]
confirmed as fixed
