### ISSUE TITLE
Problem with counter

### ISSUE THREAD

**Issue by surabhi-khandelwal** [tinymce/tinymce-docs#713]
I need to calculate remaining character count. So for calculating number of entered characters, I used following code - 
var body = tinymce.get(id).getBody();
text = tinymce.trim(body.innerText || body.textContent);
totalchar = text.length;

But this will give me wrong count, as It always increase its count by one. So, can anyone please help me out for the same.

Here is the code for initialization of editor - 
tinyMCE.init({
		selector: "#note_content",
	 	height: 145,
	 	plugins: [
	   		"link anchor autolink",
	   		"paste",    
	 	],
	 	menubar: false, 
	 	branding: false,	  
	 	statusbar: false,
		toolbar: false,
		// schema: 'html5-strict',
		invalid_elements : 'script',
		forced_root_block : '',
		force_p_newlines: false,
		force_br_newlines: false,
		// remove_redundant_brs : false,		
		paste_word_valid_elements: 'a[href|target|title|alt|target=_blank]',
		valid_elements : 'a[href|target|title|alt|target=_blank]',
   		charLimit : messages.NOTES_MESSAGES_VALIDATION.TOTAL_CHARACTER_COUNT, // this is a default value which can get modified later
		protect: [
			/\<\/?(if|endif)\>/g,  // Protect <if> & </endif>
			/\<xsl\:[^>]+\>/g,  // Protect <xsl:...>
			/<\?php.*?\?>/g  // Protect php code
		],		
		paste_as_text: true
	});

**Comment by tylerkelly13** [comment]
An API has been added for this:
```console.log(wordcount.body.getCharacterCountWithoutSpaces());```
https://www.tiny.cloud/docs/plugins/wordcount/#api
