### ISSUE TITLE
Explore Gzip Compressing Content

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#73]
Our lack of compression is hurting our speed a bit. At least in the eyes of Google's PageSpeed:
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fbeta.tinymce.com%2Fdocs%2F&tab=desktop

Unfortunately S3 doesn't do this automatically and there appears to be quite a few hoops to jump through:
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3

**Comment by androb** [comment]
We would need to GZip before upload and add metadata during upload:
http://www.rightbrainnetworks.com/blog/serving-compressed-gzipped-static-files-from-amazon-s3-or-cloudfront/

Note we should set the cache-control headers a little bit more sensibly when/if we do this.

**Comment by kilianc** [comment]
nginx keeps making even more sense day after day :)

**Comment by androb** [comment]
Completely agree @kilianc . nginx or Apache rather than S3 would solve our problem. And it would let us manage redirects on 404s a lot easier. With CloudFront out in front it is actually better as it is a bit easier setting cache-control headers too.

**Comment by kilianc** [comment]
We diced to go with nginx, everything will be taken care of there
