### ISSUE TITLE
Problem with page general-configuration-guide/upload-images.md

### ISSUE THREAD

**Issue by mt-xing** [tinymce/tinymce-docs#734]
The second sentence on the page, which reads:

> Local images that are added through other means, for example drag and drop when using the paste_data_images configuration property, or using Tiny's PowerPaste Plugin.

is not a complete sentence and reads as if it was cut off.

> *affected page: https://www.tinymce.com/docs/general-configuration-guide/upload-images/*

**Comment by tylerkelly13** [comment]
The issue has been fixed and the new version will be live later this week.
