### ISSUE TITLE
Problem with page advanced/creating-a-plugin.md

### ISSUE THREAD

**Issue by rjgamer** [tinymce/tinymce-docs#735]
Language localization is only working for custom plugins, when the location of the plugin is in the plugins directory of your current TinyMCE installation (e.g. tinymce/plugins/{custom-plugin-name}) . But when the plugin is external (e.g. myscripts/custom-plugin.tinymce.js) then the language files doesn't get loaded.

The solution is to load the plugin with the plugin manager of TinyMCE and not directly.

Working:
```
<script src="tinymce/tinymce.min.js"></script>
<script>
  tinymce.PluginManager.load('custom-plugin','./myscripts/custom-plugin.tinymce.js');
</script>
```

Is not working:
```
<script src="tinymce/tinymce.min.js"></script>
<script src="myscripts/custom-plugin.tinymce.js"></script>
```

You should address this issue. I'm not the only one with this problem. Check this question:
https://community.tinymce.com/communityQuestion?id=90661000000MrmNAAS

> *affected page: https://www.tinymce.com/docs/advanced/creating-a-plugin/*

**Comment by fyrkant** [comment]
For bug reports please create an issue on the correct repo, this repo is only about the documentation, not about the product. This is where you should create an issue: https://github.com/tinymce/tinymce/issues
