### ISSUE TITLE
Problem with page quick-start.md

### ISSUE THREAD

**Issue by abssorb** [tinymce/tinymce-docs#737]
> *affected page: https://www.tinymce.com/docs/quick-start/*

No good for total newbies.  I spent a few minutes looking around the site, did a download and it's a bunch of Javascript.  Looked further and I'm sort of getting the concept, but I went looking for an explanation of the concept / strategy / architecture to see what kind of beast tinyMCE is and I found nothing.

There is only quick start instructions for those people who already know the architecture model.

Add this line to your browser means nothing to those people expecting the download to be a .deb or .exe, for an app that will run on their desktop - and it's not at all obvious what will result if the instructions are followed blindly.

**Comment by tylerkelly13** [comment]
Hi @abssorb,
Since you opened this issue, a new page has been added to the docs which is better for new users:
https://www.tiny.cloud/docs/general-configuration-guide/
The Quick Start page does need some improvement.

**Comment by tylerkelly13** [comment]
Closing this issue.
Please reopen or create a new issue if this issue should not have been closed.
