### ISSUE TITLE
Problem with page reference/configuration/Configuration3x@external_media_list_url.md

### ISSUE THREAD

**Issue by HansPeterHaastrup** [tinymce/tinymce-docs#771]
I've found a couple of errors in the supplied PHP file for generating the .js list:

1. the array name should be tinyMCEMediaList and not tinyMCEImageList
2. $delimiter should be '\n' and not just 'n'.

> *affected page: https://www.tinymce.com/docs-3x//reference/configuration/Configuration3x@external_media_list_url/*

**Comment by tylerkelly13** [comment]
Closing this issue. TinyMCE 3 is no-longer supported and we no-longer maintain the documentation.
Please reopen or create a new issue if this issue should not have been closed.
