### ISSUE TITLE
Problem with page plugins/code.md

### ISSUE THREAD

**Issue by rajmondburgaj** [tinymce/tinymce-docs#788]
> *affected page: https://www.tinymce.com/docs/plugins/code/*

Does this `code_dialog_width` apply to v5 ? because to me does not seem to work ?

here is my code:

    tinymce.init({
            selector: 'textarea',
            plugins: 'code print preview searchreplace autolink ' +
                'directionality visualblocks visualchars fullscreen ' +
                'image link media template codesample table ' +
                'charmap hr pagebreak nonbreaking anchor ' +
                'toc insertdatetime advlist lists textcolor ' +
                'wordcount colorpicker textpattern help fileManager',
            toolbar:
                'formatselect fullscreen code | bold italic strikethrough forecolor backcolor preview codesample image | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat',
            code_dialog_height: 600
        });

**Comment by tylerkelly13** [comment]
Hi @rajmondburgaj,
Apparently that setting has been deprecated.
