### ISSUE TITLE
OpenWindow and CloseWindow events undocumented

### ISSUE THREAD

**Issue by md5** [tinymce/tinymce-docs#789]
**Do you want to request a *feature* or report a *bug*?**

Documentation request

**What is the current behavior?**

`OpenWindow` and `CloseWindow` events aren't documented. Looks like the events were added in this commit (first released in 4.3.4): https://github.com/tinymce/tinymce/commit/7ac335d8f5761181c8b23fae5217a3c8a86f58b7

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Not a bug.

**What is the expected behavior?**

`OpenWindow` and `CloseWindow` should be documented if they're part of the public API.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.8.3

**Comment by tylerkelly13** [comment]
Hi @md5,
The developers have indicated that `OpenWindow` and `CloseWindow` were documented because they are _not_ part of the public API. These events are _experimental_ and are not supported.
