### ISSUE TITLE
T4 Tiny Drive demo, wrong editor

### ISSUE THREAD

**Issue by Afraithe** [tinymce/tinymce-docs#791]
The T4 demo for Tiny Drive has the V5 editor.

Also, the menu item name is different, in V4 its "Drive", in V5 its "Tiny Drive", should probably be "Drive".

**Comment by tylerkelly13** [comment]
> The T4 demo for Tiny Drive has the V5 editor.
> 
> Also, the menu item name is different, in V4 its "Drive", in V5 its "Tiny Drive", should probably be "Drive".

Given that this issue was raised prior to the release of TinyMCE 5, is this still required @Afraithe ? If yes, which demo on which page?

**Comment by tylerkelly13** [comment]
Fixed. Correct editor version showing at: https://www.tiny.cloud/docs-4x/demo/drive/
