### ISSUE TITLE
Problem with media embed

### ISSUE THREAD

**Issue by cesar19004** [tinymce/tinymce-docs#852]
embed code from twitter does not works. but if you put a blank space or any text in general tab, and next paste your tweet code, it works fine

**Comment by tylerkelly13** [comment]
This bug appears to have been resolved in TinyMCE 5.
Note that bugs related to the TinyMCE editor should be directed to https://github.com/tinymce/tinymce
Please reopen or create a new issue if this issue should not have been closed.
