### ISSUE TITLE
Sidenav highlighting sometimes highlights two points

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#86]
See attached image. When there are two articles in view (such as in the config section) two nav items can be highlighted. Not a showstopper but visually not ideal.

![image](https://cloud.githubusercontent.com/assets/2160304/11091989/93969448-8834-11e5-98d3-e12b8b49347d.png)

**Comment by kilianc** [comment]
![](https://www.dropbox.com/s/gxbong6nlu8hrth/Screenshot%202015-11-11%2014.01.36.png?dl=1)

What should be on in this case?

**Comment by r12s** [comment]
@kilianc I think auto_focus. It seems reasonable that the "focus" would be the top anchor, not both. If a user had selected automatic_uploads then that would (be at the top of the page and naturally) be the focus, not the content below it.

There are other examples where three nav links are highlighted. In the image (below) the top highlighted link isn't in the viewport and the bottom one has just appeared.

No idea how to fix this but I bet it'll involve your script magic and some math :-)

![tinymce-link-focus](https://cloud.githubusercontent.com/assets/2252896/11166268/7aed8014-8ae1-11e5-9ee4-dfb11281600e.png)

**Comment by kilianc** [comment]
@r12s yep, as you said it's not the technical side that stopped me but rather not knowing what the desired behavior was. On it!

**Comment by kilianc** [comment]
fixed
