### ISSUE TITLE
Problem with page quick-start.md

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [tinymce/tinymce-docs#861]
I dont know how to get the value of editor

> *affected page: https://www.tinymce.com/docs/quick-start/*

**Comment by tylerkelly13** [comment]
Hi @lolPlatinumPlayer 
This page has moved for version 5.
If I understand correctly, the question relates to calling the editor the body of the html.
The selector defined in the `tinymce.init` script is called in the `textarea` element.
For example, `#mytextarea`:
```
  tinymce.init({
    selector: '#mytextarea'
  });
```
defines the editor called at `id="mytextarea"`:
```
<textarea id="mytextarea">Hello, World!</textarea>
```
For more information, see: https://www.tiny.cloud/docs/general-configuration-guide/basic-setup/#selectorconfiguration

**Comment by tylerkelly13** [comment]
If this does not answer your question, please provide more information.

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
