### ISSUE TITLE
Problem with page advanced/keyboard-shortcuts.md

### ISSUE THREAD

**Issue by speedyhoon** [tinymce/tinymce-docs#863]
Broken link to blog post: creating-keyboard-shortcuts-tinymce

Located under heading **Add custom shortcuts to TinyMCE** within the last sentance.

> *affected page: https://www.tinymce.com/docs/advanced/keyboard-shortcuts/*

**Comment by tylerkelly13** [comment]
The link appears to have been fixed. Both links under **Add custom shortcuts to TinyMCE** are now working correctly.
Please reopen or create a new issue if this issue should not have been closed.
