### ISSUE TITLE
v5 RC1 "Migration from V4" Plugin links broken

### ISSUE THREAD

**Issue by martyf** [tinymce/tinymce-docs#869]
Under "[Migration from V4 > Plugins](https://www.tiny.cloud/docs-beta/migration-from-4x/#plugins)", under "Removed Features" are four listed plugins.

"Code" is correctly linked.

However "Codesample", "Preview" and "Template" are broken links (404) due to a missing slash.

Correct, "Code" is:
`https://www.tiny.cloud/docs-beta/plugins/code/`

Incorrect, "Codesample" is:
`https://www.tiny.cloud/docs-betaplugins/codesample/`

Adding a slash before "plugins" fixes the link:
`https://www.tiny.cloud/docs-beta/plugins/codesample/`

**Comment by TheSpyder** [comment]
Our documentation is public, documentation issues can be logged here :)

**Comment by martyf** [comment]
Did you want a pull request, or just logging of the issue?

**Comment by TheSpyder** [comment]
We are happy to receive PRs for documentation issues if you are willing to help 😁

**Comment by tylerkelly13** [comment]
This issue appears to have been resolved.
Please reopen or create a new issue if this issue should not have been closed.
