### ISSUE TITLE
Contribute icon not ideal

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#87]
This might be a matter of taste but it kind of looks like a no smoking sign.
Perhaps we should try and icon without the circle around it?

**Comment by lucaorio** [comment]
![screenshot 2015-11-11 22 08 54](https://cloud.githubusercontent.com/assets/299621/11111749/dbc69d6c-88c0-11e5-8b9f-4244b9e4552a.jpg)
Already pushed the changes! Let me know if it works better. :+1:
