### ISSUE TITLE
How to set a wide dialog box?

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce-docs#882]
there is a suitable class "tox-dialog--width-lg" but how to set?

**Comment by TheSpyder** [comment]
@shikhanansi please add this to the 5.x todo pile 🤔

**Comment by tylerkelly13** [comment]
This issue appears to have been resolved. Information on configuring a dialog box, including the size can be found here:
https://www.tiny.cloud/docs/ui-components/dialog/#configurationoptions
Please reopen or create a new issue if this issue should not have been closed.
