### ISSUE TITLE
TinyMCE 5: Broken link in documentation

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce-docs#904]
There's "context menu examples." link (that point's to https://www.tiny.cloud/docs-beta/ui-elements/contextmenu) in https://www.tiny.cloud/docs-beta/configure/editor-appearance/.

**Comment by tylerkelly13** [comment]
The `tiny.cloud/docs-beta/` has been deprecated, so i'm moving this bug to closed.
Please reopen or create a new issue if this issue should not have been closed.
