### ISSUE TITLE
Ensure consistency of spelling

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce-docs#91]
spell checker vs. spellchecker

PowerPaste vs Power Paste

others?

**Comment by r12s** [comment]
* should be spellcheck not spell check. fixed in #93 
* PowerPaste inconsistent in source docs. used form in titles (PowerPaste). changed in #93 
* on the lookout for other inconsistencies or incorrect useage and will fix as they're found.

Leaving issue open and will review.

**Comment by r12s** [comment]
* Spellcheck style now two words (spell check) reversing previous decision.
* TinyMCE PowerPaste is correct. Ephox Power Paste is of course a different product. This was resolved in previous commit.

Marking this as closed and will address ad hoc instances raised as docs go live.
