### ISSUE TITLE
Problem with page reference/configuration/Configuration3x@file_browser_callback.md

### ISSUE THREAD

**Issue by kkoston** [tinymce/tinymce-docs#913]
The function should be the actual function not the string with function name. 
`tinyMCE.init({
  file_browser_callback : "myCustomFileBrowser"
});`

should be
`tinyMCE.init({
  file_browser_callback : myCustomFileBrowser
});`
> *affected page: https://www.tinymce.com/docs-3x/reference/configuration/Configuration3x@file_browser_callback/*

**Comment by tylerkelly13** [comment]
Closing this issue.
TinyMCE 3 is no-longer supported and we no-longer maintain the documentation.
Please reopen or create a new issue if this issue should not have been closed.
