### ISSUE TITLE
Problem with page configure/jwt-authentication.md

### ISSUE THREAD

**Issue by samgedert** [tinymce/tinymce-docs#935]
> *affected page: https://www.tinymce.com/docs/configure/jwt-authentication/*

I'm still a pretty green developer, so it's possible the only issue is my ignorance.

That being said, I'm not able to fill in the gaps between the instructions in the documentation.

I have created my public and private keys.  I have uploaded a copy of the 'php-jwt-master' to my server.

Regarding the 'PHP token provider example', I don't know if this is a separate file or a snippet of code that needs to go into another existing file.

**Comment by tylerkelly13** [comment]
> URL in TinyMCE 5 documentation: https://www.tiny.cloud/docs/tinydrive/jwt-authentication/

Marking this issue as an enhancement request to technical knowledge required to use the Tiny Drive JWT docs.

**Comment by tylerkelly13** [comment]
This page has been updated since the issue was logged. The codeblock in question is a separate file (see the heading over the codeblock).
