### ISSUE TITLE
Problem with page reference/configuration/Configuration3x@height.md

### ISSUE THREAD

**Issue by Juggern4ut** [tinymce/tinymce-docs#950]
Setting the height to `height : "480"` will not work. It is not mentioned in the article but you need to add "px" or "%" to the value.

`height: "480px"` would be correct

> *affected page: https://www.tinymce.com/docs-3x/reference/configuration/Configuration3x@height/*

**Comment by tylerkelly13** [comment]
Closing this issue. TinyMCE 3 is no-longer supported and we no-longer maintain the documentation.
Please reopen or create a new issue if this issue should not have been closed.
