### ISSUE TITLE
Problem with page reference/for-dummies.md

### ISSUE THREAD

**Issue by stevesss** [tinymce/tinymce-docs#967]
I need more information about controlling where and how the publishing is done.
> *affected page: https://www.tinymce.com/docs-3x/reference/for-dummies/*

**Comment by tylerkelly13** [comment]
@stevesss could you provide more detail please?

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
