### ISSUE TITLE
Problem with page advanced/yeoman-generator.md

### ISSUE THREAD

**Issue by maz0717** [tinymce/tinymce-docs#971]
Following the instructions on this page I receive an error:
Failed to initialize plugin: test-plugin Error: editor.addButton has been removed in tinymce 5x ...

I'm guessing that the yeoman generator only generates 4x plugins.

> *affected page: https://www.tinymce.com/docs/advanced/yeoman-generator/*

**Comment by tylerkelly13** [comment]
Hi @maz0717,
Sorry it has taken a while to get back to you. The addButton method did move for TinyMCE 5, but I'm not sure if this is an isolated bug in the generator or if it hasn't been updated for TinyMCE 5. I'll check with the devs and update the page if required.

**Comment by tylerkelly13** [comment]
Scratch that. I had a look at the code and it looks like the yeoman generator has been updated for TinyMCE 5 and the correct method is now used (`editor.ui.registry.addButton`).
