### ISSUE TITLE
Problem with page advanced/creating-a-plugin.md

### ISSUE THREAD

**Issue by DeanWard** [tinymce/tinymce-docs#986]
> *affected page: https://www.tiny.cloud/docs/advanced/creating-a-plugin/*

Documentation appears to be out of date. editor.addButton is no longer used according to the errors thrown by tiny when trying to use it.

**Comment by tylerkelly13** [comment]
The issue was resolved by: https://github.com/tinymce/tinymce-docs/commit/d9d2c65ab176c0f43fedfd809758d7df15aec663
Please reopen or create a new issue if this issue should not have been closed.
