### ISSUE TITLE
Problem with page demo/local-upload.md

### ISSUE THREAD

**Issue by awan2008** [tinymce/tinymce-docs#998]
Can we display the actual image here:

> *affected page: https://www.tiny.cloud/docs/demo/local-upload/*

**Comment by tylerkelly13** [comment]
Hi @awan2008,
Could you please provide more information?
I have also noticed that the screenshot needs updating, hopefully I can address your issue at the same time.

**Comment by tylerkelly13** [comment]
Closing this issue due to lack of information.
Please reopen or create a new issue if this issue should not have been closed.
