### ISSUE TITLE
Problem with page advanced/creating-custom-dialogs.md

### ISSUE THREAD

**Issue by reynave** [tinymce/tinymce-docs#999]
I have tried many times tinymce 5.0.2, but windowManager.open with url doesn't work, but its worked well on ver 4.. 

> *affected page: https://www.tiny.cloud/docs/advanced/creating-custom-dialogs/*

**Comment by lnewson** [comment]
I can confirm this page is out of date sorry, as url dialogs were removed in v5, though we are planning to bring them back: https://github.com/tinymce/tinymce/issues/4786 The docs for creating dialogs are now located here:
- Dialogs overview: https://www.tiny.cloud/docs/ui-components/dialog/
- DIalog Components: https://www.tiny.cloud/docs/ui-components/dialogcomponents/

**Comment by lnewson** [comment]
Looking more it seems that this page was removed from the navigation for v5, but wasn't deleted entirely so it's still accessible by search, etc... I'll follow up with the team to get this page properly removed to avoid confusion until url dialogs are back.

**Comment by lnewson** [comment]
The old left over pages have been cleaned up and shouldn't be accessible anymore.

Also just as a heads up, we've just merged the new docs for bringing back URL dialog functionality (https://github.com/tinymce/tinymce-docs/pull/1021), so expect to see that functionality back soon!
